
import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from 'dotenv';
import { GoogleGenAI } from "@google/genai";

dotenv.config();

// Lazy initialization of Gemini SDK
let aiClientInstance: GoogleGenAI | null = null;
    // @ts-ignore - auto generated by cleanup
function getGeminiClient(): GoogleGenAI {
  if (!aiClientInstance) {
    const key = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || process.env.API_KEY || process.env.VITE_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY is not defined in the environment variables (checked GEMINI_API_KEY, VITE_GEMINI_API_KEY, API_KEY, VITE_API_KEY).");
    }
    aiClientInstance = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClientInstance;
}

// Résolution universelle __dirname pour ESM (dev) et CJS (build)
const _filename = typeof __filename !== 'undefined' ? __filename : (typeof import.meta !== 'undefined' && import.meta.url ? fileURLToPath(import.meta.url) : '');
const _dirname = typeof __dirname !== 'undefined' ? __dirname : (_filename ? path.dirname(_filename) : process.cwd());

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Increase payload limit for large requests (e.g., OCR images)
  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ extended: true, limit: '50mb' }));

    // @ts-ignore - auto generated by cleanup
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(_dirname, "dist")));
    // @ts-ignore - auto generated by cleanup
    app.get("*all", (req, res) => {
      res.sendFile(path.join(_dirname, "dist", "index.html"));
    });
  }

    // @ts-ignore - auto generated by cleanup
  const httpServer = app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
