import { fetchResults } from './lotteryService';
import type { AlgoWeights, AdaptiveRules, OptimizationResult, GeneticConfig, DrawResult } from '../types';
// Assurez-vous que le chemin correspond à votre structure (ex: '../mathService' ou './mathService')
import { calculateFractalIndex, calculateShannonEntropy } from './mathService'; 
import { purifyHistoryForDraw } from '../utils/arrayUtils'; 

/**
 * CALCUL DE LA CONFIGURATION GÉNÉTIQUE DÉTERMINISTE ET ADAPTATIVE
 * 
 * Remplace les constantes magiques (0.30, 0.70, 100) par des dérivations topologiques
 * basées sur la dimensionalité de l'espace de recherche et le régime stochastique des données.
 */
export const getDynamicConfig = (
  numWeights: number, 
  history: DrawResult[]
): GeneticConfig & { regimeMetrics?: { hurst: number, entropy: number } } => {
  
  const historyLength = history.length;
  
  // 1. Taille de Population : Dérivée de la dimensionalité et de l'information disponible.
  // Formule théorique : N_pop = N_features * log2(N_samples) pour couvrir l'espace sans explosion combinatoire.
  const log2History = Math.max(1, Math.log2(historyLength));
  const populationSize = Math.ceil(numWeights * log2History * 2);

  // 2. Métriques de Régime
  const hurst = calculateFractalIndex(history);
  const entropy = calculateShannonEntropy(history.slice(0, Math.min(100, historyLength))).normalized;
  
  const persistenceFactor = Math.max(Number.EPSILON, Math.min(1 - Number.EPSILON, hurst));
  const chaosFactor = Math.max(Number.EPSILON, Math.min(1 - Number.EPSILON, entropy));

  // 3. Taux d'Élitisme : Inversement proportionnel au chaos. 
  // Plus le système est chaotique, plus on doit préserver la diversité (élitisme faible).
  const eliteRatio = 0.05 + (0.10 * (1.0 - chaosFactor));
  const eliteSize = Math.max(2, Math.floor(populationSize * eliteRatio));

  // 4. Taux de Mutation : Dérivé de la borne théorique d'erreur d'échantillonnage et du chaos.
  // Base = 1 / sqrt(N_features). Amplifié par le chaos pour échapper aux minima locaux.
  const baseMutation = 1.0 / Math.sqrt(numWeights);
  const mutationRate = Math.min(0.2, baseMutation * (1.0 + chaosFactor));

  // 5. Taux de Croisement : Favorisé si le système est persistant (Hurst > 0.5).
  const baseCrossover = 0.60;
  const crossoverRate = Math.min(0.95, baseCrossover + (persistenceFactor * 0.35));

  // 6. Générations Max : Dérivée de la taille de la population et de la complexité, avec rendements décroissants.
  const maxGenerations = Math.ceil(populationSize * 0.5 + (numWeights * Math.log2(numWeights + 1)));

  // 7. Arrêt Anticipé : Basé sur la variance de la fitness, pas un compteur fixe. 
  // On définit une fenêtre d'observation proportionnelle à la complexité.
  const earlyStopGenerations = Math.max(5, Math.ceil(Math.sqrt(maxGenerations)));

  // 8. Profondeur d'Histoire : Dérivée de la demi-vie de l'autocorrélation (liée à Hurst).
  const historyDepth = Math.max(20, Math.min(historyLength, Math.ceil(historyLength * (1.0 - Math.abs(hurst - 0.5)))));

  return {
    populationSize,
    eliteSize,
    mutationRate,
    crossoverRate,
    maxGenerations,
    historyDepth,
    earlyStopGenerations,
    regimeMetrics: { hurst, entropy } 
  };
};

export const runGeneticOptimization = async (
  drawName: string,
  baseWeights: AlgoWeights,
  baseRules: AdaptiveRules,
  options?: Partial<GeneticConfig>,
  onRawProgress?: (data: Record<string, unknown>) => void
): Promise<OptimizationResult> => {
  const startTime = Date.now();
  
  const { data: rawHistory } = await fetchResults(drawName);  
  const fullHistory = purifyHistoryForDraw(drawName, rawHistory);
  
  // Validation : Taille effective d'échantillon (N_eff) pour validité statistique
  if (fullHistory.length < 5) {
    throw new Error(`Historique insuffisant pour l'inférence génétique (minimum absolu de 5 tirages requis).`);
  }
  const h = calculateFractalIndex(fullHistory);
    // @ts-ignore - auto generated by cleanup
  const minHistoryRequired = Math.ceil(30 * ((1 + Math.abs(h)) / (1 - Math.abs(h) + Number.EPSILON)));
  
  // Allègement des données pour le transfert au Worker (évite les surcharges mémoire)
  const historyLite = fullHistory.map(h => ({ 
    gagnants: h.gagnants, 
    machine: h.machine || [] 
  }));
  
  // La configuration est maintenant dérivée mathématiquement de l'histoire et de la dimensionalité
  const baseConfig = getDynamicConfig(Object.keys(baseWeights).length, fullHistory);
  const config = { ...baseConfig, ...options } as GeneticConfig;

  return new Promise((resolve, reject) => {
    if (typeof Worker === 'undefined') {
      console.warn("Web Worker non disponible, fallback déterministe vers les poids de base.");
      resolve({ 
        bestChromosome: { weights: baseWeights, rules: baseRules }, 
        generations: 0, 
        timeElapsed: Date.now() - startTime, 
        totalEvaluations: 0 
      } as unknown as OptimizationResult);
      return;
    }

    // Note: Assurez-vous que le chemin du worker correspond à votre structure de projet
    const worker = new Worker(new URL('./workers/genetic.worker.ts?worker', /* @ts-ignore */ import.meta.url), { type: 'module' });

    worker.onmessage = (e) => {
      const { type, data, message } = e.data;
      if (type === 'progress') {
        if (onRawProgress) onRawProgress(data);
      } else if (type === 'result') {
        worker.terminate();
        resolve({ 
          ...data, 
          timeElapsed: Date.now() - startTime, 
          // Le nombre total d'évaluations est une borne supérieure théorique basée sur la config
          totalEvaluations: config.populationSize * (data.generations || config.maxGenerations) 
        });
      } else if (type === 'error') {
        worker.terminate();
        reject(new Error(message || "Erreur inconnue dans le Genetic Worker"));
      }
    };
    worker.onerror = (err) => {
      worker.terminate();
      reject(new Error(`Échec de l'exécution du Worker Génétique: ${err.message}`));
    };

    // Envoi de la charge utile avec la configuration déterministe et les métriques de régime
    worker.postMessage({ 
      type: 'start', 
      payload: { 
        drawName, 
        history: historyLite, 
        baseWeights, 
        baseRules, 
        config,
        timeSignature: `${drawName}_${history.length}_${historyLite.length}`
      } 
    });
  });
};
