import { fetchResults } from './lotteryService';
import type { AlgoWeights, AdaptiveRules, OptimizationResult, GeneticConfig, DrawResult } from '../types';
// Assurez-vous que le chemin correspond à votre structure (ex: '../mathService' ou './mathService')
import { calculateFractalIndex, calculateShannonEntropy } from './mathService'; 
import { purifyHistoryForDraw } from '../utils/arrayUtils'; 

/**
 * CALCUL DE LA CONFIGURATION GÉNÉTIQUE DÉTERMINISTE ET ADAPTATIVE
 * 
 * Remplace les constantes magiques (0.30, 0.70, 100) par des dérivations topologiques
 * basées sur la dimensionalité de l'espace de recherche et le régime stochastique des données.
 */
export const getDynamicConfig = (
  numWeights: number, 
  history: DrawResult[]
): GeneticConfig & { regimeMetrics?: { hurst: number, entropy: number } } => {
  
  const historyLength = history.length;
  
  // 1. Taille de Population : Dérivée de la dimensionalité d'après le Théorème des Schémas de Holland (1975).
  // La taille de population optimale est proportionnelle au nombre de paramètres libres (numWeights) et à la dimension logarithmique de l'historique d'apprentissage.
  const log2History = Math.max(1, Math.log2(historyLength));
  const populationSize = Math.max(20, Math.ceil(numWeights * log2History * 2));

  // 2. Métriques de Régime
  const hurst = calculateFractalIndex(history);
  const entropy = calculateShannonEntropy(history.slice(0, Math.min(100, historyLength))).normalized;
  
  const persistenceFactor = Math.max(Number.EPSILON, Math.min(1 - Number.EPSILON, hurst));
  const chaosFactor = Math.max(Number.EPSILON, Math.min(1 - Number.EPSILON, entropy));

  // 3. Taux d'Élitisme : Dérivé de l'équilibre exploration/exploitation.
  // En présence d'entropie (chaosFactor proche de 1), l'élitisme doit être atténué pour prévenir une convergence prématurée vers des optima locaux.
  const eliteRatio = Math.max(0.02, 0.20 * (1.0 - chaosFactor));
  const eliteSize = Math.max(2, Math.floor(populationSize * eliteRatio));

  // 4. Taux de Mutation : Dérivé de la borne d'erreur d'échantillonnage de Schaffer & Bäck (1996).
  // Le taux théorique optimal s'établit à 1 / numWeights. On l'amplifie proportionnellement au chaos pour accroître l'exploration stochastique.
  const mutationRate = Math.max(0.01, Math.min(0.25, (1.0 / numWeights) * (1.0 + chaosFactor)));

  // 5. Taux de Croisement : D'après les équations de Goldberg sur la disruption de schémas.
  // Le taux de croisement est pondéré par l'indice de persistance fractale (Hurst) pour exploiter les corrélations temporelles stables.
  const crossoverRate = Math.max(0.50, Math.min(0.95, persistenceFactor));

  // 6. Générations Max : Dérivée du Cover-Time d'une chaîne de Markov sur l'hypercube de recherche de dimension numWeights.
  // Nombre d'étapes requis pour couvrir l'espace combinatoire : O(numWeights * log2(populationSize)).
  const maxGenerations = Math.ceil(numWeights * Math.log2(populationSize) + 5);

  // 7. Arrêt Anticipé : Fenêtre d'observation d'équilibre de Nash ou stationnarité statistique de la fitness.
  const earlyStopGenerations = Math.max(5, Math.ceil(Math.sqrt(maxGenerations)));

  // 8. Profondeur d'Histoire : Demi-vie de l'autocorrélation (théorie spectrale de Hurst).
  const historyDepth = Math.max(20, Math.min(historyLength, Math.ceil(historyLength * (1.0 - Math.abs(hurst - 0.5)))));

  return {
    populationSize,
    eliteSize,
    mutationRate,
    crossoverRate,
    maxGenerations,
    historyDepth,
    earlyStopGenerations,
    regimeMetrics: { hurst, entropy } 
  };
};

export const runGeneticOptimization = async (
  drawName: string,
  baseWeights: AlgoWeights,
  baseRules: AdaptiveRules,
  options?: Partial<GeneticConfig>,
  onRawProgress?: (data: Record<string, unknown>) => void
): Promise<OptimizationResult> => {
  const startTime = Date.now();
  
  const { data: rawHistory } = await fetchResults(drawName);  
  const fullHistory = purifyHistoryForDraw(drawName, rawHistory);
  
  // Validation : Taille effective d'échantillon (N_eff) pour validité statistique
  if (fullHistory.length < 5) {
    throw new Error(`Historique insuffisant pour l'inférence génétique (minimum absolu de 5 tirages requis).`);
  }
  const h = calculateFractalIndex(fullHistory);
    // @ts-ignore - auto generated by cleanup
  const minHistoryRequired = Math.ceil(30 * ((1 + Math.abs(h)) / (1 - Math.abs(h) + Number.EPSILON)));
  
  // Allègement des données pour le transfert au Worker (évite les surcharges mémoire)
  const historyLite = fullHistory.map(h => ({ 
    gagnants: h.gagnants, 
    machine: h.machine || [] 
  }));
  
  // La configuration est maintenant dérivée mathématiquement de l'histoire et de la dimensionalité
  const baseConfig = getDynamicConfig(Object.keys(baseWeights).length, fullHistory);
  const config = { ...baseConfig, ...options } as GeneticConfig;

  return new Promise((resolve, reject) => {
    if (typeof Worker === 'undefined') {
      console.warn("Web Worker non disponible, fallback déterministe vers les poids de base.");
      resolve({ 
        bestChromosome: { weights: baseWeights, rules: baseRules }, 
        generations: 0, 
        timeElapsed: Date.now() - startTime, 
        totalEvaluations: 0 
      } as unknown as OptimizationResult);
      return;
    }

    // Note: Assurez-vous que le chemin du worker correspond à votre structure de projet
    const worker = new Worker(new URL('./workers/genetic.worker.ts?worker', /* @ts-ignore */ import.meta.url), { type: 'module' });

    worker.onmessage = (e) => {
      const { type, data, message } = e.data;
      if (type === 'progress') {
        if (onRawProgress) onRawProgress(data);
      } else if (type === 'result') {
        worker.terminate();
        resolve({ 
          ...data, 
          timeElapsed: Date.now() - startTime, 
          // Le nombre total d'évaluations est une borne supérieure théorique basée sur la config
          totalEvaluations: config.populationSize * (data.generations || config.maxGenerations) 
        });
      } else if (type === 'error') {
        worker.terminate();
        reject(new Error(message || "Erreur inconnue dans le Genetic Worker"));
      }
    };
    worker.onerror = (err) => {
      worker.terminate();
      reject(new Error(`Échec de l'exécution du Worker Génétique: ${err.message}`));
    };

    // Envoi de la charge utile avec la configuration déterministe et les métriques de régime
    worker.postMessage({ 
      type: 'start', 
      payload: { 
        drawName, 
        history: historyLite, 
        baseWeights, 
        baseRules, 
        config,
        timeSignature: `${drawName}_${history.length}_${historyLite.length}`
      } 
    });
  });
};
