import type { PredictionHistoryItem, DrawResult, AlgoWeights } from "../types";
import {
  applyMetaLearning,
  saveAlgoWeights,
  getAlgoWeights,
  normalizeWeights,
} from "./prediction/weightsManager";
import { WeightVersionManager } from "./prediction/WeightVersionManager";
import { getLocalForensicReports } from "./postPredictionAnalysisService";
import { fetchResults } from "./lotteryService";
import { runBacktestTraining } from "./backtestService";
import { logger } from "../utils/logger";
import { driftDetector } from "./prediction/conceptDriftDetector";
import { isSupabaseConfigured } from "./supabaseClient";
import { apiClient } from "../core/api/apiClient";
import { useNexusStore } from "../store/useNexusStore";

export interface LearningStatus {
  lastRun: string | null;
  improvement: boolean;
  message: string;
  delta?: string;
  weights?: AlgoWeights;
  requiresHumanValidation?: boolean;
  rollbackAvailable?: boolean;
  oldScore?: number;
  newScore?: number;
  weightChanges?: Record<string, number>;
  criticalDecision?: string;
}

export interface LearningConfig {
  minHistorySize: number;
  minImprovementDelta: number;
  maxWeightChangePercent: number;
  validationSampleSize: number;
  driftWindowRecent: number;
  driftWindowBaseline: number;
  cooldownHours: number;
}

// REMPLACEMENT DES CONSTANTES MAGIQUES : Valeurs par défaut dynamiques, calculées à l'exécution
const getDynamicConfig = (historyLength: number): LearningConfig => {
  return {
    minHistorySize: Math.max(5, Math.min(historyLength, Math.floor(historyLength * 0.1) || 25)),
    minImprovementDelta: 1.5, // Seuil minimal de gain significatif
    maxWeightChangePercent: Math.max(10, Math.floor(historyLength * 0.05)), // Plus l'historique est long, plus on autorise de changement
    validationSampleSize: Math.max(2, Math.min(historyLength - 2, Math.floor(historyLength * 0.15) || 20)),
    driftWindowRecent: Math.max(2, Math.min(historyLength, Math.floor(historyLength * 0.05) || 5)),
    driftWindowBaseline: Math.max(3, Math.min(historyLength, Math.floor(historyLength * 0.2) || 15)),
    cooldownHours: 8,
  };
};

export const LearningService = {
  config: { ...getDynamicConfig(100) }, // Fallback initial

  updateConfig(updates: Partial<LearningConfig>) {
    Object.assign(this.config, updates);
  },

  /**
   * Détection avancée de dérive (multi-métriques)
   */
  async checkDrift(
    // @ts-ignore - auto generated by cleanup
    drawName: string,
    predictions: PredictionHistoryItem[],
    results: DrawResult[],
  ) {
    // Mise à jour dynamique de la config basée sur la longueur des données
    this.config = getDynamicConfig(results.length);

    const validPairs = predictions
      .map((p) => {
        const res = results.find((r) => r.id === p.drawResultId);
        if (!res) return null;
        const hits = p.prediction.suggestedNumbers.filter((n) =>
          res.gagnants.includes(n),
        ).length;
        return {
          hits,
          confidence: p.prediction.confidence || 50,
          timestamp: p.timestamp,
        };
      })
      .filter(Boolean) as any[];

    if (validPairs.length < this.config.driftWindowBaseline) {
      return {
        hasDrift: false,
        reason: "Historique insuffisant pour la détection de dérive",
      };
    }

    const recent = validPairs.slice(0, this.config.driftWindowRecent);
    const baseline = validPairs.slice(this.config.driftWindowRecent);

    const recentAvgHits =
      recent.reduce((a, b) => a + b.hits, 0) / (recent.length || 1);
    const baselineAvgHits =
      baseline.reduce((a, b) => a + b.hits, 0) / (baseline.length || 1);
    const recentSuccessRate =
      recent.filter((p) => p.hits >= 1).length / (recent.length || 1);

    // Calcul des variances
    const recentVar =
      recent.reduce(
        (sum, item) => sum + Math.pow(item.hits - recentAvgHits, 2),
        0,
      ) / (recent.length || 1);
    const baselineVar =
      baseline.reduce(
        (sum, item) => sum + Math.pow(item.hits - baselineAvgHits, 2),
        0,
      ) / (baseline.length || 1);

    // Alpha adaptatif basé sur la volatilité relative (F-test style)
    // Si la variance récente est très grande, alpha diminue (on fait moins confiance aux variations brusques)
    const volatilityRatio = (recentVar + 1e-9) / (baselineVar + 1e-9);
    const alpha = Math.max(
      0.1,
      Math.min(0.9, 1.0 / (1.0 + Math.sqrt(volatilityRatio))),
    );

    // EWMA (Exponential Weighted Moving Average)
    let ewma = recent[0].hits;
    for (let i = 1; i < recent.length; i++) {
      ewma = alpha * recent[i].hits + (1 - alpha) * ewma;
    }

    const driftScore =
      (ewma - baselineAvgHits) / (Math.sqrt(baselineVar) + 1e-9);

    // Test de Student (Welch's t-test) pour comparer les moyennes de deux échantillons de variances inégales
    const tStatistic =
      (recentAvgHits - baselineAvgHits) /
      Math.sqrt(
        recentVar / recent.length + baselineVar / baseline.length + 1e-9,
      );

    // Degrés de liberté (approximation de Welch-Satterthwaite)
    const num = Math.pow(
      recentVar / recent.length + baselineVar / baseline.length,
      2,
    );
    const den =
      Math.pow(recentVar / recent.length, 2) / (recent.length - 1 || 1) +
      Math.pow(baselineVar / baseline.length, 2) / (baseline.length - 1 || 1);
    // @ts-ignore - auto generated by cleanup
    const df = num / (den + 1e-9);

    // Approximation continue de la p-value (CDF de Student via fonction de répartition de la loi normale pour grand df,
    // ou t-distribution approximation). Ici on dresse la probabilité que la dérive soit significative
    // Une approximation sigmoïde bien calibrée sur la t-statistique
    const pValue = 1.0 - 1.0 / (1.0 + Math.exp(-1.702 * tStatistic)); // Approximation continue de la CDF normale (sigmoïde normalisée)

    // Facteur additionnel continu pour la chute du taux de succès (success rate)
    const successRateRatio =
      recentSuccessRate /
      (baseline.filter((p) => p.hits >= 1).length / baseline.length || 1e-9);
    // Si le taux de succès s'effondre (ratio < 1), le risque augmente asymétriquement
    const successCollapseRisk = Math.max(0, 1.0 - successRateRatio);

    // Outil de renforcement : Kelly-inspired Risk Capital Allocation pour la dérive
    // P-value est le "Win Probability" (w).
    const w = 1.0 - pValue; 
    const l = pValue; // Loss probability
    const kellyRisk = (successCollapseRisk > 0) ? Math.max(0, w - (l / (successCollapseRisk + 1e-9))) : w;

    // On s'intéresse à la dérive négative (dégradation) : pValue < 0.05
    // Ou on mesure le risque global de dérive :
    let driftRisk = 0;
    if (tStatistic < 0) {
      // La moyenne récente est plus basse que la baseline
      driftRisk = 1.0 - pValue; // P(t < tStatistic)
    }
    
    // Application de la marge de sécurité fractale (Kelly fractionnel dynamique)
    const safetyFraction = 0.5 + 0.5 * Math.min(1.0, baselineVar / 10.0);
    driftRisk = Math.max(driftRisk, kellyRisk * safetyFraction);

    driftRisk = 1 - (1 - driftRisk) * (1 - successCollapseRisk); // Union probabiliste

    // REMPLACEMENT DU SEUIL MAGIQUE 0.85 : Seuil dérivé de la distribution normale (environ 1 sigma = 84%, on utilise une marge de sécurité)
    const dynamicDriftThreshold = 0.80 + (0.10 * Math.min(1.0, baselineVar)); 
    const isPerformanceDrift = driftRisk > dynamicDriftThreshold;

    // Évaluation Page-Hinkley sur les erreurs de prédictions (Brier Loss-like)
    const errorStream = validPairs.map(p => {
      const hitRatio = p.hits / 5.0;
      const confidenceRatio = p.confidence / 100.0;
      return Math.pow(hitRatio - confidenceRatio, 2);
    }).reverse(); // Du plus ancien au plus récent pour Page-Hinkley

    const pageHinkleyResult = driftDetector.detectDriftPageHinkley(errorStream);

    // Évaluation de la dérive structurelle (KL-Divergence)
    const structuralDriftResult = driftDetector.evaluateStructuralDrift(results);

    // Union logique des différents signaux de dérive
    const hasDrift = isPerformanceDrift || pageHinkleyResult.hasDrift || structuralDriftResult.driftDetected;

    let driftReason = "Performance stable";
    if (hasDrift) {
      const activeSignals: string[] = [];
      if (isPerformanceDrift) activeSignals.push(`Baisse Performance (risque: ${(driftRisk * 100).toFixed(1)}%)`);
      if (pageHinkleyResult.hasDrift) activeSignals.push(`Dérive Page-Hinkley (confiance: ${pageHinkleyResult.confidence}%)`);
      if (structuralDriftResult.driftDetected) activeSignals.push(`Dérive Structurelle KL (sévérité: ${structuralDriftResult.severity})`);
      driftReason = `Dérive détectée : ${activeSignals.join(", ")}`;
    }

    return {
      hasDrift,
      metrics: {
        recentAvgHits,
        baselineAvgHits,
        ewma,
        driftScore,
        recentSuccessRate,
        pageHinkleyConfidence: pageHinkleyResult.confidence,
        structuralDivergence: structuralDriftResult.divergence,
        structuralSeverity: structuralDriftResult.severity
      },
      reason: driftReason,
    };
  },

  /**
   * Auto-apprentissage complet avec versioning et validation
   */
  async triggerAutoLearning(
    drawName: string,
    customWeights?: any,
    // @ts-ignore - auto generated by cleanup
    bypassHitl: boolean = false,
    force: boolean = false,
  ): Promise<LearningStatus> {
    const startTime = Date.now();
    const now = new Date().toISOString();

    try {
      const { data: history } = await fetchResults(drawName);
      
      this.config = getDynamicConfig(history.length);
      if (!history || history.length < this.config.minHistorySize) {
        return {
          lastRun: now,
          improvement: false,
          message: `Historique insuffisant pour l'apprentissage (min ${this.config.minHistorySize} requis).`,
        };
      }

      const currentWeights = await getAlgoWeights(drawName);

      // Cloud Auto-Learning Delegation
      const useCloudEngine = useNexusStore.getState().useCloudEngine;
      if (useCloudEngine && isSupabaseConfigured() && !customWeights) {
        try {
          console.log(`[CLOUD AUTO-LEARNING] Délégation de l'apprentissage ${drawName} vers Supabase Edge Function (self-learn)...`);
          const response = await apiClient.post<{ success: boolean; improved: boolean; weights: any; delta: string; message?: string }>('self-learn', {
            drawName
          });
          if (response && response.success) {
            if (response.improved && response.weights) {
              const { updateGlobalWeights } = useNexusStore.getState();
              await updateGlobalWeights(response.weights, drawName);
              return {
                lastRun: now,
                improvement: true,
                message: `ADN auto-régulé avec succès via Cloud Edge (+${response.delta}%).`,
                delta: response.delta,
                weights: response.weights,
                criticalDecision: `L'algorithme génétique exécuté dans le Cloud (Supabase Edge Compute) a optimisé l'équilibre des poids ADN avec un gain estimé de +${response.delta}%.`
              };
            } else {
              return {
                lastRun: now,
                improvement: false,
                message: `L'ADN actuel est optimal (analysé par Cloud Edge).`,
                delta: "0",
                weights: currentWeights,
                criticalDecision: `L'algorithme génétique Cloud Edge a analysé l'historique et conclu que les poids ADN actuels sont déjà à l'équilibre optimal.`
              };
            }
          }
        } catch (err) {
          console.warn("[CLOUD AUTO-LEARNING] Échec de l'apprentissage Cloud, basculement sur l'apprentissage local.", err);
        }
      }

      const forensicReports = await getLocalForensicReports();
      const drawReports = forensicReports.filter(
        (r: any) => r.drawName === drawName,
      );

      // Sauvegarde de la version actuelle (avant modification)
      await WeightVersionManager.saveVersion(
        drawName,
        currentWeights as any,
        0,
        0,
        {
          source: "before-auto-learning",
          forensicReportsCount: drawReports.length,
        },
      );

      // === Phase 1 : Auto-Équilibrage IA Indexation Empirique ===
      // CORRECTION CRITIQUE : on applique l'optimisation Meta-Learning sur les poids fournis ou actuels,
      // au lieu d'utiliser directement customWeights brut (qui annulait l'effet de l'apprentissage !)
      const weightsBase = customWeights || currentWeights;
      const newWeightsRaw = await applyMetaLearning(weightsBase as any, history, drawName);
      const candidateWeights = normalizeWeights(newWeightsRaw as any);

      // Calcul des deltas de poids pour le feedback visuel
      const weightChanges: Record<string, number> = {};
      Object.keys(candidateWeights).forEach((key) => {
        const oldVal = (weightsBase as any)[key] || 0;
        const newVal = (candidateWeights as any)[key] || 0;
        weightChanges[key] = newVal - oldVal;
      });

      // === Phase 2 : Validation Champion vs Challenger ===
      const [oldReport, newReport] = await Promise.all([
        runBacktestTraining(
          drawName,
          history,
          this.config.validationSampleSize,
          undefined,
          weightsBase as any,
        ),
        runBacktestTraining(
          drawName,
          history,
          this.config.validationSampleSize,
          undefined,
          candidateWeights as any,
        ),
      ]);

      const improvement = newReport.score - oldReport.score;
      const relativeGain =
        oldReport.score > 0 ? (improvement / oldReport.score) * 100 : 0;

      const totalWeightChange = Object.keys(candidateWeights).reduce(
        (sum, key) => {
          return (
            sum +
            Math.abs(
              (candidateWeights[key as keyof AlgoWeights] || 0) -
                ((weightsBase as any)[key] || 0),
            )
          );
        },
        0,
      );

      // === Phase 3 : Garde-fous et décision ===
      // Si force est activée (clic manuel), on accepte toute amélioration strictement positive (> 0%)
      const isRejected = force
        ? (relativeGain <= 0)
        : (relativeGain < this.config.minImprovementDelta ||
          totalWeightChange > this.config.maxWeightChangePercent);

      // Description explicite des ajustements continus
      const mostUpvotedAlgo = Object.entries(weightChanges).sort((a, b) => b[1] - a[1])[0];
      const mostDownvotedAlgo = Object.entries(weightChanges).sort((a, b) => a[1] - b[1])[0];
      const criticalDecision = relativeGain > 0 
        ? `Le filtre de Kalman récursif a calibré l'ADN en renforçant l'algorithme "${mostUpvotedAlgo[0]}" (+${(mostUpvotedAlgo[1] * 100).toFixed(1)}%) et en atténuant "${mostDownvotedAlgo[0]}" (${(mostDownvotedAlgo[1] * 100).toFixed(1)}%) pour s'adapter aux dynamiques de l'historique.`
        : `L'ADN actuel est déjà à l'équilibre optimal vis-à-vis des anomalies Forensic détectées. Aucun ajustement requis.`;

      if (isRejected) {
        return {
          lastRun: now,
          improvement: false,
          message: relativeGain <= 0
            ? `L'ADN actuel est optimal (Gain : ${relativeGain.toFixed(2)}%).`
            : `Ajustement rejeté par les garde-fous de robustesse (Gain : ${relativeGain.toFixed(2)}% | Variation : ${totalWeightChange.toFixed(2)}%).`,
          delta: relativeGain.toFixed(2),
          weights: weightsBase,
          oldScore: oldReport.score,
          newScore: newReport.score,
          weightChanges,
          criticalDecision,
        };
      }

      // === Phase 4 : Application et versioning ===
      await saveAlgoWeights(drawName, candidateWeights as any);

      await WeightVersionManager.saveVersion(
        drawName,
        candidateWeights as any,
        newReport.score,
        relativeGain,
        {
          source: "auto-learning",
          forensicReportsCount: drawReports.length,
          backtestSampleSize: this.config.validationSampleSize,
        },
      );

      logger.info(
        {
          relativeGain: relativeGain.toFixed(2),
          weightChange: totalWeightChange.toFixed(2),
          newScore: newReport.score,
          durationMs: Date.now() - startTime,
        },
        `[LearningService] Auto-learning réussi pour ${drawName}`,
      );

      return {
        lastRun: now,
        improvement: true,
        message: `ADN auto-régulé avec succès (+${relativeGain.toFixed(1)}% de performance de validation).`,
        delta: relativeGain.toFixed(2),
        weights: candidateWeights,
        oldScore: oldReport.score,
        newScore: newReport.score,
        weightChanges,
        criticalDecision,
      };
    } catch (error: unknown) {
      logger.error(
        error instanceof Error ? error : new Error(String(error)),
        "[LearningService] Échec",
      );
      return {
        lastRun: now,
        improvement: false,
        message: `Erreur critique : ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  },

  async getWeightHistory(drawName: string) {
    if (typeof window === "undefined" || !window.localStorage) return [];
    try {
      const history = localStorage.getItem(`nexus_weights_history_${drawName}`);
      return history ? JSON.parse(history) : [];
    } catch (e) {
      return [];
    }
  },

  async rollbackWeights(
    drawName: string,
    versionId: string,
  ): Promise<any | null> {
    try {
      const versions = await this.getWeightHistory(drawName);
      const target = versions.find((v: any) => v.id === versionId);
      if (target) {
        await saveAlgoWeights(drawName, target.weights);
        logger.info(
          { versionId, drawName },
          `[Rollback] Reverted weights to version`,
        );
        return target.weights;
      }
    } catch (e) {
      logger.error(
        e instanceof Error ? e : new Error(String(e)),
        "[Rollback] Error reverting weights",
      );
    }
    return null;
  },
};
