
import { DrawResult, ProjectionItem, TopFollowerAnalysis } from '../types';
import { DRAW_SCHEDULE } from '../constants';
import { db, isFirebaseConfigured } from './firebaseClient';
import { collection, query, where, getDocs, limit, doc, addDoc, setDoc, updateDoc, deleteDoc, writeBatch } from 'firebase/firestore';
import { getProjectionsAsync, getFollowersAnalysisAsync } from './mathService';
import { AppError, logError, getErrorMessage } from '../utils/AppError';
import { globalCache, CACHE_TTL } from './cache/CacheService';

/**
 * Constantes fondamentales du système de loterie 5/90.
 * Regroupe et documente toutes les valeurs théoriques et opérationnelles officielles pour éradiquer les nombres magiques.
 */
export const LOTTERY_CONSTANTS = {
  /** Nombre total de boules dans l'urne pour les tirages 5/90 (Source officielle: Loto Civil/National) */
  TOTAL_NUMBERS: 90,
  
  /** Nombre de numéros tirés par tirage (gagnants / machine) (Source officielle: Loto Civil 5/90) */
  NUMBERS_PER_DRAW: 5,
  
  /** Taille par défaut de l'historique de secours déterministe pour assurer une convergence statistique */
  FALLBACK_HISTORY_DEPTH: 250,
  
  /** Graine première de grand ordre pour l'initialisation du générateur congruentiel linéaire (LCG) déterministe */
  SEED_PRIME: 99991,
  
  /** Nombre de jours par défaut pour l'agrégation statistique récente (fenêtre d'observation standard) */
  DEFAULT_STATS_DAYS: 7,
  
  /** Limite de lecture maximale des tirages de l'historique pour préserver l'occupation mémoire en client */
  MAX_HISTORY_LIMIT: 2000,
  
  /** Identifiant global représentant l'agrégation de tous les tirages */
  ALL_DRAWS_IDENTIFIER: 'ALL',
};

// @ts-ignore - auto generated by cleanup
const CACHE_PREFIX = 'nexus_cache_history_';

const isValidDate = (d: number, m: number, y: number): boolean => {
  const date = new Date(y, m - 1, d);
  return date.getFullYear() === y && date.getMonth() === m - 1 && date.getDate() === d;
};

export const formatDate = (dateStr: string, isIsoOutput: boolean = false): string => {
  if (!dateStr) return '';
  if (dateStr.match(/^\d{4}-\d{2}-\d{2}$/)) {
      const [y, m, d] = dateStr.split('-').map(Number);
      if (!isValidDate(d, m, y)) return 'Invalid Date';
      if (isIsoOutput) return dateStr;
      return `${String(d).padStart(2, '0')}/${String(m).padStart(2, '0')}/${y}`;
  }
  if (dateStr.includes('/')) {
    const parts = dateStr.split('/');
    if (parts.length === 3) {
        const [d, m, y] = parts.map(Number);
        if (!isValidDate(d, m, y)) return 'Invalid Date';
        if (isIsoOutput) return `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
        return dateStr;
    }
  }
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) return dateStr;
  const d = date.getDate().toString().padStart(2, '0');
  const m = (date.getMonth() + 1).toString().padStart(2, '0');
  const y = date.getFullYear();
  if (isIsoOutput) return `${y}-${m}-${d}`;
  return `${d}/${m}/${y}`;
};

export const normalizeDate = (dateStr: string): string => {
  if (!dateStr) return new Date().toISOString().split('T')[0];
  if (dateStr.includes('/')) {
    const [d, m, y] = dateStr.split('/');
    return `${y}-${m}-${d}`;
  }
  return dateStr;
};

const normalizeDrawName = (name: string): string => {
    return name.trim().charAt(0).toUpperCase() + name.trim().slice(1).toLowerCase().replace(/(\s[a-z])/g, (c) => c.toUpperCase());
};

export const lotteryService = {
    // @ts-ignore - auto generated by cleanup
  async fetchHistory(drawName: string, force?: boolean): Promise<DrawResult[]> {
    const cacheKey = globalCache.generateKey('history', drawName);

    // Stale-While-Revalidate : Si un cache valide existe et force=false, retour instantané
    if (!force) {
      const cached = await globalCache.get<DrawResult[]>(cacheKey, drawName);
      if (cached && cached.length > 0) {
        // Rafraîchissement asynchrone discret en arrière-plan
        if (isFirebaseConfigured() && navigator.onLine) {
          (async () => {
            try {
              let q;
              if (drawName && drawName !== LOTTERY_CONSTANTS.ALL_DRAWS_IDENTIFIER) {
                q = query(
                  collection(db, 'draw_results'),
                  where('draw_name', '==', normalizeDrawName(drawName)),
                  limit(LOTTERY_CONSTANTS.MAX_HISTORY_LIMIT)
                );
              } else {
                q = query(
                  collection(db, 'draw_results'),
                  limit(LOTTERY_CONSTANTS.MAX_HISTORY_LIMIT)
                );
              }
              const snap = await getDocs(q);
              const data = snap.docs.map(doc => ({ id: doc.id, ...doc.data() })) as any[];
              data.sort((a, b) => getDrawTimestamp(b.date) - getDrawTimestamp(a.date));
              if (data && data.length > 0) {
                const fresh = data.map(row => ({
                  id: row.id,
                  drawName: row.draw_name,
                  date: formatDate(row.date),
                  gagnants: row.gagnants || [],
                  machine: row.machine || [],
                  version: row.version || 1
                }));
                await globalCache.set(cacheKey, fresh, CACHE_TTL.HISTORY, drawName);
              }
            } catch (e) {
              // Silently ignore background revalidation failures
            }
          })();
        }
        return cached;
      }
    }

    let remoteData: DrawResult[] | null = null;
    let fetchError: unknown = null;

    if (isFirebaseConfigured() && navigator.onLine) {
        try {
            let q;
            if (drawName && drawName !== LOTTERY_CONSTANTS.ALL_DRAWS_IDENTIFIER) {
                q = query(
                    collection(db, 'draw_results'),
                    where('draw_name', '==', normalizeDrawName(drawName)),
                    limit(LOTTERY_CONSTANTS.MAX_HISTORY_LIMIT)
                );
            } else {
                q = query(
                    collection(db, 'draw_results'),
                    limit(LOTTERY_CONSTANTS.MAX_HISTORY_LIMIT)
                );
            }
            
            const snap = await getDocs(q);
            const data = snap.docs.map(doc => ({ id: doc.id, ...doc.data() })) as any[];
            data.sort((a, b) => getDrawTimestamp(b.date) - getDrawTimestamp(a.date));
            
            if (data && data.length > 0) {
                remoteData = data.map(row => ({
                  id: row.id,
                  drawName: row.draw_name,
                  date: formatDate(row.date),
                  gagnants: row.gagnants || [],
                  machine: row.machine || [],
                  version: row.version || 1
                }));

                // Update indexedDB cache with the fresh data
                await globalCache.registerNewDraw(drawName, remoteData.length);
                await globalCache.set(cacheKey, remoteData, CACHE_TTL.HISTORY, drawName);
                return remoteData;
            }
        } catch (e) {
            logError(e, { source: 'lotteryService.fetchHistory' });
            fetchError = e;
        }
    }

    // Fallback to cache if network fails or offline
    const cached = await globalCache.get<DrawResult[]>(cacheKey, drawName);
    if (cached) return cached;

    // Aucun échappement imaginaire ou inventé : retour d'un jeu vide comme demandé par l'utilisateur
    console.warn(`[LotteryService] Aucun cache ni donnée Firebase réelle disponible pour '${drawName}'.`);
    return [];
  }
};

const getDrawTimestamp = (dateStr: string): number => {
    if (!dateStr) return 0;
    if (dateStr.includes('/')) {
        const parts = dateStr.split('/');
        if (parts.length === 3) {
            return new Date(parseInt(parts[2]), parseInt(parts[1]) - 1, parseInt(parts[0])).getTime();
        }
    }
    const d = new Date(dateStr);
    return isNaN(d.getTime()) ? 0 : d.getTime();
};

export const syncDrawExternal = async (drawName?: string): Promise<number> => {
  if (!isFirebaseConfigured()) {
    // CORRECTIF CRITIQUE (contamination de données) : ce bloc générait auparavant de FAUX
    // tirages via un LCG déterministe, les persistait dans le cache comme s'ils venaient d'être
    // synchronisés depuis une vraie source officielle, déclenchait une analyse forensique
    // automatique dessus, PUIS un auto-apprentissage qui ajustait les poids RÉELS de
    // l'algorithme de prédiction — le tout de façon silencieuse et automatique (via le minuteur
    // d'auto-sync de GlobalDashboard.tsx), sans qu'aucun utilisateur n'ait rien demandé.
    //
    // Une "synchronisation" est par nature un aller chercher de vraies données externes. Sans
    // backend configuré, il n'y a rien de réel à synchroniser : on le dit clairement plutôt que
    // d'inventer des résultats. Les données de secours imaginaires ont été supprimées du système.
    const err = new AppError(
      "Synchronisation indisponible : aucun backend n'est configuré (mode démo hors-ligne). " +
      "Aucune donnée n'est inventée ; configurez Firebase pour synchroniser de vrais résultats.",
      'SYNC_REQUIRES_BACKEND',
      'low',
      { drawName }
    );
    logError(err, { source: 'syncDrawExternal-offline' });
    throw err;
  }

  return 0;
};

export const checkAndSyncRecentResults = async (drawName?: string): Promise<number> => {
    return syncDrawExternal(drawName);
};

export const computeAnalytics = async (drawName: string): Promise<boolean> => {
  return false;
};

export const fetchResults = async (drawName: string, force?: boolean): Promise<{ data: DrawResult[] }> => {
  const data = await lotteryService.fetchHistory(drawName, force);
  return { data };
};

export const getDailySummary = async (day: string) => {
  const cacheKey = globalCache.generateKey('daily_summary', day);
  const cached = await globalCache.get<any>(cacheKey);
  if (cached) return cached;

  const draws = DRAW_SCHEDULE[day] || {};
  const sortedTimes = Object.keys(draws).sort(); 
  const names = sortedTimes.map(time => draws[time]);
  
  let result;
  try {
      if (isFirebaseConfigured() && navigator.onLine) {
          const q = query(
            collection(db, 'draw_results'),
            where('draw_name', 'in', names.length > 0 ? names : ['__none__'])
          );
          const snap = await getDocs(q);
          const data = snap.docs.map(d => ({ id: d.id, ...d.data() })) as any[];
          data.sort((a, b) => getDrawTimestamp(b.date) - getDrawTimestamp(a.date));

          result = sortedTimes.map((time) => {
              const name = draws[time];
              const match = data?.find(row => row.draw_name === name);
              let lastDraw: DrawResult | null = null;
              if (match) {
                  lastDraw = {
                      id: match.id,
                      drawName: match.draw_name,
                      date: formatDate(match.date),
                      gagnants: match.gagnants || [],
                      machine: match.machine || [],
                      version: match.version || 1
                  };
              }
              return { time, name, result: lastDraw };
          });
      } else {
          const promises = sortedTimes.map(async (time) => {
              const name = draws[time];
              let lastDraw: DrawResult | null = null;
              try {
                  const history = await lotteryService.fetchHistory(name);
                  if (history.length > 0) lastDraw = history[0];
              } catch (e) {
                  // ignore
              }
              return { time, name, result: lastDraw };
          });
          result = await Promise.all(promises);
      }
  } catch (e) {
      const promises = sortedTimes.map(async (time) => {
          const name = draws[time];
          let lastDraw: DrawResult | null = null;
          try {
              const history = await lotteryService.fetchHistory(name);
              if (history.length > 0) lastDraw = history[0];
          } catch (err) {
              // ignore
          }
          return { time, name, result: lastDraw };
      });
      result = await Promise.all(promises);
  }

  await globalCache.set(cacheKey, result, 120 * 1000);
  return result;
};

export const getNextScheduledDraw = () => {
  const days = ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'];
  const now = new Date();
  const todayName = days[now.getDay()];
  const schedule = DRAW_SCHEDULE[todayName];
  if (!schedule) return null;
  const times = Object.keys(schedule).sort((a, b) => {
      const [h1, m1] = a.split(':').map(Number);
      const [h2, m2] = b.split(':').map(Number);
      return (h1 * 60 + m1) - (h2 * 60 + m2);
  });
  const currentTimestamp = now.getTime();
  const nextTime = times.find(t => {
      const [h, m] = t.split(':').map(Number);
      const drawDate = new Date(now);
      drawDate.setHours(h, m, 0, 0);
      return drawDate.getTime() > currentTimestamp;
  });
  if (nextTime) {
      return { time: nextTime, name: schedule[nextTime], day: todayName };
  } else {
      const tomorrowIndex = (now.getDay() + 1) % 7;
      const tomorrowName = days[tomorrowIndex];
      const tomorrowSchedule = DRAW_SCHEDULE[tomorrowName];
      const tomorrowTimes = Object.keys(tomorrowSchedule).sort();
      const firstDraw = tomorrowTimes[0];
      return { time: firstDraw, name: tomorrowSchedule[firstDraw], day: tomorrowName };
  }
};

export const fetchRecentStats = async (days: number = 7, drawName?: string) => {
  const cacheKey = globalCache.generateKey('recent_stats', `${days}d`, drawName || 'global');
  
  const cached = await globalCache.get<any>(cacheKey, drawName);
  if (cached) return cached;

  if (!isFirebaseConfigured() || !navigator.onLine) {
      const stats = await computeRecentStatsFromHistory(days, drawName);
      await globalCache.set(cacheKey, stats, CACHE_TTL.MEDIUM, drawName);
      return stats;
  }
  
  try {
    let q;
    if (drawName && drawName !== 'ALL') {
        q = query(
            collection(db, 'draw_results'),
            where('draw_name', '==', normalizeDrawName(drawName))
        );
    } else {
        q = query(collection(db, 'draw_results'));
    }

    const snap = await getDocs(q);
    const data = snap.docs.map(doc => doc.data()) as any[];
    
    const counts: Record<number, number> = {};
    (data || []).forEach(row => (row.gagnants || []).forEach((n: number) => counts[n] = (counts[n] || 0) + 1));
    
    if (Object.keys(counts).length === 0) {
         return fetchGlobalStats(drawName);
    }

    const stats = Object.entries(counts)
      .map(([n, c]) => ({ number: Number(n), count: c }))
      .sort((a, b) => b.count - a.count);
    
    await globalCache.set(cacheKey, stats, CACHE_TTL.MEDIUM, drawName);
    return stats;
  } catch (e) {
    const stats = await computeRecentStatsFromHistory(days, drawName);
    await globalCache.set(cacheKey, stats, CACHE_TTL.MEDIUM, drawName);
    return stats;
  }
};

export const fetchGlobalStats = async (drawName?: string) => {
  const cacheKey = globalCache.generateKey('global_stats', drawName || 'global');
  
  const cached = await globalCache.get<any>(cacheKey, drawName);
  if (cached) return cached;

  if (!isFirebaseConfigured() || !navigator.onLine) {
      const stats = await computeGlobalStatsFromHistory(drawName);
      await globalCache.set(cacheKey, stats, CACHE_TTL.MEDIUM, drawName);
      return stats;
  }
  
  try {
    let q;
    if (drawName && drawName !== 'ALL') {
        q = query(collection(db, 'draw_results'), where('draw_name', '==', normalizeDrawName(drawName)), limit(2000));
    } else {
        q = query(collection(db, 'draw_results'), limit(2000));
    }

    const snap = await getDocs(q);
    const data = snap.docs.map(doc => doc.data()) as any[];
    const counts: Record<number, number> = {};
    (data || []).forEach(row => (row.gagnants || []).forEach((n: number) => counts[n] = (counts[n] || 0) + 1));
    const stats = Object.entries(counts).map(([n, c]) => ({ number: Number(n), count: c })).sort((a, b) => b.count - a.count);
    
    await globalCache.set(cacheKey, stats, CACHE_TTL.MEDIUM, drawName);
    return stats;
  } catch (e) {
    const stats = await computeGlobalStatsFromHistory(drawName);
    await globalCache.set(cacheKey, stats, CACHE_TTL.MEDIUM, drawName);
    return stats;
  }
};

const computeRecentStatsFromHistory = async (days: number, drawName?: string): Promise<{ number: number, count: number }[]> => {
  try {
    const history = await lotteryService.fetchHistory(drawName || 'ALL');
    const counts: Record<number, number> = {};
    const dateLimit = new Date();
    dateLimit.setDate(dateLimit.getDate() - days);
    
    const filteredHistory = history.filter(h => {
      const hTime = getDrawTimestamp(h.date);
      return hTime >= dateLimit.getTime();
    });
    const sample = filteredHistory.length > 0 ? filteredHistory : history.slice(0, 30);
    sample.forEach(row => row.gagnants.forEach((n: number) => counts[n] = (counts[n] || 0) + 1));
    return Object.entries(counts).map(([n, c]) => ({ number: Number(n), count: c })).sort((a, b) => b.count - a.count);
  } catch (_) {
    return [];
  }
};

const computeGlobalStatsFromHistory = async (drawName?: string): Promise<{ number: number, count: number }[]> => {
  try {
    const history = await lotteryService.fetchHistory(drawName || 'ALL');
    const counts: Record<number, number> = {};
    history.forEach(row => row.gagnants.forEach((n: number) => counts[n] = (counts[n] || 0) + 1));
    return Object.entries(counts).map(([n, c]) => ({ number: Number(n), count: c })).sort((a, b) => b.count - a.count);
  } catch (_) {
    return [];
  }
};

export const triggerAutomationForNewResults = async (drawName: string, date: string, resultId?: string, forceLocal: boolean = false) => {
  if (isFirebaseConfigured() && !forceLocal) {
    try {
      const qSnap = query(
        collection(db, 'prediction_snapshots'),
        where('draw_name', '==', normalizeDrawName(drawName)),
        where('status', '==', 'PENDING')
      );
      const snapDocs = await getDocs(qSnap);

      if (!snapDocs.empty) {
        let autopsyCount = 0;
        for (const snapDoc of snapDocs.docs) {
          let targetResultId = resultId;
          if (!targetResultId) {
              const qRes = query(
                  collection(db, 'draw_results'),
                  where('draw_name', '==', normalizeDrawName(drawName)),
                  where('date', '==', normalizeDate(date)),
                  limit(1)
              );
              const resSnap = await getDocs(qRes);
              if (!resSnap.empty) targetResultId = resSnap.docs[0].id;
          }

          if (targetResultId) {
              console.log("Trigger forensic autopsy locally for snapshot:", snapDoc.id, "and result:", targetResultId);
              autopsyCount++;
          }
        }
      }
      return;
    } catch (e) {
      console.error("Cloud automation failed, falling back to local:", e);
    }
  }

  // LOGIQUE DE RETRAITE LOCALE
  try {
    const { getPredictionHistoryAsync, linkPredictionToResult } = await import('./predictionHistoryService');
    const { performForensicAnalysis, saveForensicReport } = await import('./postPredictionAnalysisService');

    const history = await lotteryService.fetchHistory(drawName);
    const resultToMatch = history.find((r) => r.date === normalizeDate(date) || r.id === resultId);
    
    if (!resultToMatch) return;

    const unlinkedPredictions = (await getPredictionHistoryAsync(drawName)).filter(
      p => !p.drawResultId || p.drawResultId === resultToMatch.id
    );

    let autopsiesRun = 0;
    
    for (const pred of unlinkedPredictions) {
      const pDate = new Date(pred.timestamp).toLocaleDateString("fr-FR", { year: 'numeric', month: '2-digit', day: '2-digit' });
      if (pDate === date || pred.drawResultId === resultToMatch.id) {
          console.log(`[Autopsy Locale] Execution forensics pour prédiction ${pred.id}`);
          const report = await performForensicAnalysis(
            drawName,
            date,
            pred.prediction.suggestedNumbers,
            resultToMatch.gagnants,
            pred.prediction.breakdown
          );
          await saveForensicReport(report);
          await linkPredictionToResult(pred.id, resultToMatch.id);
          autopsiesRun++;
      }
    }

    if (autopsiesRun > 0) {
       console.log(`[Autopsie] ${autopsiesRun} autopsie(s) effectuée(s).`);
    } else {
       console.log(`[Autopsie] Enregistrement d'un nouveau tirage sans autopsie.`);
    }
  } catch (e) {
    console.error("Local automation trigger failed:", e);
  }
};

export const bulkAddResults = async (drawName: string, results: { date: string, draw_num?: string, numbers?: string[], gagnants: number[], machine?: number[], draw_name?: string }[]) => {
  await globalCache.invalidateByPrefix('nexus_daily_summary_');
  if (!isFirebaseConfigured()) throw new Error("Mode hors-ligne : Écriture impossible.");
  
  const savedData: any[] = [];
  const batch = writeBatch(db);
  
  for (const r of results) {
    const normalizedName = r.draw_name || normalizeDrawName(drawName);
    const normalizedD = normalizeDate(r.date);
    const docId = `${normalizedName}_${normalizedD}`.replace(/[\/\s]/g, '_');
    const docRef = doc(db, 'draw_results', docId);
    const payload = {
      draw_name: normalizedName,
      date: normalizedD,
      gagnants: r.gagnants,
      machine: r.machine || [],
      version: 1
    };
    batch.set(docRef, payload, { merge: true });
    savedData.push({ id: docId, ...payload });
  }
  
  await batch.commit();

  if (savedData.length > 0) {
      for (const res of savedData) {
          await triggerAutomationForNewResults(res.draw_name, res.date, res.id);
      }
      if (typeof window !== 'undefined') {
          window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName } }));
      }
  }
};

export const addResult = async (drawName: string, result: Omit<DrawResult, 'id'>) => {
  await globalCache.invalidateByPrefix('nexus_daily_summary_');
  if (!isFirebaseConfigured()) throw new Error("Mode hors-ligne : Écriture impossible.");
  const normalizedName = normalizeDrawName(drawName);
  const normalizedD = normalizeDate(result.date);
  const docId = `${normalizedName}_${normalizedD}`.replace(/[\/\s]/g, '_');
  const docRef = doc(db, 'draw_results', docId);
  const payload = {
    draw_name: normalizedName,
    date: normalizedD,
    gagnants: result.gagnants,
    machine: result.machine || [],
    version: 1
  };
  await setDoc(docRef, payload, { merge: true });
  
  await triggerAutomationForNewResults(normalizedName, normalizedD, docId);
  if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName: normalizedName } }));
  }
};

export const updateResult = async (drawName: string, result: DrawResult) => {
  await globalCache.invalidateByPrefix('nexus_daily_summary_');
  if (!isFirebaseConfigured()) throw new Error("Mode hors-ligne : Écriture impossible.");
  const docRef = doc(db, 'draw_results', result.id);
  const payload = {
    date: normalizeDate(result.date),
    gagnants: result.gagnants,
    machine: result.machine || [],
    version: result.version || 1
  };
  await updateDoc(docRef, payload);
  
  await triggerAutomationForNewResults(normalizeDrawName(drawName), payload.date, result.id);
  if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName: normalizeDrawName(drawName) } }));
  }
};

export const deleteResult = async (drawName: string, id: string) => {
  await globalCache.invalidateByPrefix('nexus_daily_summary_');
  if (!isFirebaseConfigured()) throw new Error("Mode hors-ligne : Suppression impossible.");
  await deleteDoc(doc(db, 'draw_results', id));

  if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName } }));
  }
};

export const bulkDeleteResults = async (drawName: string, ids: string[]) => {
  await globalCache.invalidateByPrefix('nexus_daily_summary_');
  if (!isFirebaseConfigured()) {
    const cacheKey = globalCache.generateKey('history', drawName);
    const history = await globalCache.get<DrawResult[]>(cacheKey, drawName);
    if (history) {
      const updatedHistory = history.filter(item => !ids.includes(item.id));
      await globalCache.set(cacheKey, updatedHistory, CACHE_TTL.HISTORY, drawName);
      await globalCache.registerNewDraw(drawName, updatedHistory.length);
      if (typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName } }));
      }
    }
    return;
  }
  const batch = writeBatch(db);
  for (const id of ids) {
    batch.delete(doc(db, 'draw_results', id));
  }
  await batch.commit();

  const cacheKey = globalCache.generateKey('history', drawName);
  await globalCache.delete(cacheKey);

  if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName } }));
  }
};

export const purgeAllResults = async (drawName: string) => {
  await globalCache.invalidateByPrefix('nexus_daily_summary_');
  if (!isFirebaseConfigured()) {
    const cacheKey = globalCache.generateKey('history', drawName);
    await globalCache.delete(cacheKey);
    await globalCache.registerNewDraw(drawName, 0);
    if (typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName } }));
    }
    return;
  }
  const q = query(
    collection(db, 'draw_results'),
    where('draw_name', '==', normalizeDrawName(drawName))
  );
  const snap = await getDocs(q);
  const batch = writeBatch(db);
  snap.docs.forEach(d => batch.delete(d.ref));
  await batch.commit();

  const cacheKey = globalCache.generateKey('history', drawName);
  await globalCache.delete(cacheKey);
  await globalCache.registerNewDraw(drawName, 0);

  if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('DRAW_RESULTS_UPDATED', { detail: { drawName } }));
  }
};

    // @ts-ignore - auto generated by cleanup
export const fetchNextDrawProjections = async (drawName: string, lastNumbers: number[], history: DrawResult[]): Promise<ProjectionItem[]> => {
    return await getProjectionsAsync(history, lastNumbers);
};

    // @ts-ignore - auto generated by cleanup
export const fetchTopFollowersAnalysis = async (drawName: string, history: DrawResult[]): Promise<TopFollowerAnalysis[]> => {
    return await getFollowersAnalysisAsync(history);
};

    // @ts-ignore - auto generated by cleanup
export const fetchAssociatedNumbers = async (number: number, drawName: string, history: DrawResult[]): Promise<{ following: { number: number; count: number }[] }> => {
    const followers: Record<number, number> = {};
    for (let i = 0; i < history.length - 1; i++) {
        const prev = history[i+1].gagnants;
        if (prev.includes(number)) {
            const current = history[i].gagnants;
            current.forEach(n => followers[n] = (followers[n] || 0) + 1);
        }
    }
    const sorted = Object.entries(followers).map(([n, c]) => ({ number: Number(n), count: c })).sort((a, b) => b.count - a.count).slice(0, 10);
    return { following: sorted };
};


