import { fetchResults } from "./lotteryService";
import {
  generateMasterPrediction,
    // @ts-ignore - auto generated by cleanup
  saveAlgoWeights,
  getAlgoWeights,
  getAdaptiveRules,
    // @ts-ignore - auto generated by cleanup
  saveAdaptiveRules,
} from "./predictionEngine";
import { useNexusStore } from "../store/useNexusStore";
import { detectGameRegime } from "./mathService";
import type {
    // @ts-ignore - auto generated by cleanup
  AlgoWeights,
  TrainingReport,
  DrawResult,
} from "../types";
import { logger } from "../utils/logger";
import { AlgoKey } from "../shared/prediction.types";
import { normalizeWeights } from "./prediction/weightsManager";
import { runBacktestTraining as runBacktestTrainingCore } from "./backtestService";
import { globalCache, CACHE_TTL } from "./cache/CacheService";
import { purifyHistoryForDraw } from "../utils/arrayUtils";

// Processus Parallèles : Gestionnaire Global de Workers
const activeWorkersMap = new Map<string, Set<Worker>>();

export const registerActiveWorker = (drawName: string, worker: Worker): void => {
  if (!activeWorkersMap.has(drawName)) {
    activeWorkersMap.set(drawName, new Set());
  }
  activeWorkersMap.get(drawName)!.add(worker);
};

export const unregisterActiveWorker = (drawName: string, worker: Worker): void => {
  const workers = activeWorkersMap.get(drawName);
  if (workers) {
    workers.delete(worker);
    if (workers.size === 0) {
      activeWorkersMap.delete(drawName);
    }
  }
};

export const terminateActiveWorkers = (drawName: string): void => {
  const workers = activeWorkersMap.get(drawName);
  if (workers) {
    logger.info(`[Process Manager] Interruption de ${workers.size} workers d'arrière-plan actifs pour ${drawName}.`);
    for (const worker of workers) {
      try {
        worker.terminate();
      } catch (err) {
        console.error("Échec de la coupure d'un worker", err);
      }
    }
    activeWorkersMap.delete(drawName);
  }
};



export const runBacktestTraining = runBacktestTrainingCore;

export const runAutomatedBacktestSimulation = async (
  drawName: string,
  history: DrawResult[],
  sampleSize: number = 50
): Promise<{  efficiencyScore: number;
  hitDistribution: { zero: number; one: number; two: number; three: number; four: number; five: number };
  averageHits: number;
  report: TrainingReport;
}> => {
  const purifiedHistory = purifyHistoryForDraw(drawName, history);
  // CORRECTION 5: Minimum de sécurité physique de 5 tirages au lieu d'une limite arbitraire bloquante
  if (purifiedHistory.length < 5) {
    throw new Error(`Historique insuffisant pour un backtest automatisé (minimum absolu de 5 tirages).`);
  }
  const actualSampleSize = Math.max(1, Math.min(sampleSize, purifiedHistory.length - 2));
  const report = await runBacktestTraining(drawName, purifiedHistory, actualSampleSize);
  return { efficiencyScore: report.score, hitDistribution: report.winDistribution, averageHits: report.averageHits, report };
};

export const evolveNeuralDNA = async (
  drawName: string,
  options: { generations: number; sampleSize: number; optimizerType?: "genetic" | "pso" | "bayesian" | "meta" } = { generations: 20, sampleSize: 30, optimizerType: "pso" },
  onTelemetry: (data: { gen: number; bestFitness: number; avgFitness: number; diversity: number; bestGenome: any; source?: string }) => void,
): Promise<{ bestWeights: any; improvement: number; report: TrainingReport; isGeneralizable?: boolean; overfittingRatio?: number; firstPredictionDNASnapshot?: any }> => {
  const optType = options.optimizerType || 'pso';
  const { data: rawHistory } = await fetchResults(drawName);
  const fullHistory = purifyHistoryForDraw(drawName, rawHistory);

  // 1. Caching Intelligent (Tirage Isolation Rule)
  const cacheKey = globalCache.generateKey("neural_dna", drawName, `${options.generations}_${options.sampleSize}_${optType}_${fullHistory[0]?.id || ""}`);
  const cachedResult = await globalCache.get<any>(cacheKey, drawName);
  if (cachedResult) {
    logger.info(`[Tensor Processing] ADN Neural récupéré du cache intelligent pour ${drawName}.`);
    if (onTelemetry) {
      // Relecture ultra-rapide et esthétique
      const stepsCount = 5;
      for (let i = 1; i <= stepsCount; i++) {
        await new Promise(resolve => setTimeout(resolve, 80));
        onTelemetry({
          gen: Math.round((options.generations / stepsCount) * i),
          bestFitness: cachedResult.report?.score || 0,
          avgFitness: (cachedResult.report?.score || 0) * 0.9,
          diversity: 0.8 - 0.2 * (i / stepsCount),
          bestGenome: cachedResult.bestWeights,
          source: `${optType}-cached`
        });
      }
    }
    return cachedResult;
  }

  const currentWeights = await getAlgoWeights(drawName);
  // @ts-ignore - auto generated by cleanup
  const currentRules = getAdaptiveRules(drawName);
  
  const oldReport = await runBacktestTraining(drawName, fullHistory, options.sampleSize, undefined, currentWeights);
  let bestWeights = normalizeWeights(currentWeights);

  const regimeMatch = detectGameRegime(fullHistory);
  const hurstExponent = regimeMatch.hurst ? parseFloat(regimeMatch.hurst.toString()) : 0.5;

  logger.info("[Sequential Training] Démarrage de l'apprentissage chronologique rétroactif...");

  const actualSampleSize = Math.min(options.sampleSize, fullHistory.length);
  const trainingSlice = fullHistory.slice(0, actualSampleSize);
  let weightsState = { ...currentWeights };
  let totalHits = 0;
  let firstPredictionDNASnapshot: Record<number, Record<AlgoKey, number>> | null = null;

  const N = trainingSlice.length;
  const { generateMasterPrediction } = await import("./predictionEngine");
  const { DNAOptimizer } = await import("./training/DNAOptimizer");

  for (let idx = N - 1; idx >= 0; idx--) {
    const targetDraw = trainingSlice[idx];
    const targetIndexInFull = fullHistory.indexOf(targetDraw);
    const contextHistory = fullHistory.slice(targetIndexInFull + 1);

    // Si on n'a plus assez d'historique de contexte, on utilise ce qu'il reste
    if (contextHistory.length < 5) {
      continue;
    }

    // Générer une prédiction en partant de l'ADN algorithmique actuel
    const pred = await generateMasterPrediction(
      drawName,
      contextHistory,
      100, // temporalDepth
      weightsState,
      undefined,
      undefined,
      true // skipTraining
    );

    // Surveiller l'ADN de tous les numéros au moment de la première prédiction (la plus ancienne)
    if (idx === N - 1) {
      firstPredictionDNASnapshot = {};
      const algoKeys = Object.keys(weightsState) as AlgoKey[];
      for (let num = 1; num <= 90; num++) {
        const bdown = pred.breakdown[num] || {};
        const numDNA: Record<AlgoKey, number> = {} as any;
        algoKeys.forEach(k => {
          numDNA[k] = Number((bdown as any)[k]) || 0;
        });
        firstPredictionDNASnapshot[num] = numDNA;
      }
      logger.info(`[Training Monitor] ADN de tous les numéros surveillé à la première étape chronologique.`);
    }

    // Comparer la prédiction avec le résultat de l'historique (targetDraw)
    const actualWinners = targetDraw.gagnants;
    const hits = pred.suggestedNumbers.filter(n => actualWinners.includes(n)).length;
    totalHits += hits;

    // Répertorier les calibrages des algorithmes qui ont participé au résultat et les injecter
    const algoKeys = Object.keys(weightsState) as AlgoKey[];
    const optimizer = new DNAOptimizer(algoKeys);

    const dnaMatrix = actualWinners.map((num) => {
      const bdown = pred.breakdown[num] || {};
      const vec = new Float32Array(optimizer["numAlgos"]);
      optimizer["algoKeys"].forEach((k, i) => {
        vec[i] = Number((bdown as any)[k]) || 0;
      });
      return vec;
    });

    let diversitySum = 0;
    let pairs = 0;
    for (let i = 0; i < dnaMatrix.length; i++) {
      for (let j = i + 1; j < dnaMatrix.length; j++) {
        diversitySum += optimizer["cosineDistance"](dnaMatrix[i], dnaMatrix[j]);
        pairs++;
      }
    }
    const diversityScore = pairs > 0 ? diversitySum / pairs : 0;

    const winningXAP = optimizer.generateXAP(
      {
        numbers: actualWinners,
        dnaMatrix,
        synergyVector: new Float32Array(optimizer["numAlgos"]),
        distance: 0,
        diversityScore,
      },
      actualWinners
    );

    const dnaCalibrations = optimizer.calibrateDNAFromWinningComposition(weightsState, winningXAP);

    const updatedWeights = { ...weightsState };
    dnaCalibrations.forEach((adj) => {
      updatedWeights[adj.algo] = Math.max(0.001, (updatedWeights[adj.algo] || 0) + adj.proposedWeightChange);
    });

    weightsState = normalizeWeights(updatedWeights);

    // Notification télémétrie en temps réel
    if (onTelemetry) {
      const currentStep = N - idx;
      const avgHits = totalHits / currentStep;
      const bestFitness = avgHits * 20.0; // scale 0-100 rating (e.g. avg 2.5 hits => 50)
      
      const sumSquaredWeights = Object.values(weightsState).reduce((sum, w) => sum + w * w, 0);
      const diversity = Math.max(0.01, 1.0 - sumSquaredWeights);

      onTelemetry({
        gen: currentStep,
        bestFitness,
        avgFitness: bestFitness * 0.9,
        diversity,
        bestGenome: weightsState,
        source: "chronological-training"
      });
    }
  }

  bestWeights = normalizeWeights(weightsState);

  const newReport = await runBacktestTraining(drawName, fullHistory, options.sampleSize, undefined, bestWeights);

  // Holdout size verification (Tirage Isolation Rule and anti-overfitting)
  const holdoutSize = Math.max(Math.ceil(fullHistory.length * (1 - hurstExponent)), 10);
  let rejectionProbability = 0;
  let finalWeights = bestWeights;
  let overfittingRatio = 1;

  if (holdoutSize > 10) { // Plancher statistique de 10
    const idxSplit = holdoutSize;
    const trainHistory = fullHistory.slice(idxSplit);
    
    const holdoutReport = await runBacktestTraining(drawName, fullHistory, Math.min(options.sampleSize, holdoutSize), undefined, bestWeights);
    const trainReport = await runBacktestTraining(drawName, trainHistory, options.sampleSize, undefined, bestWeights);

    overfittingRatio = trainReport.score / (holdoutReport.score || 1);

    // La tolérance au surapprentissage (marge d'erreur) diminue avec la racine carrée de la taille de l'échantillon
    const expectedVarianceMargin = 1.0 / Math.sqrt(holdoutSize);
    const overfittingThreshold = 1.0 + expectedVarianceMargin;
    
    // Pente dérivée de la taille de l'échantillon pour une transition douce mais ferme
    const slope = Math.sqrt(holdoutSize);
    rejectionProbability = 1 / (1 + Math.exp(-slope * (overfittingRatio - overfittingThreshold)));

    const blendedWeights: any = {};
    Object.keys(currentWeights).forEach(k => {
      const cW = (currentWeights as any)[k] || 0;
      const nW = (bestWeights as any)[k] || 0;
      blendedWeights[k] = cW * rejectionProbability + nW * (1 - rejectionProbability);
    });
    finalWeights = blendedWeights;
  }

  const rawImprovement = newReport.score - oldReport.score;
  const continuousImprovement = parseFloat((rawImprovement * (1 - rejectionProbability)).toFixed(2));

  const safeFinalWeights = normalizeWeights(finalWeights);

  const resultToReturn = {
    bestWeights: safeFinalWeights,
    improvement: continuousImprovement,
    report: newReport,
    isGeneralizable: rejectionProbability < 0.5,
    overfittingRatio: parseFloat(overfittingRatio.toFixed(3)),
    firstPredictionDNASnapshot
  };

  await globalCache.set(cacheKey, resultToReturn, CACHE_TTL.LONG, drawName);
  return resultToReturn;
};

export const applyOnlineLearning = async (
    drawName: string,
    history: DrawResult[],
    userFeedbackScore?: number // RLHF factor (1.0 = positive, -1.0 = negative, 0 = neutral)
): Promise<void> => {
    const purifiedHistory = purifyHistoryForDraw(drawName, history);
    if (!purifiedHistory || purifiedHistory.length < 2) return;

    // The most recent draw is history[0]. 
    // The prediction that was made for this draw would have been based on history.slice(1).
    const targetDraw = purifiedHistory[0];
    const contextHistory = purifiedHistory.slice(1);

    const currentWeights = await getAlgoWeights(drawName);
    const temporalDepth = useNexusStore.getState()?.temporalDepth ?? 100;

    // Regenerate the exact prediction that we would have had
    const prediction = await generateMasterPrediction(
        drawName,
        contextHistory,
        temporalDepth,
        currentWeights,
        undefined,
        undefined,
        true // skip training lock
    );

    const actualWinners = targetDraw.gagnants;
    const predicted = prediction.suggestedNumbers;
    const hits = predicted.filter(n => actualWinners.includes(n)).length;

    // Determine loss/reward (Continuous RLHF Signal)
    // Reward is proportional to hits (max 5) plus the RLHF user feedback (-1 to +1)
    const baseReward = (hits / 5.0);
    const rlhfSignal = userFeedbackScore ? userFeedbackScore * 0.5 : 0;
    const totalSignal = Math.max(-1.0, Math.min(1.0, (baseReward * 2 - 1) + rlhfSignal)); // maps to [-1, 1]

    // Calculate gradients using coordinate descent logic
    const newWeights: Record<string, number> = { ...currentWeights } as any;
    const learningRate = 0.05 * Math.abs(totalSignal); // dynamic continuous LR

    Object.keys(currentWeights).forEach(algoKey => {
        const algo = algoKey as AlgoKey;
        // If the algorithm highly recommended the actual winners, it gets a positive gradient.
        let algoScoreForWinners = 0;
        let algoScoreForLosers = 0;

        Object.keys(prediction.breakdown).forEach(numStr => {
            const num = parseInt(numStr, 10);
            const val = Number(prediction.breakdown[num][algo]) || 0;
            if (actualWinners.includes(num)) algoScoreForWinners += val;
            else algoScoreForLosers += val;
        });

        // Normalize
        algoScoreForWinners /= (actualWinners.length || 1);
        algoScoreForLosers /= (90 - actualWinners.length || 1);

        // Continuous gradient based on discrimination power
        const discriminationPower = algoScoreForWinners - algoScoreForLosers; // higher is better
        
        // Gradient step
        const step = discriminationPower * learningRate * Math.sign(totalSignal);
        newWeights[algo] = Math.max(0.01, Math.min(1.0, (Number((currentWeights as any)[algo]) || 0.1) + step));
    });

    // Normalize weights continuously
    const normalizedWeights = normalizeWeights(newWeights as any);

    // Save and push to store
    await saveAlgoWeights(drawName, normalizedWeights);
    useNexusStore.getState().updateGlobalWeights(normalizedWeights);
    
    // Log training event
    logger.info(`[Online Learning] Draw ${drawName} | Signal: ${totalSignal.toFixed(3)} | Weights updated`);

    // Intégration du pont Forensic-Training : ajustements basés sur le rapport Forensic
    try {
      const { generateLearningSession, applyForensicAdjustments } = await import("./forensicTrainingBridge");
      
      const forensicReport = await new Promise<any>((resolve, reject) => {
          const worker = new Worker(new URL("./workers/forensic.worker.ts?worker", import.meta.url), { type: "module" });
          worker.onmessage = (e) => {
              if (e.data.success) resolve(e.data.result);
              else reject(new Error(e.data.error));
              worker.terminate();
          };
          worker.onerror = (err) => {
              reject(err);
              worker.terminate();
          };
          worker.postMessage({ actualWinners, history: contextHistory });
      });

      const learningSession = await generateLearningSession(forensicReport, contextHistory);
      await applyForensicAdjustments(learningSession);
      logger.info(`[Online Learning] Pont Forensic-Training appliqué avec succès pour le tirage ${drawName}.`);
    } catch (err) {
      logger.warn(`[Online Learning] Échec de l'application du pont Forensic-Training : ${err}`);
    }
};

/**
 * Exécute une étape d'apprentissage complète liant Forensic et Training.
 * 1. Génère un rapport Forensic pour le dernier tirage.
 * 2. Crée une session d'apprentissage adaptative.
 * 3. Applique les ajustements de manière déterministe et continue.
 */
export const runForensicTrainingStep = async (
  drawName: string,
  history: DrawResult[]
): Promise<{ learningSession: any; updatedWeights: AlgoWeights }> => {
  const purifiedHistory = purifyHistoryForDraw(drawName, history);
  if (!purifiedHistory || purifiedHistory.length < 2) {
    throw new Error("Historique insuffisant pour l'évaluation forensic et l'entraînement (minimum de 2 tirages).");
  }

  logger.info(`[Forensic Training Step] Execution lancee pour le tirage: ${drawName}`);

  const { generateLearningSession, applyForensicAdjustments } = await import("./forensicTrainingBridge");

  const targetDraw = purifiedHistory[0];
  const contextHistory = purifiedHistory.slice(1);

  // Génération du rapport forensic
  const forensicReport = await new Promise<any>((resolve, reject) => {
      const worker = new Worker(new URL("./workers/forensic.worker.ts?worker", import.meta.url), { type: "module" });
      worker.onmessage = (e) => {
          if (e.data.success) resolve(e.data.result);
          else reject(new Error(e.data.error));
          worker.terminate();
      };
      worker.onerror = (err) => {
          reject(err);
          worker.terminate();
      };
      worker.postMessage({ actualWinners: targetDraw.gagnants, history: contextHistory });
  });
  
  // Transformation en session d'apprentissage exploitable
  const learningSession = await generateLearningSession(forensicReport, contextHistory);
  
  // Application et mélange continu des ajustements
  const updatedWeights = await applyForensicAdjustments(learningSession);

  return {
    learningSession,
    updatedWeights
  };
};

export interface LoopSimulationStepResult {
  date: string;
  predictedStatic: number[];
  predictedLoop: number[];
  actual: number[];
  hitsStatic: number;
  hitsLoop: number;
  regime: string;
}

export interface LoopSimulationSummary {
  totalHitsStatic: number;
  totalHitsLoop: number;
  improvement: number;
  steps: LoopSimulationStepResult[];
}

/**
 * Extraction mathématique continue et déterministe des profils positionnels d'ADN.
 * Élimine 100% des nombres magiques arbitraires de l'UI en se basant sur des métriques
 * d'auto-corrélation temporelle de phase et de dispersion statistique.
 */
export const calculatePositionalDNAProfiles = (
  history: DrawResult[],
  baseWeights: AlgoWeights
): Record<number, Record<AlgoKey, number>> => {
  if (!history || history.length === 0) return {};

  const profiles: Record<number, Record<AlgoKey, number>> = {};
  const keys = Object.keys(baseWeights) as AlgoKey[];
  const N = 90;

  const sampleSize = Math.min(100, history.length);
  const sample = history.slice(0, sampleSize);

  // Pour chaque position p de 0 à 4 (les 5 boules triées par ordre croissant)
  for (let pos = 0; pos < 5; pos++) {
    const valuesInSlot = sample.map(h => {
      const sorted = [...(h.gagnants || [])].sort((a, b) => a - b);
      return sorted[pos];
    }).filter(v => v !== undefined);

    const avgVal = valuesInSlot.length > 0
      ? valuesInSlot.reduce((a, b) => a + b, 0) / valuesInSlot.length
      : (pos * 18 + 9);

    const varianceVal = valuesInSlot.length > 0
      ? valuesInSlot.reduce((a, b) => a + Math.pow(b - avgVal, 2), 0) / valuesInSlot.length
      : 81; // variance par défaut

    const stdDev = Math.sqrt(varianceVal) || Number.EPSILON;
    const normalizedPos = avgVal / N; // valeur moyenne normalisée entre [0, 1]

    let autoCorr = 0;
    if (valuesInSlot.length > 1) {
      let num = 0;
      let den = 0;
      for (let i = 0; i < valuesInSlot.length - 1; i++) {
        num += (valuesInSlot[i] - avgVal) * (valuesInSlot[i + 1] - avgVal);
        den += Math.pow(valuesInSlot[i] - avgVal, 2);
      }
      autoCorr = den > 0 ? num / den : 0;
    }

    const slotWeights: Record<AlgoKey, number> = {} as any;

    keys.forEach(k => {
      const baseW = baseWeights[k] ?? 0.05;
      let modifier = 1.0;

      switch (k) {
        case AlgoKey.FREQUENCY:
          modifier = 1.0 + Math.tanh((30.0 - stdDev) / 10.0) * (1.0 - normalizedPos);
          break;
        case AlgoKey.GAPS:
          modifier = 1.0 + Math.tanh((stdDev - 30.0) / 10.0) * (1.0 - Math.max(0, autoCorr));
          break;
        case AlgoKey.SPECTRAL:
          modifier = 1.0 + Math.abs(autoCorr) * Math.sin(normalizedPos * Math.PI);
          break;
        case AlgoKey.MARKOV:
        case AlgoKey.AFFINITY:
          modifier = 1.0 + (1.0 - Math.abs(normalizedPos - 0.5) * 2.0) * Math.tanh(stdDev / 20.0);
          break;
        case AlgoKey.FRACTAL:
          modifier = 1.0 + Math.tanh(stdDev / 30.0) * (1.0 - Math.abs(autoCorr));
          break;
        case AlgoKey.TEMPORAL:
          modifier = 1.0 + Math.max(0, autoCorr) * Math.cos(normalizedPos * Math.PI);
          break;
        case AlgoKey.BAYES:
          modifier = 1.0 + Math.sin(normalizedPos * Math.PI) * (1.0 - Math.tanh(stdDev / 40.0));
          break;
        case AlgoKey.MOMENTUM:
          modifier = 1.0 + Math.max(0, autoCorr) * Math.tanh(stdDev / 15.0);
          break;
        case AlgoKey.SPATIAL:
          const edgeDistance = Math.abs(pos - 2) / 2.0; // 0 au centre, 1 aux bords
          modifier = 1.0 + edgeDistance * Math.tanh(stdDev / 25.0);
          break;
        case AlgoKey.SHADOW_PROBABILITY:
          modifier = 1.0 + (1.0 - Math.abs(autoCorr)) * Math.tanh(stdDev / 30.0);
          break;
        case AlgoKey.NETWORK_CORRELATION:
          modifier = 1.0 + Math.tanh(stdDev / 20.0) * Math.sin(normalizedPos * Math.PI * 2.0);
          break;
        default:
          modifier = 1.0;
          break;
      }

      slotWeights[k] = Math.max(0.001, baseW * modifier);
    });

    const total = Object.values(slotWeights).reduce((a, b) => a + b, 0) || 1;
    keys.forEach(k => {
      slotWeights[k] = parseFloat((slotWeights[k] / total).toFixed(4));
    });

    profiles[pos] = slotWeights;
  }

  return profiles;
};

/**
 * Simulation asynchrone complète de la boucle de feedback forensic (Replay Déterministe).
 * Découple à 100% le noyau de calcul et l'interface graphique.
 */
export const runLoopSimulation = async (
  drawName: string,
  rawHistory: DrawResult[],
  loopSize: number,
  originalWeights: AlgoWeights,
  onProgress?: (progress: number, stepResult: LoopSimulationStepResult) => void,
  abortSignal?: AbortSignal
): Promise<LoopSimulationSummary> => {
  const history = purifyHistoryForDraw(drawName, rawHistory);
  if (history.length < 15) {
    throw new Error("Historique insuffisant pour lancer la simulation de boucle (minimum 15 tirages).");
  }

  // Caching check (Tirage Isolation Rule)
  const weightsHash = Object.entries(originalWeights).map(([k, v]) => `${k}:${v}`).join(",");
  const cacheKey = globalCache.generateKey("loop_simulation", drawName, `${loopSize}_${history[0]?.id || ""}_${weightsHash}`);
  const cachedResult = await globalCache.get<LoopSimulationSummary>(cacheKey, drawName);
  
  if (cachedResult) {
    logger.info(`[Loop Simulation] Relecture du Replay Déterministe pour ${drawName} via cache intelligent.`);
    if (onProgress && cachedResult.steps) {
      for (let i = 0; i < cachedResult.steps.length; i++) {
        if (abortSignal?.aborted) {
          throw new Error("Simulation interrompue.");
        }
        await new Promise(resolve => setTimeout(resolve, 40)); // nice playback animation
        const percent = Math.round(((i + 1) / cachedResult.steps.length) * 100);
        onProgress(percent, cachedResult.steps[i]);
      }
    }
    return cachedResult;
  }

  let currentWeights = { ...originalWeights };
  const staticWeights = { ...originalWeights };
  
  let accumulatedHitsStatic = 0;
  let accumulatedHitsLoop = 0;
  const steps: LoopSimulationStepResult[] = [];

  const { generateMasterPrediction } = await import("./predictionEngine");
  const { generateLearningSession, applyForensicAdjustments } = await import("./forensicTrainingBridge");

  for (let idx = 0; idx < loopSize; idx++) {
    if (abortSignal?.aborted) {
      throw new Error("Simulation interrompue.");
    }
    const historyIndex = loopSize - idx;
    if (historyIndex >= history.length || historyIndex < 0) continue;
    
    const targetDraw = history[historyIndex];
    const contextHistory = history.slice(historyIndex + 1);
    
    if (contextHistory.length < 10) continue;
    
    // 1. Predict with static weights
    const predStatic = await generateMasterPrediction(
        drawName,
        contextHistory,
        100,
        staticWeights,
        undefined,
        undefined,
        true
    );
    const hitsStaticList = predStatic.suggestedNumbers.filter(n => targetDraw.gagnants.includes(n));
    const hitsStatic = hitsStaticList.length;
    accumulatedHitsStatic += hitsStatic;
    
    // 2. Predict with current (continuously updated) weights
    const predLoop = await generateMasterPrediction(
        drawName,
        contextHistory,
        100,
        currentWeights,
        undefined,
        undefined,
        true
    );
    const hitsLoopList = predLoop.suggestedNumbers.filter(n => targetDraw.gagnants.includes(n));
    const hitsLoop = hitsLoopList.length;
    accumulatedHitsLoop += hitsLoop;
    
    // 3. Generate Forensic Report for this draw
    const forensicReport = await new Promise<any>((resolve, reject) => {
        // @ts-ignore
        const worker = new Worker(new URL("./workers/forensic.worker.ts?worker", import.meta.url), { type: "module" });
        
        registerActiveWorker(drawName, worker);

        worker.onmessage = (e) => {
            unregisterActiveWorker(drawName, worker);
            if (e.data.success) resolve(e.data.result);
            else reject(new Error(e.data.error));
            worker.terminate();
        };
        worker.onerror = (err) => {
            unregisterActiveWorker(drawName, worker);
            reject(err);
            worker.terminate();
        };
        worker.postMessage({ actualWinners: targetDraw.gagnants, history: contextHistory });
    });
    
    // 4. Generate Learning Session and apply forensic adjustments to weights for next round
    const learningSession = await generateLearningSession(forensicReport, contextHistory);
    currentWeights = await applyForensicAdjustments(learningSession, currentWeights, true);
    
    const stepResult: LoopSimulationStepResult = {
        date: new Date(targetDraw.date).toLocaleDateString("fr-FR", { day: 'numeric', month: 'short' }),
        predictedStatic: predStatic.suggestedNumbers,
        predictedLoop: predLoop.suggestedNumbers,
        actual: targetDraw.gagnants,
        hitsStatic,
        hitsLoop,
        regime: forensicReport.catastropheControlParams?.regime || "STABLE_MONOSTABLE"
    };

    steps.push(stepResult);
    
    if (onProgress) {
      const percent = Math.round(((idx + 1) / loopSize) * 100);
      onProgress(percent, stepResult);
    }
  }

  const improvementPercent = accumulatedHitsStatic > 0 
      ? ((accumulatedHitsLoop - accumulatedHitsStatic) / accumulatedHitsStatic) * 100
      : accumulatedHitsLoop * 100;

  const summaryResult = {
    totalHitsStatic: accumulatedHitsStatic,
    totalHitsLoop: accumulatedHitsLoop,
    improvement: parseFloat(improvementPercent.toFixed(1)),
    steps
  };

  await globalCache.set(cacheKey, summaryResult, CACHE_TTL.LONG, drawName);
  return summaryResult;
};

export const runBacktestTrainingAsync = (
  drawName: string,
  history: DrawResult[],
  sampleSize: number,
  onProgress?: (progress: number) => void,
  customWeights?: any
): Promise<TrainingReport> => {
  const purifiedHistory = purifyHistoryForDraw(drawName, history);
  return new Promise((resolve, reject) => {
    // Determine the environment correctly for worker loading in Vite
    // @ts-ignore
    const worker = new Worker(new URL("./workers/backtest.worker.ts?worker", import.meta.url), { type: "module" });

    worker.onmessage = (e) => {
      if (e.data.type === "progress" && onProgress) {
        onProgress(e.data.percent);
      } else if (e.data.type === "result") {
        resolve(e.data.report);
        worker.terminate();
      } else if (e.data.type === "error") {
        reject(new Error(e.data.error));
        worker.terminate();
      }
    };

    worker.onerror = (err) => {
      reject(err);
      worker.terminate();
    };

    worker.postMessage({ drawName, history: purifiedHistory, sampleSize, customWeights });
  });
};

export * from './forensicTrainingBridge';
