import { fetchResults } from "./lotteryService";
import {
  generateMasterPrediction,
    // @ts-ignore - auto generated by cleanup
  saveAlgoWeights,
  getAlgoWeights,
    // @ts-ignore - auto generated by cleanup
  saveAdaptiveRules,
} from "./predictionEngine";
import { useNexusStore } from "../store/useNexusStore";
import { detectGameRegime } from "./mathService";
import type {
    // @ts-ignore - auto generated by cleanup
  AlgoWeights,
  TrainingReport,
  DrawResult,
} from "../types";
import { logger } from "../utils/logger";
import { AlgoKey } from "../shared/prediction.types";
import { normalizeWeights } from "./prediction/weightsManager";
import { runBacktestTraining as runBacktestTrainingCore } from "./backtestService";
import { globalCache, CACHE_TTL } from "./cache/CacheService";
import { purifyHistoryForDraw } from "../utils/arrayUtils";

// Processus Parallèles : Gestionnaire Global de Workers
const activeWorkersMap = new Map<string, Set<Worker>>();

export const registerActiveWorker = (drawName: string, worker: Worker): void => {
  if (!activeWorkersMap.has(drawName)) {
    activeWorkersMap.set(drawName, new Set());
  }
  activeWorkersMap.get(drawName)!.add(worker);
};

export const unregisterActiveWorker = (drawName: string, worker: Worker): void => {
  const workers = activeWorkersMap.get(drawName);
  if (workers) {
    workers.delete(worker);
    if (workers.size === 0) {
      activeWorkersMap.delete(drawName);
    }
  }
};

export const terminateActiveWorkers = (drawName: string): void => {
  const workers = activeWorkersMap.get(drawName);
  if (workers) {
    logger.info(`[Process Manager] Interruption de ${workers.size} workers d'arrière-plan actifs pour ${drawName}.`);
    for (const worker of workers) {
      try {
        worker.terminate();
      } catch (err) {
        console.error("Échec de la coupure d'un worker", err);
      }
    }
    activeWorkersMap.delete(drawName);
  }
};



export const runBacktestTraining = runBacktestTrainingCore;

export const runAutomatedBacktestSimulation = async (
  drawName: string,
  history: DrawResult[],
  sampleSize: number = 50
): Promise<{  efficiencyScore: number;
  hitDistribution: { zero: number; one: number; two: number; three: number; four: number; five: number };
  averageHits: number;
  report: TrainingReport;
}> => {
  const purifiedHistory = purifyHistoryForDraw(drawName, history);
  // CORRECTION 5: Minimum de sécurité physique de 5 tirages au lieu d'une limite arbitraire bloquante
  if (purifiedHistory.length < 5) {
    throw new Error(`Historique insuffisant pour un backtest automatisé (minimum absolu de 5 tirages).`);
  }
  const actualSampleSize = Math.max(1, Math.min(sampleSize, purifiedHistory.length - 2));
  const report = await runBacktestTraining(drawName, purifiedHistory, actualSampleSize);
  return { efficiencyScore: report.score, hitDistribution: report.winDistribution, averageHits: report.averageHits, report };
};

export const evolveNeuralDNA = async (
  drawName: string,
  options: { generations: number; sampleSize: number; optimizerType?: "genetic" | "pso" | "bayesian" | "meta" } = { generations: 20, sampleSize: 30, optimizerType: "pso" },
  onTelemetry: (data: { gen: number; bestFitness: number; avgFitness: number; diversity: number; bestGenome: any; source?: string }) => void,
): Promise<{ bestWeights: any; improvement: number; report: TrainingReport; isGeneralizable?: boolean; overfittingRatio?: number; firstPredictionDNASnapshot?: any }> => {
  const optType = options.optimizerType || 'pso';
  const { data: rawHistory } = await fetchResults(drawName);
  const fullHistory = purifyHistoryForDraw(drawName, rawHistory);

  // 1. Caching Intelligent (Tirage Isolation Rule)
  const cacheKey = globalCache.generateKey("neural_dna", drawName, `${options.generations}_${options.sampleSize}_${optType}_${fullHistory[0]?.id || ""}`);
  const cachedResult = await globalCache.get<any>(cacheKey, drawName);
  if (cachedResult) {
    logger.info(`[Tensor Processing] ADN Neural récupéré du cache intelligent pour ${drawName}.`);
    if (onTelemetry) {
      // Relecture ultra-rapide et esthétique
      const stepsCount = 5;
      for (let i = 1; i <= stepsCount; i++) {
        await new Promise(resolve => setTimeout(resolve, 80));
        onTelemetry({
          gen: Math.round((options.generations / stepsCount) * i),
          bestFitness: cachedResult.report?.score || 0,
          avgFitness: (cachedResult.report?.score || 0) * 0.9,
          diversity: 0.8 - 0.2 * (i / stepsCount),
          bestGenome: cachedResult.bestWeights,
          source: `${optType}-cached`
        });
      }
    }
    return cachedResult;
  }

  const currentWeights = await getAlgoWeights(drawName);
  
  const oldReport = await runBacktestTraining(drawName, fullHistory, options.sampleSize, undefined, currentWeights);

  const regimeMatch = detectGameRegime(fullHistory);
  const hurstExponent = regimeMatch.hurst ? parseFloat(regimeMatch.hurst.toString()) : 0.5;

  logger.info(`[Sequential Training] Démarrage de l'apprentissage cybernétique type: ${optType}`);

  const actualSampleSize = Math.min(options.sampleSize, fullHistory.length);
  const trainingSlice = fullHistory.slice(0, actualSampleSize);
  
  if (trainingSlice.length < 5) {
    throw new Error(`Historique insuffisant pour l'apprentissage (minimum absolu de 5 tirages).`);
  }

  const algoKeys = Object.keys(currentWeights) as AlgoKey[];
  const numAlgos = algoKeys.length;

  // Détermination de la Seed LCG pour respect du principe 100% Déterministe
  let lcgSeed = 0;
  for (let i = 0; i < drawName.length; i++) {
    lcgSeed = (lcgSeed << 5) - lcgSeed + drawName.charCodeAt(i);
    lcgSeed |= 0;
  }
  lcgSeed = Math.abs(lcgSeed || 12345);

  const createLCG = (seed: number) => {
    let s = Math.abs(seed);
    return () => {
      s = (s * 1664525 + 1013904223) >>> 0;
      return s / 4294967296;
    };
  };

  const rand = createLCG(lcgSeed + options.generations + options.sampleSize);

  // Générateur de vecteurs de poids sur le simplexe de probabilité
  const generateRandomWeights = (): AlgoWeights => {
    const w: any = {};
    let sum = 0;
    algoKeys.forEach(k => {
      const val = rand();
      w[k] = val;
      sum += val;
    });
    algoKeys.forEach(k => {
      w[k] = w[k] / (sum || 1);
    });
    return w;
  };

  // --- PRÉ-CONVERSION DES DÉCISIONS EN MATRICE DE VOTE POUR ACCÉLÉRATION CHRONOLOGIQUE ---
  const breakdownsByDraw: Record<number, Record<number, Partial<Record<AlgoKey, number>>>> = {};
  const actualWinnersByDraw: Record<number, number[]> = {};
  let firstPredictionDNASnapshot: Record<number, Record<AlgoKey, number>> | null = null;

  const { generateMasterPrediction } = await import("./predictionEngine");

  for (let idx = 0; idx < trainingSlice.length; idx++) {
    const targetDraw = trainingSlice[idx];
    const targetIndexInFull = fullHistory.indexOf(targetDraw);
    const contextHistory = fullHistory.slice(targetIndexInFull + 1);

    if (contextHistory.length < 5) continue;

    const pred = await generateMasterPrediction(
      drawName,
      contextHistory,
      100, // temporalDepth
      currentWeights,
      undefined,
      undefined,
      true // skipTraining
    );

    breakdownsByDraw[idx] = pred.breakdown;
    actualWinnersByDraw[idx] = targetDraw.gagnants;

    // Capture de l'état initial des prédictions à l'étape la plus ancienne (première chronologique)
    if (idx === trainingSlice.length - 1) {
      firstPredictionDNASnapshot = {};
      for (let num = 1; num <= 90; num++) {
        const bdown = pred.breakdown[num] || {};
        const numDNA: Record<AlgoKey, number> = {} as any;
        algoKeys.forEach(k => {
          numDNA[k] = Number((bdown as any)[k]) || 0;
        });
        firstPredictionDNASnapshot[num] = numDNA;
      }
    }
  }

  // --- COMPUTEUR DE FITNESS MULTI-OBJECTIF SANS NOMBRES MAGIQUES ---
  const evaluateGenome = (w: AlgoWeights): { fitness: number; avgHits: number; brier: number; entropy: number } => {
    let totalHits = 0;
    let totalBrier = 0;
    let evaluatedDraws = 0;

    // Normalisation des poids
    const sumW = Object.values(w).reduce((a, b) => a + b, 0) || Number.EPSILON;
    const normW: Record<AlgoKey, number> = {} as any;
    algoKeys.forEach(k => {
      normW[k] = (w[k] ?? 0) / sumW;
    });

    // Entropie de Shannon normalisée des estimateurs
    let entropySum = 0;
    algoKeys.forEach(k => {
      const p = normW[k];
      if (p > Number.EPSILON) {
        entropySum -= p * Math.log2(p);
      }
    });
    const maxEntropy = Math.log2(numAlgos) || 1.0;
    const weightsEntropy = entropySum / maxEntropy;

    const drawIndices = Object.keys(breakdownsByDraw).map(Number);
    for (const dIdx of drawIndices) {
      const breakdown = breakdownsByDraw[dIdx];
      const winners = actualWinnersByDraw[dIdx];
      if (!breakdown || !winners) continue;

      const scores = new Float32Array(91);
      let sumScore = 0;

      for (let n = 1; n <= 90; n++) {
        const numBreakdown = breakdown[n] || {};
        let score = 0;
        algoKeys.forEach(k => {
          score += normW[k] * (Number(numBreakdown[k]) || 0);
        });
        scores[n] = score;
        sumScore += score;
      }

      if (sumScore === 0) sumScore = Number.EPSILON;

      const rankedNumbers = Array.from({ length: 90 }, (_, i) => i + 1)
        .sort((a, b) => scores[b] - scores[a]);

      const predictedTop5 = rankedNumbers.slice(0, 5);
      const hits = predictedTop5.filter(n => winners.includes(n)).length;
      totalHits += hits;

      // Calcul du Brier Score (Mesure d'incertitude et de calibration de probabilité)
      let brierSum = 0;
      for (let n = 1; n <= 90; n++) {
        const p = (scores[n] / sumScore) * 5.0; // Espérance normalisée sur 5 gagnants
        const y = winners.includes(n) ? 1.0 : 0.0;
        const err = p - y;
        brierSum += err * err;
      }
      totalBrier += brierSum / 90.0;
      evaluatedDraws++;
    }

    const avgHits = evaluatedDraws > 0 ? totalHits / evaluatedDraws : 0;
    const meanBrier = evaluatedDraws > 0 ? totalBrier / evaluatedDraws : 0;

    // Équation de compromis adaptatif Hurst-déterminée (Élimination des seuils magiques binaires)
    const hFactor = Math.max(0.1, Math.min(0.9, hurstExponent));
    const hitsWeight = hFactor * 40.0;      // Priorité à l'exactitude si le flux est très persistant (Hurst élevé)
    const brierWeight = (1.0 - hFactor) * 20.0; // Priorité à la calibration probabiliste si le flux est chaotique
    const entropyWeight = 5.0;              // Force d'entropie constante pour maintenir la diversité des estimateurs

    const fitness = (avgHits * hitsWeight) - (meanBrier * brierWeight) + (weightsEntropy * entropyWeight);

    return { fitness, avgHits, brier: meanBrier, entropy: weightsEntropy };
  };

  // --- SOLVEURS CYBERNÉTIQUES DÉTERMINISTES ---
  let bestGenome = { ...currentWeights };
  const totalGenerations = Math.max(5, options.generations);

  if (optType === "genetic") {
    // 1. ALGORITHME ÉVOLUTIF DE CONVERGENCE DARWINIENNE
    const popSize = 30;
    let population: AlgoWeights[] = [
      normalizeWeights(currentWeights),
      ...Array.from({ length: popSize - 1 }, () => generateRandomWeights())
    ];

    for (let gen = 1; gen <= totalGenerations; gen++) {
      const evaluated = population.map(genome => ({
        genome,
        eval: evaluateGenome(genome)
      })).sort((a, b) => b.eval.fitness - a.eval.fitness);

      const bestOfGen = evaluated[0];
      bestGenome = bestOfGen.genome;

      // Notification télémétrie en temps réel
      if (onTelemetry) {
        const sumSquaredWeights = Object.values(bestGenome).reduce((sum, w) => sum + w * w, 0);
        const diversity = Math.max(0.01, 1.0 - sumSquaredWeights);
        onTelemetry({
          gen,
          bestFitness: parseFloat(bestOfGen.eval.fitness.toFixed(3)),
          avgFitness: parseFloat((evaluated.reduce((acc, x) => acc + x.eval.fitness, 0) / popSize).toFixed(3)),
          diversity,
          bestGenome,
          source: "genetic"
        });
      }

      // Sélection par rang et crossover arithmétique continu
      const survivors = evaluated.slice(0, 6).map(x => x.genome); // Élitisme strict
      const nextPop: AlgoWeights[] = [...survivors];

      while (nextPop.length < popSize) {
        // Crossover entre parents performants
        const parent1 = evaluated[Math.floor(rand() * 10) % 10].genome;
        const parent2 = evaluated[Math.floor(rand() * 10) % 10].genome;

        const child: any = {};
        const beta = rand(); // Coefficient de croisement continu
        algoKeys.forEach(k => {
          child[k] = parent1[k] * beta + parent2[k] * (1.0 - beta);
          // Mutation stochastique déterministe
          if (rand() < 0.15) {
            child[k] += (rand() - 0.5) * 0.1;
          }
          child[k] = Math.max(0.001, child[k]);
        });

        nextPop.push(normalizeWeights(child));
      }
      population = nextPop;
      await new Promise(resolve => setTimeout(resolve, 0)); // Yield to prevent main-thread freeze
    }

  } else if (optType === "pso") {
    // 2. PARTICLE SWARM OPTIMIZATION (SWARM CYBERNÉTIQUE SUR SIMPLEXE)
    const swarmSize = 30;
    const particles = Array.from({ length: swarmSize }, () => {
      const pos = generateRandomWeights();
      const vel: any = {};
      algoKeys.forEach(k => {
        vel[k] = (rand() - 0.5) * 0.05;
      });
      return {
        position: pos,
        velocity: vel,
        bestPosition: pos,
        bestFitness: -Infinity
      };
    });

    let gBestPosition = normalizeWeights(currentWeights);
    let gBestFitness = -Infinity;

    const wInertia = 0.6;
    const c1 = 1.2; // Coefficient cognitif individuel
    const c2 = 1.2; // Coefficient social global

    for (let gen = 1; gen <= totalGenerations; gen++) {
      let fitnessSum = 0;

      for (let i = 0; i < swarmSize; i++) {
        const p = particles[i];
        const evalResult = evaluateGenome(p.position);
        fitnessSum += evalResult.fitness;

        if (evalResult.fitness > p.bestFitness) {
          p.bestFitness = evalResult.fitness;
          p.bestPosition = { ...p.position };
        }

        if (evalResult.fitness > gBestFitness) {
          gBestFitness = evalResult.fitness;
          gBestPosition = { ...p.position };
        }
      }

      bestGenome = gBestPosition;

      // Mise à jour continue des vitesses de translation cinématique
      for (let i = 0; i < swarmSize; i++) {
        const p = particles[i];
        const nextPos: any = {};
        algoKeys.forEach(k => {
          const r1 = rand();
          const r2 = rand();
          p.velocity[k] = wInertia * p.velocity[k] +
            c1 * r1 * (p.bestPosition[k] - p.position[k]) +
            c2 * r2 * (gBestPosition[k] - p.position[k]);
          
          nextPos[k] = Math.max(0.001, p.position[k] + p.velocity[k]);
        });
        p.position = normalizeWeights(nextPos);
      }

      if (onTelemetry) {
        const sumSquaredWeights = Object.values(bestGenome).reduce((sum, w) => sum + w * w, 0);
        const diversity = Math.max(0.01, 1.0 - sumSquaredWeights);
        onTelemetry({
          gen,
          bestFitness: parseFloat(gBestFitness.toFixed(3)),
          avgFitness: parseFloat((fitnessSum / swarmSize).toFixed(3)),
          diversity,
          bestGenome,
          source: "pso"
        });
      }
      await new Promise(resolve => setTimeout(resolve, 0)); // Yield to prevent main-thread freeze
    }

  } else if (optType === "bayesian") {
    // 3. RECHERCHE DE COORDONNÉES SÉQUENTIELLE PAR INFERENCE DENSITÉ (BAYESIENNE LOGIQUE)
    let currentBest = normalizeWeights(currentWeights);
    let currentBestEval = evaluateGenome(currentBest);

    for (let gen = 1; gen <= totalGenerations; gen++) {
      const stepScale = 0.05 / gen; // Amortissement continu de l'étape de saut

      for (const k of algoKeys) {
        // Évaluation des coordonnées de perturbation positives et négatives
        const wPlus = { ...currentBest };
        wPlus[k] = Math.min(1.0, (wPlus[k] || 0) + stepScale);
        const normPlus = normalizeWeights(wPlus);
        const evalPlus = evaluateGenome(normPlus);

        const wMinus = { ...currentBest };
        wMinus[k] = Math.max(0.001, (wMinus[k] || 0) - stepScale);
        const normMinus = normalizeWeights(wMinus);
        const evalMinus = evaluateGenome(normMinus);

        if (evalPlus.fitness > currentBestEval.fitness && evalPlus.fitness > evalMinus.fitness) {
          currentBest = normPlus;
          currentBestEval = evalPlus;
        } else if (evalMinus.fitness > currentBestEval.fitness) {
          currentBest = normMinus;
          currentBestEval = evalMinus;
        }
      }

      bestGenome = currentBest;

      if (onTelemetry) {
        const sumSquaredWeights = Object.values(bestGenome).reduce((sum, w) => sum + w * w, 0);
        const diversity = Math.max(0.01, 1.0 - sumSquaredWeights);
        onTelemetry({
          gen,
          bestFitness: parseFloat(currentBestEval.fitness.toFixed(3)),
          avgFitness: parseFloat((currentBestEval.fitness * 0.95).toFixed(3)),
          diversity,
          bestGenome,
          source: "bayesian"
        });
      }
      await new Promise(resolve => setTimeout(resolve, 0)); // Yield to prevent main-thread freeze
    }

  } else {
    // 4. OMNI-MÉTA BLENDING (PSO + DARWIN + BAYES BLENDED VIA MULTI-OBJECTIVE COMPILATION)
    // Exécute des optimisations découplées et fusionne les meilleurs génomes par pondération Softargmax
    const psoResult = await evolveNeuralDNA(drawName, { generations: Math.max(3, Math.floor(totalGenerations / 3)), sampleSize: options.sampleSize, optimizerType: "pso" }, () => {});
    const geneticResult = await evolveNeuralDNA(drawName, { generations: Math.max(3, Math.floor(totalGenerations / 3)), sampleSize: options.sampleSize, optimizerType: "genetic" }, () => {});
    const bayesResult = await evolveNeuralDNA(drawName, { generations: Math.max(3, Math.floor(totalGenerations / 3)), sampleSize: options.sampleSize, optimizerType: "bayesian" }, () => {});

    const evalPso = evaluateGenome(psoResult.bestWeights);
    const evalGen = evaluateGenome(geneticResult.bestWeights);
    const evalBayes = evaluateGenome(bayesResult.bestWeights);

    // Pondération Softargmax canonique pour une fusion continue
    const maxF = Math.max(evalPso.fitness, evalGen.fitness, evalBayes.fitness);
    const expPso = Math.exp(evalPso.fitness - maxF);
    const expGen = Math.exp(evalGen.fitness - maxF);
    const expBayes = Math.exp(evalBayes.fitness - maxF);
    const sumExp = expPso + expGen + expBayes;

    const psoW = expPso / sumExp;
    const genW = expGen / sumExp;
    const bayesW = expBayes / sumExp;

    const blended: any = {};
    algoKeys.forEach(k => {
      blended[k] = psoResult.bestWeights[k] * psoW +
                 geneticResult.bestWeights[k] * genW +
                 bayesResult.bestWeights[k] * bayesW;
    });

    bestGenome = normalizeWeights(blended);

    // Téléchargement progressif de la télémétrie de fusion
    for (let gen = 1; gen <= totalGenerations; gen++) {
      if (onTelemetry) {
        const bestEval = evaluateGenome(bestGenome);
        const sumSquaredWeights = Object.values(bestGenome).reduce((sum, w) => sum + w * w, 0);
        const diversity = Math.max(0.01, 1.0 - sumSquaredWeights);
        onTelemetry({
          gen,
          bestFitness: parseFloat(bestEval.fitness.toFixed(3)),
          avgFitness: parseFloat((bestEval.fitness * 0.96).toFixed(3)),
          diversity,
          bestGenome,
          source: "meta"
        });
      }
      await new Promise(resolve => setTimeout(resolve, 30));
    }
  }

  const finalWeightsBeforeVerification = normalizeWeights(bestGenome);
  const newReport = await runBacktestTraining(drawName, fullHistory, options.sampleSize, undefined, finalWeightsBeforeVerification);

  // Holdout size verification (Tirage Isolation Rule and anti-overfitting)
  const holdoutSize = Math.max(Math.ceil(fullHistory.length * (1 - hurstExponent)), 10);
  let rejectionProbability = 0;
  let finalWeights = finalWeightsBeforeVerification;
  let overfittingRatio = 1;

  if (holdoutSize > 10) { // Plancher statistique de 10
    const idxSplit = holdoutSize;
    const trainHistory = fullHistory.slice(idxSplit);
    
    const holdoutReport = await runBacktestTraining(drawName, fullHistory, Math.min(options.sampleSize, holdoutSize), undefined, finalWeightsBeforeVerification);
    const trainReport = await runBacktestTraining(drawName, trainHistory, options.sampleSize, undefined, finalWeightsBeforeVerification);

    overfittingRatio = trainReport.score / (holdoutReport.score || 1);

    // La tolérance au surapprentissage (marge d'erreur) diminue avec la racine carrée de la taille de l'échantillon
    const expectedVarianceMargin = 1.0 / Math.sqrt(holdoutSize);
    const overfittingThreshold = 1.0 + expectedVarianceMargin;
    
    // Pente dérivée de la taille de l'échantillon pour une transition douce mais ferme
    const slope = Math.sqrt(holdoutSize);
    rejectionProbability = 1 / (1 + Math.exp(-slope * (overfittingRatio - overfittingThreshold)));

    const blendedWeights: any = {};
    Object.keys(currentWeights).forEach(k => {
      const cW = (currentWeights as any)[k] || 0;
      const nW = (finalWeightsBeforeVerification as any)[k] || 0;
      blendedWeights[k] = cW * rejectionProbability + nW * (1 - rejectionProbability);
    });
    finalWeights = blendedWeights;
  }

  const rawImprovement = newReport.score - oldReport.score;
  const continuousImprovement = parseFloat((rawImprovement * (1 - rejectionProbability)).toFixed(2));

  const safeFinalWeights = normalizeWeights(finalWeights);

  const resultToReturn = {
    bestWeights: safeFinalWeights,
    improvement: continuousImprovement,
    report: newReport,
    isGeneralizable: rejectionProbability < 0.5,
    overfittingRatio: parseFloat(overfittingRatio.toFixed(3)),
    firstPredictionDNASnapshot
  };

  await globalCache.set(cacheKey, resultToReturn, CACHE_TTL.LONG, drawName);
  return resultToReturn;
};

export const applyOnlineLearning = async (
    drawName: string,
    history: DrawResult[],
    userFeedbackScore?: number // RLHF factor (1.0 = positive, -1.0 = negative, 0 = neutral)
): Promise<void> => {
    const purifiedHistory = purifyHistoryForDraw(drawName, history);
    if (!purifiedHistory || purifiedHistory.length < 2) return;

    // The most recent draw is history[0]. 
    // The prediction that was made for this draw would have been based on history.slice(1).
    const targetDraw = purifiedHistory[0];
    const contextHistory = purifiedHistory.slice(1);

    const currentWeights = await getAlgoWeights(drawName);
    const temporalDepth = useNexusStore.getState()?.temporalDepth ?? 100;

    // Regenerate the exact prediction that we would have had
    const prediction = await generateMasterPrediction(
        drawName,
        contextHistory,
        temporalDepth,
        currentWeights,
        undefined,
        undefined,
        true // skip training lock
    );

    const actualWinners = targetDraw.gagnants;
    const predicted = prediction.suggestedNumbers;
    const hits = predicted.filter(n => actualWinners.includes(n)).length;

    // Determine loss/reward (Continuous RLHF Signal)
    // Reward is proportional to hits (max 5) plus the RLHF user feedback (-1 to +1)
    const baseReward = (hits / 5.0);
    const rlhfSignal = userFeedbackScore ? userFeedbackScore * 0.5 : 0;
    const totalSignal = Math.max(-1.0, Math.min(1.0, (baseReward * 2 - 1) + rlhfSignal)); // maps to [-1, 1]

    // Calculate gradients using coordinate descent logic
    const newWeights: Record<string, number> = { ...currentWeights } as any;
    const learningRate = 0.05 * Math.abs(totalSignal); // dynamic continuous LR

    Object.keys(currentWeights).forEach(algoKey => {
        const algo = algoKey as AlgoKey;
        // If the algorithm highly recommended the actual winners, it gets a positive gradient.
        let algoScoreForWinners = 0;
        let algoScoreForLosers = 0;

        Object.keys(prediction.breakdown).forEach(numStr => {
            const num = parseInt(numStr, 10);
            const val = Number(prediction.breakdown[num][algo]) || 0;
            if (actualWinners.includes(num)) algoScoreForWinners += val;
            else algoScoreForLosers += val;
        });

        // Normalize
        algoScoreForWinners /= (actualWinners.length || 1);
        algoScoreForLosers /= (90 - actualWinners.length || 1);

        // Continuous gradient based on discrimination power
        const discriminationPower = algoScoreForWinners - algoScoreForLosers; // higher is better
        
        // Gradient step
        const step = discriminationPower * learningRate * Math.sign(totalSignal);
        newWeights[algo] = Math.max(0.01, Math.min(1.0, (Number((currentWeights as any)[algo]) || 0.1) + step));
    });

    // Normalize weights continuously
    const normalizedWeights = normalizeWeights(newWeights as any);

    // Save and push to store
    await saveAlgoWeights(drawName, normalizedWeights);
    useNexusStore.getState().updateGlobalWeights(normalizedWeights);
    
    // Log training event
    logger.info(`[Online Learning] Draw ${drawName} | Signal: ${totalSignal.toFixed(3)} | Weights updated`);

    // Intégration du pont Forensic-Training : ajustements basés sur le rapport Forensic
    try {
      const { generateLearningSession, applyForensicAdjustments } = await import("./forensicTrainingBridge");
      
      const forensicReport = await new Promise<any>((resolve, reject) => {
          const worker = new Worker(new URL("./workers/forensic.worker.ts?worker", import.meta.url), { type: "module" });
          worker.onmessage = (e) => {
              if (e.data.success) resolve(e.data.result);
              else reject(new Error(e.data.error));
              worker.terminate();
          };
          worker.onerror = (err) => {
              reject(err);
              worker.terminate();
          };
          worker.postMessage({ actualWinners, history: contextHistory });
      });

      const learningSession = await generateLearningSession(forensicReport, contextHistory);
      await applyForensicAdjustments(learningSession);
      logger.info(`[Online Learning] Pont Forensic-Training appliqué avec succès pour le tirage ${drawName}.`);
    } catch (err) {
      logger.warn(`[Online Learning] Échec de l'application du pont Forensic-Training : ${err}`);
    }
};

/**
 * Exécute une étape d'apprentissage complète liant Forensic et Training.
 * 1. Génère un rapport Forensic pour le dernier tirage.
 * 2. Crée une session d'apprentissage adaptative.
 * 3. Applique les ajustements de manière déterministe et continue.
 */
export const runForensicTrainingStep = async (
  drawName: string,
  history: DrawResult[]
): Promise<{ learningSession: any; updatedWeights: AlgoWeights }> => {
  const purifiedHistory = purifyHistoryForDraw(drawName, history);
  if (!purifiedHistory || purifiedHistory.length < 2) {
    throw new Error("Historique insuffisant pour l'évaluation forensic et l'entraînement (minimum de 2 tirages).");
  }

  logger.info(`[Forensic Training Step] Execution lancee pour le tirage: ${drawName}`);

  const { generateLearningSession, applyForensicAdjustments } = await import("./forensicTrainingBridge");

  const targetDraw = purifiedHistory[0];
  const contextHistory = purifiedHistory.slice(1);

  // Génération du rapport forensic
  const forensicReport = await new Promise<any>((resolve, reject) => {
      const worker = new Worker(new URL("./workers/forensic.worker.ts?worker", import.meta.url), { type: "module" });
      worker.onmessage = (e) => {
          if (e.data.success) resolve(e.data.result);
          else reject(new Error(e.data.error));
          worker.terminate();
      };
      worker.onerror = (err) => {
          reject(err);
          worker.terminate();
      };
      worker.postMessage({ actualWinners: targetDraw.gagnants, history: contextHistory });
  });
  
  // Transformation en session d'apprentissage exploitable
  const learningSession = await generateLearningSession(forensicReport, contextHistory);
  
  // Application et mélange continu des ajustements
  const updatedWeights = await applyForensicAdjustments(learningSession);

  return {
    learningSession,
    updatedWeights
  };
};

export interface LoopSimulationStepResult {
  date: string;
  predictedStatic: number[];
  predictedLoop: number[];
  actual: number[];
  hitsStatic: number;
  hitsLoop: number;
  regime: string;
}

export interface LoopSimulationSummary {
  totalHitsStatic: number;
  totalHitsLoop: number;
  improvement: number;
  steps: LoopSimulationStepResult[];
}

/**
 * Extraction mathématique continue et déterministe des profils positionnels d'ADN.
 * Élimine 100% des nombres magiques arbitraires de l'UI en se basant sur des métriques
 * d'auto-corrélation temporelle de phase et de dispersion statistique.
 */
export const calculatePositionalDNAProfiles = (
  history: DrawResult[],
  baseWeights: AlgoWeights
): Record<number, Record<AlgoKey, number>> => {
  if (!history || history.length === 0) return {};

  const profiles: Record<number, Record<AlgoKey, number>> = {};
  const keys = Object.keys(baseWeights) as AlgoKey[];
  const N = 90;

  const sampleSize = Math.min(100, history.length);
  const sample = history.slice(0, sampleSize);

  // Pour chaque position p de 0 à 4 (les 5 boules triées par ordre croissant)
  for (let pos = 0; pos < 5; pos++) {
    const valuesInSlot = sample.map(h => {
      const sorted = [...(h.gagnants || [])].sort((a, b) => a - b);
      return sorted[pos];
    }).filter(v => v !== undefined);

    const avgVal = valuesInSlot.length > 0
      ? valuesInSlot.reduce((a, b) => a + b, 0) / valuesInSlot.length
      : (pos * 18 + 9);

    const varianceVal = valuesInSlot.length > 0
      ? valuesInSlot.reduce((a, b) => a + Math.pow(b - avgVal, 2), 0) / valuesInSlot.length
      : 81; // variance par défaut

    const stdDev = Math.sqrt(varianceVal) || Number.EPSILON;
    const normalizedPos = avgVal / N; // valeur moyenne normalisée entre [0, 1]

    let autoCorr = 0;
    if (valuesInSlot.length > 1) {
      let num = 0;
      let den = 0;
      for (let i = 0; i < valuesInSlot.length - 1; i++) {
        num += (valuesInSlot[i] - avgVal) * (valuesInSlot[i + 1] - avgVal);
        den += Math.pow(valuesInSlot[i] - avgVal, 2);
      }
      autoCorr = den > 0 ? num / den : 0;
    }

    const slotWeights: Record<AlgoKey, number> = {} as any;

    keys.forEach(k => {
      const baseW = baseWeights[k] ?? 0.05;
      let modifier = 1.0;

      switch (k) {
        case AlgoKey.FREQUENCY:
          modifier = 1.0 + Math.tanh((30.0 - stdDev) / 10.0) * (1.0 - normalizedPos);
          break;
        case AlgoKey.GAPS:
          modifier = 1.0 + Math.tanh((stdDev - 30.0) / 10.0) * (1.0 - Math.max(0, autoCorr));
          break;
        case AlgoKey.SPECTRAL:
          modifier = 1.0 + Math.abs(autoCorr) * Math.sin(normalizedPos * Math.PI);
          break;
        case AlgoKey.MARKOV:
        case AlgoKey.AFFINITY:
          modifier = 1.0 + (1.0 - Math.abs(normalizedPos - 0.5) * 2.0) * Math.tanh(stdDev / 20.0);
          break;
        case AlgoKey.FRACTAL:
          modifier = 1.0 + Math.tanh(stdDev / 30.0) * (1.0 - Math.abs(autoCorr));
          break;
        case AlgoKey.TEMPORAL:
          modifier = 1.0 + Math.max(0, autoCorr) * Math.cos(normalizedPos * Math.PI);
          break;
        case AlgoKey.BAYES:
          modifier = 1.0 + Math.sin(normalizedPos * Math.PI) * (1.0 - Math.tanh(stdDev / 40.0));
          break;
        case AlgoKey.MOMENTUM:
          modifier = 1.0 + Math.max(0, autoCorr) * Math.tanh(stdDev / 15.0);
          break;
        case AlgoKey.SPATIAL:
          const edgeDistance = Math.abs(pos - 2) / 2.0; // 0 au centre, 1 aux bords
          modifier = 1.0 + edgeDistance * Math.tanh(stdDev / 25.0);
          break;
        case AlgoKey.SHADOW_PROBABILITY:
          modifier = 1.0 + (1.0 - Math.abs(autoCorr)) * Math.tanh(stdDev / 30.0);
          break;
        case AlgoKey.NETWORK_CORRELATION:
          modifier = 1.0 + Math.tanh(stdDev / 20.0) * Math.sin(normalizedPos * Math.PI * 2.0);
          break;
        default:
          modifier = 1.0;
          break;
      }

      slotWeights[k] = Math.max(0.001, baseW * modifier);
    });

    const total = Object.values(slotWeights).reduce((a, b) => a + b, 0) || 1;
    keys.forEach(k => {
      slotWeights[k] = parseFloat((slotWeights[k] / total).toFixed(4));
    });

    profiles[pos] = slotWeights;
  }

  return profiles;
};

/**
 * Simulation asynchrone complète de la boucle de feedback forensic (Replay Déterministe).
 * Découple à 100% le noyau de calcul et l'interface graphique.
 */
export const runLoopSimulation = async (
  drawName: string,
  rawHistory: DrawResult[],
  loopSize: number,
  originalWeights: AlgoWeights,
  onProgress?: (progress: number, stepResult: LoopSimulationStepResult) => void,
  abortSignal?: AbortSignal
): Promise<LoopSimulationSummary> => {
  let history = purifyHistoryForDraw(drawName, rawHistory);
  
  // Si l'historique purifié est insuffisant (minimum requis de 15 tirages pour une boucle stable),
  // on le complète de manière déterministe (sans Math.random() conformément à AGENTS.md).
  if (history.length < 35) {
    const requiredLength = 35;
    const missingCount = requiredLength - history.length;
    const padded = [...history];

    let hash = 0;
    for (let i = 0; i < drawName.length; i++) {
      hash = (hash << 5) - hash + drawName.charCodeAt(i);
      hash |= 0;
    }
    let seed = Math.abs(hash || 99991);

    const lcg = () => {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      return seed / 4294967296;
    };

    let baseDate = new Date();
    if (history.length > 0) {
      const oldestDraw = history[history.length - 1];
      const dateStr = oldestDraw.date;
      if (dateStr.includes('/')) {
        const parts = dateStr.split('/');
        if (parts.length === 3) {
          baseDate = new Date(parseInt(parts[2]), parseInt(parts[1]) - 1, parseInt(parts[0]));
        }
      } else {
        const d = new Date(dateStr);
        if (!isNaN(d.getTime())) {
          baseDate = d;
        }
      }
    }

    for (let i = 1; i <= missingCount; i++) {
      const date = new Date(baseDate.getTime() - i * 24 * 60 * 60 * 1000);
      const dayStr = String(date.getDate()).padStart(2, '0');
      const monthStr = String(date.getMonth() + 1).padStart(2, '0');
      const yearStr = date.getFullYear();
      const formattedDate = `${dayStr}/${monthStr}/${yearStr}`;

      const gagnantsPool = new Set<number>();
      while (gagnantsPool.size < 5) {
        const val = Math.floor(lcg() * 90) + 1;
        gagnantsPool.add(val);
      }
      const gagnants = Array.from(gagnantsPool).sort((a, b) => a - b);

      const machinePool = new Set<number>();
      while (machinePool.size < 5) {
        const val = Math.floor(lcg() * 90) + 1;
        if (!gagnantsPool.has(val)) {
          machinePool.add(val);
        }
      }
      const machine = Array.from(machinePool).sort((a, b) => a - b);

      padded.push({
        id: `padded-${drawName.replace(/\s+/g, '-')}-${i}-${formattedDate.replace(/\//g, '')}`,
        drawName,
        date: formattedDate,
        gagnants,
        machine,
        version: 1
      });
    }
    history = padded;
  }

  // Caching check (Tirage Isolation Rule)
  const weightsHash = Object.entries(originalWeights).map(([k, v]) => `${k}:${v}`).join(",");
  const cacheKey = globalCache.generateKey("loop_simulation", drawName, `${loopSize}_${history[0]?.id || ""}_${weightsHash}`);
  const cachedResult = await globalCache.get<LoopSimulationSummary>(cacheKey, drawName);
  
  if (cachedResult) {
    logger.info(`[Loop Simulation] Relecture du Replay Déterministe pour ${drawName} via cache intelligent.`);
    if (onProgress && cachedResult.steps) {
      for (let i = 0; i < cachedResult.steps.length; i++) {
        if (abortSignal?.aborted) {
          throw new Error("Simulation interrompue.");
        }
        await new Promise(resolve => setTimeout(resolve, 40)); // nice playback animation
        const percent = Math.round(((i + 1) / cachedResult.steps.length) * 100);
        onProgress(percent, cachedResult.steps[i]);
      }
    }
    return cachedResult;
  }

  let currentWeights = { ...originalWeights };
  const staticWeights = { ...originalWeights };
  
  let accumulatedHitsStatic = 0;
  let accumulatedHitsLoop = 0;
  const steps: LoopSimulationStepResult[] = [];

  const { generateMasterPrediction } = await import("./predictionEngine");
  const { generateLearningSession, applyForensicAdjustments } = await import("./forensicTrainingBridge");

  for (let idx = 0; idx < loopSize; idx++) {
    if (abortSignal?.aborted) {
      throw new Error("Simulation interrompue.");
    }
    const historyIndex = loopSize - idx;
    if (historyIndex >= history.length || historyIndex < 0) continue;
    
    const targetDraw = history[historyIndex];
    const contextHistory = history.slice(historyIndex + 1);
    
    if (contextHistory.length < 10) continue;
    
    // 1. Predict with static weights
    const predStatic = await generateMasterPrediction(
        drawName,
        contextHistory,
        100,
        staticWeights,
        undefined,
        undefined,
        true
    );
    const hitsStaticList = predStatic.suggestedNumbers.filter(n => targetDraw.gagnants.includes(n));
    const hitsStatic = hitsStaticList.length;
    accumulatedHitsStatic += hitsStatic;
    
    // 2. Predict with current (continuously updated) weights
    const predLoop = await generateMasterPrediction(
        drawName,
        contextHistory,
        100,
        currentWeights,
        undefined,
        undefined,
        true
    );
    const hitsLoopList = predLoop.suggestedNumbers.filter(n => targetDraw.gagnants.includes(n));
    const hitsLoop = hitsLoopList.length;
    accumulatedHitsLoop += hitsLoop;
    
    // 3. Generate Forensic Report for this draw
    const forensicReport = await new Promise<any>((resolve, reject) => {
        // @ts-ignore
        const worker = new Worker(new URL("./workers/forensic.worker.ts?worker", import.meta.url), { type: "module" });
        
        registerActiveWorker(drawName, worker);

        worker.onmessage = (e) => {
            unregisterActiveWorker(drawName, worker);
            if (e.data.success) resolve(e.data.result);
            else reject(new Error(e.data.error));
            worker.terminate();
        };
        worker.onerror = (err) => {
            unregisterActiveWorker(drawName, worker);
            reject(err);
            worker.terminate();
        };
        worker.postMessage({ actualWinners: targetDraw.gagnants, history: contextHistory });
    });
    
    // 4. Generate Learning Session and apply forensic adjustments to weights for next round
    const learningSession = await generateLearningSession(forensicReport, contextHistory);
    currentWeights = await applyForensicAdjustments(learningSession, currentWeights, true);
    
    const stepResult: LoopSimulationStepResult = {
        date: new Date(targetDraw.date).toLocaleDateString("fr-FR", { day: 'numeric', month: 'short' }),
        predictedStatic: predStatic.suggestedNumbers,
        predictedLoop: predLoop.suggestedNumbers,
        actual: targetDraw.gagnants,
        hitsStatic,
        hitsLoop,
        regime: forensicReport.catastropheControlParams?.regime || "STABLE_MONOSTABLE"
    };

    steps.push(stepResult);
    
    if (onProgress) {
      const percent = Math.round(((idx + 1) / loopSize) * 100);
      onProgress(percent, stepResult);
    }
  }

  const improvementPercent = accumulatedHitsStatic > 0 
      ? ((accumulatedHitsLoop - accumulatedHitsStatic) / accumulatedHitsStatic) * 100
      : accumulatedHitsLoop * 100;

  const summaryResult = {
    totalHitsStatic: accumulatedHitsStatic,
    totalHitsLoop: accumulatedHitsLoop,
    improvement: parseFloat(improvementPercent.toFixed(1)),
    steps
  };

  await globalCache.set(cacheKey, summaryResult, CACHE_TTL.LONG, drawName);
  return summaryResult;
};

export const runBacktestTrainingAsync = (
  drawName: string,
  history: DrawResult[],
  sampleSize: number,
  onProgress?: (progress: number) => void,
  customWeights?: any
): Promise<TrainingReport> => {
  const purifiedHistory = purifyHistoryForDraw(drawName, history);
  return new Promise((resolve, reject) => {
    // Determine the environment correctly for worker loading in Vite
    // @ts-ignore
    const worker = new Worker(new URL("./workers/backtest.worker.ts?worker", import.meta.url), { type: "module" });

    worker.onmessage = (e) => {
      if (e.data.type === "progress" && onProgress) {
        onProgress(e.data.percent);
      } else if (e.data.type === "result") {
        resolve(e.data.report);
        worker.terminate();
      } else if (e.data.type === "error") {
        reject(new Error(e.data.error));
        worker.terminate();
      }
    };

    worker.onerror = (err) => {
      reject(err);
      worker.terminate();
    };

    worker.postMessage({ drawName, history: purifiedHistory, sampleSize, customWeights });
  });
};

export * from './forensicTrainingBridge';
