
import { AppError } from '../utils/AppError';
import { apiClient } from '../core/api/apiClient';

/**
 * NEXUS WORKER SERVICE
 * Orchestre les calculs lourds en arrière-plan.
 * Tente d'abord l'Edge Function Supabase, puis utilise un véritable Web Worker local en cas d'échec
 * pour ne plus jamais bloquer le thread principal (UI).
 */

class WorkerService {
    private localWorker: Worker | null = null;
    private callbacks: Map<string, { resolve: Function, reject: Function }> = new Map();
    private workerReady: boolean = false;

    constructor() {
        this.initLocalWorker();
    }

    private initLocalWorker() {
        try {
            if (typeof Worker === 'undefined') {
                console.warn("L'environnement ne supporte pas les Web Workers. Exécution en mode dégradé (synchrone).");
                return;
            }
            // Initialisation d'un vrai Web Worker via Vite
            this.localWorker = new Worker(new URL('./nexus.worker.ts?worker', /* @ts-ignore */ import.meta.url), { type: 'module' });
            
            this.localWorker.onmessage = (e: MessageEvent) => {
                const { taskId, success, result, error } = e.data;
                const callback = this.callbacks.get(taskId);
                
                if (callback) {
                    if (success) {
                        callback.resolve(result);
                    } else {
                        callback.reject(new Error(error));
                    }
                    this.callbacks.delete(taskId);
                }
            };
            
            this.localWorker.onerror = (e) => {
                console.error("Local Worker interne error:", e);
                this.workerReady = false;
                // Reject all pending tasks because the worker is dead
    // @ts-ignore - auto generated by cleanup
                for (const [taskId, callback] of this.callbacks.entries()) {
                    callback.reject(new Error("Local Worker a crashé ou n'a pas pu se charger."));
                }
                this.callbacks.clear();
            };
            
            this.workerReady = true;
        } catch (e) {
            console.error("Impossible d'initialiser le Web Worker Local. Les calculs seront bloquants.", e);
            this.workerReady = false;
        }
    }

    private internalWorkerCounter = 0;

    public isAvailable(): boolean {
        return true;
    }

    private runInLocalWorker(task: string, payload: unknown, history: unknown[]): Promise<unknown> {
        return new Promise((resolve, reject) => {
            if (!this.workerReady || !this.localWorker) {
                return reject(new Error("Local Worker non disponible"));
            }
            
            this.internalWorkerCounter++;
            const taskId = `${task}_${Date.now()}_${this.internalWorkerCounter}`;
            this.callbacks.set(taskId, { resolve, reject });
            
            this.localWorker.postMessage({
                taskId,
                task,
                payload,
                history
            });
            
            // Timeout de sécurité pour le worker local (10 secondes maximum)
            setTimeout(() => {
                if (this.callbacks.has(taskId)) {
                    this.callbacks.delete(taskId);
                    reject(new Error(`Timeout du Worker Local pour la tâche ${task}`));
                }
            }, 10000);
        });
    }

    private edgeFailures: number = 0;
    private edgeCooldownUntil: number = 0;

    public async runTask<T>(task: string, payload: unknown = {}, history: unknown[] = []): Promise<T> {
        // Circuit Breaker: Si l'Edge a trop échoué, on passe directement au Local Worker pendant un temps (ex: 5 minutes)
        if (Date.now() < this.edgeCooldownUntil) {
            return this.runInLocalWorker(task, payload, history) as Promise<T>;
        }

        try {
            const response = await apiClient.post<{ success: boolean, result?: unknown, error?: string }>('compute-nexus-analytics', {
                task,
                payload,
                history
            }, { suppressErrorLogging: true });

            if (response && response.success) {
                // Reset circuit breaker on success
                this.edgeFailures = 0;
                return response.result as T;
            } else {
                throw new Error(response?.error || "Erreur silencieuse venant de l'Edge Function");
            }
        } catch (e: unknown) {
            this.edgeFailures++;
            if (this.edgeFailures >= 3) {
                // Si ça rate 3 fois de suite, on met l'Edge Function en pause pendant 5 minutes
                this.edgeCooldownUntil = Date.now() + 5 * 60 * 1000;
                console.info(`[Nexus Worker] Edge Function hors ligne (Circuit ouvert). Passage en local exclusif pendant 5 min.`);
            } else {
                console.info(`[Nexus Worker] Edge Function indisponible (non déployée). Délégation en cours au Worker Local...`);
            }
            
            try {
                // Utilisation du Worker Asynchrone au lieu d'importer directement mathCore sur le thread principal
                const result = await this.runInLocalWorker(task, payload, history);
                return result as T;
            } catch (fallbackError: unknown) {
                throw new AppError((fallbackError instanceof Error ? fallbackError.message : String(fallbackError)) || "Echec du Worker Local", "WORKER_FALLBACK_ERROR", "high");
            }
        }
    }
}

export const workerService = new WorkerService();
