import React, { useState, useMemo } from "react";
import type {
  ForensicReport,
  ForensicEvidence,
  PredictionFeedback,
} from "../types";
import { logError, AppError } from "../utils/AppError";
import { NumberBall } from "./NumberBall";
import { deleteForensicReportLocal } from "../services/postPredictionAnalysisService";
import { deleteForensicReportCloud } from "../services/syncService";
import {
  updatePredictionFeedback,
  deletePrediction,
} from "../services/predictionHistoryService";
import { isSupabaseConfigured } from "../services/supabaseClient";
import { apiClient } from "../core/api/apiClient";
import { useToast } from "./ui/Toast";
import { applyOnlineLearning } from "../services/trainingService";
import { useNexusStore } from "../store/useNexusStore";
import { applyBayesianForensicFeedback } from "../services/prediction/weightsManager";
import { Forensic3DRadar } from "./Forensic3DRadar";
import { audioEngine } from "../utils/audioEngine";
import {
  ThumbsUp,
  ThumbsDown,
  Meh,
  CheckCircle2,
  MessageSquare,
  X as XIcon,
  AlertOctagon,
  ScanLine,
  GitMerge,
  Microscope,
  ArrowRight,
  Activity,
  // @ts-ignore - auto generated by cleanup
  PlayCircle,
  LayoutGrid,
  AlertTriangle,
  Trash2,
  Cpu,
  Sparkles,
  Waves,
  Lightbulb,
  } from "lucide-react";




interface PredictionForensicsProps {
  report: ForensicReport;
  onClose: () => void;
}

export const PredictionForensics: React.FC<PredictionForensicsProps> = ({
  report,
  onClose,
}) => {
  const { showToast } = useToast();
  const globalWeights = useNexusStore((state) => state.globalWeights);

  const [activeTab, setActiveTab] = useState<
    "spatial" | "ballistic" | "autopsy" | "metrics" | "counterfactuals" | "spectral" | "xap" | "radar3d"
  >("radar3d");
      const [submittingFeedback, setSubmittingFeedback] = useState(false);
  const [feedbackSent, setFeedbackSent] = useState(false);
  const [userRating, setUserRating] = useState<
    PredictionFeedback["userRating"] | null
  >(null);
  const [userComment, setUserComment] = useState("");

  
  
  const handleDeleteReport = async () => {
    if (
      !confirm(
        "Voulez-vous vraiment supprimer définitivement ce rapport d'analyse post-mortem (Action irréversible) ?",
      )
    )
      return;
    try {
      if (report.id) {
        await deleteForensicReportLocal(report.id);
        await deleteForensicReportCloud(report.id);
        if (report.predictionId) {
          await deletePrediction(report.predictionId);
        }
        showToast("Rapport Forensic supprimé avec succès", "success");
        onClose(); // Automatically close since it's deleted
      }
    } catch (e) {
      logError(
        new AppError(
          "Failed to delete forensic report",
          "FORENSIC_DELETE_ERROR",
          "low",
          { error: e },
        ),
      );
      showToast("Erreur lors de la suppression du rapport", "error");
    }
  };

  
  const handleSubmitFeedback = async () => {
    if (!report.predictionId || !userRating) return;
    audioEngine.play("click");
    setSubmittingFeedback(true);
    try {
      await updatePredictionFeedback(report.predictionId, {
        keyLearning:
          userRating === "Visionnaire"
            ? "Résonance validée"
            : "Décalage structurel",
        userRating,
        userComment,
      });

      if (isSupabaseConfigured()) {
        await apiClient.post("process-rlhf", {
          predictionId: report.predictionId,
          rating: userRating,
          drawName: report.drawName,
          actualHits: report.matches.filter((m) => m.errorType === "Hit")
            .length,
          user_comment: userComment,
        });
      }

      // Online Learning Application locally
      const feedbackScore = userRating === "Visionnaire" ? 1.0 : (userRating === "Incohérente" ? -1.0 : 0.0);
      const history = useNexusStore.getState().history;
      await applyOnlineLearning(report.drawName, history, feedbackScore);

      // Appliquer le feedback Bayesien direct sur les poids d'algorithmes locaux associé au rapport forensic
      const updatedWeights = await applyBayesianForensicFeedback(report.drawName, report, userRating);
      
      // Mettre à jour le store global
      const { updateGlobalWeights } = useNexusStore.getState();
      await updateGlobalWeights(updatedWeights, report.drawName);

      setFeedbackSent(true);
      audioEngine.play("success");
      showToast("Signal RL envoyé au Cloud.", "success");
    } catch (e) {
      audioEngine.play("error");
      showToast("Feedback sauvegardé localement.", "info");
      setFeedbackSent(true);
    } finally {
      setSubmittingFeedback(false);
    }
  };

  

  
  
  const spatialGridData = useMemo(() => {
    const predicted = new Set<number>();
    const actualSet = new Set<number>();
    const misses = new Set<number>();

    if (Array.isArray(report.matches)) {
      report.matches.forEach((m) => {
        if (m.predicted) predicted.add(m.predicted);
        if (m.errorType === "Hit" && m.actual) actualSet.add(m.actual);
      });
    }

    if (report.missedOpportunities) {
      report.missedOpportunities.forEach((m) => {
        actualSet.add(m.number);
        misses.add(m.number);
      });
    }

    const grid = [];
    for (let i = 1; i <= 90; i++) {
      grid.push({
        num: i,
        isPredicted: predicted.has(i),
        isActual: actualSet.has(i),
        isMissed: misses.has(i),
      });
    }
    return grid;
  }, [report]);

  const getBadgeColor = (type: ForensicEvidence["errorType"]) => {
    switch (type) {
      case "Hit":
        return "bg-emerald-100 text-emerald-800 border-emerald-300 dark:bg-emerald-900/40 dark:text-emerald-300 dark:border-emerald-700";
      case "Voisin":
        return "bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-900/40 dark:text-blue-300 dark:border-blue-700";
      case "Miroir":
        return "bg-purple-100 text-purple-800 border-purple-300 dark:bg-purple-900/40 dark:text-purple-300 dark:border-purple-700";
      case "Shadow":
        return "bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-900/40 dark:text-amber-300 dark:border-amber-700";
      case "Machine":
        return "bg-cyan-100 text-cyan-800 border-cyan-300 dark:bg-cyan-900/40 dark:text-cyan-300 dark:border-cyan-700";
      default:
        return "bg-red-50 text-red-600 border-red-200 dark:bg-red-900/20 dark:text-red-400 dark:border-red-800";
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-950/90 backdrop-blur-md animate-fade-in">
      <div className="bg-white dark:bg-slate-900 w-full max-w-5xl max-h-[90vh] rounded-3xl shadow-2xl flex flex-col overflow-hidden border border-slate-200 dark:border-slate-800 relative">
        {/* Header */}
        <div className="p-6 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-indigo-500 rounded-2xl text-white shadow-lg shadow-indigo-500/30">
              <Microscope size={28} />
            </div>
            <div>
              <h3 className="text-2xl font-black text-slate-800 dark:text-white uppercase tracking-tighter">
                Forensic Hub
              </h3>
              <div className="flex flex-wrap gap-2 mt-1">
                <p className="text-[10px] font-bold text-slate-500 dark:text-slate-400 flex items-center gap-2 flex-wrap">
                  Tirage {report.drawName} • {report.date}
                  {report.rmse !== undefined && (
                    <span className="text-xs px-2 py-0.5 rounded bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">
                      RMSE: {report.rmse.toFixed(2)}
                    </span>
                  )}
                  {report.continuousTopologicalLoss !== undefined && (
                    <span className="text-xs px-2 py-0.5 rounded bg-pink-100 dark:bg-pink-900/30 text-pink-600 dark:text-pink-400 border border-pink-300 dark:border-pink-800">
                      Topologie: {report.continuousTopologicalLoss.toFixed(3)}
                    </span>
                  )}
                  {report.brier_score !== undefined && (
                    <span className="text-xs px-2 py-0.5 rounded bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">
                      Brier: {report.brier_score.toFixed(3)}
                    </span>
                  )}
                  {report.kl_divergence !== undefined && (
                    <span className="text-xs px-2 py-0.5 rounded bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">
                      KL-Div: {report.kl_divergence.toFixed(3)}
                    </span>
                  )}
                  {report.shannon_entropy !== undefined && (
                    <span className="text-xs px-2 py-0.5 rounded bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">
                      Entropy: {report.shannon_entropy.toFixed(2)} bits
                    </span>
                  )}
                  {report.benfordCompliance !== undefined && (
                    <span className="text-xs px-2 py-0.5 rounded bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">
                      Benford: {(report.benfordCompliance * 100).toFixed(1)}%
                    </span>
                  )}
                  {report.entropyCollapse && (
                    <span className="text-xs px-2 py-0.5 rounded bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 border border-red-300 dark:border-red-800 flex items-center gap-1 font-bold">
                      <AlertTriangle size={10} /> Effondrement Entropique
                    </span>
                  )}
                  {report.isBlackSwan && (
                    <span className="text-xs px-2 py-0.5 rounded bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 border border-amber-400 dark:border-amber-700 flex items-center gap-1 font-bold">
                      <AlertTriangle size={10} /> Cygne Noir
                    </span>
                  )}
                </p>
                {report.matches.filter((m) => m.errorType === "Voisin").length >
                  0 && (
                  <span className="bg-blue-100 text-blue-800 border border-blue-200 px-2 rounded text-xs font-black uppercase flex items-center gap-1">
                    <GitMerge size={10} />{" "}
                    {
                      report.matches.filter((m) => m.errorType === "Voisin")
                        .length
                    }{" "}
                    Voisins
                  </span>
                )}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-3 sm:grid-cols-4 md:flex md:flex-wrap bg-slate-100 dark:bg-slate-950 p-1.5 rounded-2xl max-w-full md:max-w-2xl gap-1.5 justify-center">
            {[
              { id: "radar3d", label: "Radar 3D", color: "text-fuchsia-500 dark:text-fuchsia-400" },
              { id: "spatial", label: "Spatial", color: "text-amber-500 dark:text-amber-400" },
              { id: "ballistic", label: "Balistique", color: "text-indigo-600 dark:text-indigo-400" },
              { id: "autopsy", label: "Autopsie IA", color: "text-purple-600 dark:text-purple-400" },
              { id: "metrics", label: "Métriques", color: "text-rose-600 dark:text-rose-400" },
              { id: "counterfactuals", label: "Contre-Factuels", color: "text-emerald-600 dark:text-emerald-400" },
              { id: "spectral", label: "Spectral", color: "text-cyan-600 dark:text-cyan-400" },
              { id: "xap", label: "XAP / ADN", color: "text-blue-600 dark:text-blue-400" }
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => {
                  audioEngine.play("click");
                  setActiveTab(tab.id as any);
                }}
                className={`px-3 py-2 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all whitespace-nowrap flex-1 text-center min-w-[80px] ${
                  activeTab === tab.id
                    ? `bg-white dark:bg-slate-800 shadow ${tab.color}`
                    : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleDeleteReport();
              }}
              title="Supprimer définitivement ce rapport"
              className="p-3 bg-white dark:bg-slate-800 rounded-full hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-500 text-slate-400 transition shadow-sm border border-slate-200 dark:border-slate-700"
            >
              <Trash2 size={20} />
            </button>
            <button
              onClick={() => {
                audioEngine.play("click");
                onClose();
              }}
              className="p-3 bg-white dark:bg-slate-800 rounded-full hover:bg-rose-50 dark:hover:bg-rose-900/20 hover:text-rose-500 transition shadow-sm border border-slate-200 dark:border-slate-700"
            >
              <XIcon size={20} />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto custom-scrollbar p-6 md:p-8 space-y-10 bg-slate-50/50 dark:bg-slate-900/50">
          {activeTab === "radar3d" && (
            <div className="animate-slide-up space-y-6">
              <Forensic3DRadar report={report} globalWeights={globalWeights} />
            </div>
          )}

          {activeTab === "spatial" && (
            <div className="animate-slide-up space-y-6">
              <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden relative">
                <div className="absolute top-0 right-0 p-8 opacity-5">
                  <LayoutGrid size={150} />
                </div>
                <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-6 relative z-10">
                  <LayoutGrid size={18} className="text-amber-500" />{" "}
                  Cartographie des Impacts (Spatial Analysis)
                </h4>

                <div className="grid grid-cols-10 gap-2 relative z-10">
                  {spatialGridData.map((cell) => {
                    let bgClass =
                      "bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-600 border border-slate-200 dark:border-slate-700/50";

                    if (cell.isPredicted && cell.isActual) {
                      bgClass =
                        "bg-emerald-500 text-white shadow-lg shadow-emerald-500/30 scale-110 z-10 font-black border-2 border-emerald-300 dark:border-emerald-400";
                    } else if (cell.isPredicted && !cell.isActual) {
                      bgClass =
                        "bg-indigo-500 text-white shadow-md font-bold opacity-80 border border-indigo-400";
                    } else if (!cell.isPredicted && cell.isMissed) {
                      bgClass =
                        "bg-rose-500 text-white shadow-lg shadow-rose-500/30 font-black border border-rose-400 scale-105";
                    }

                    return (
                      <div
                        key={cell.num}
                        className={`aspect-square rounded-lg md:rounded-xl flex items-center justify-center text-xs md:text-sm transition-all duration-300 ${bgClass}`}
                      >
                        {cell.num}
                      </div>
                    );
                  })}
                </div>

                <div className="flex flex-wrap gap-4 mt-8 justify-center p-4 bg-slate-50 dark:bg-black/20 rounded-2xl border border-slate-100 dark:border-white/5 relative z-10">
                  <div className="flex items-center gap-2 text-[10px] font-bold text-slate-600 dark:text-slate-300 uppercase">
                    <div className="w-3 h-3 bg-emerald-500 rounded-sm"></div>{" "}
                    Impact Direct (Hit)
                  </div>
                  <div className="flex items-center gap-2 text-[10px] font-bold text-slate-600 dark:text-slate-300 uppercase">
                    <div className="w-3 h-3 bg-indigo-500 rounded-sm"></div>{" "}
                    Zone Prédite (Vide)
                  </div>
                  <div className="flex items-center gap-2 text-[10px] font-bold text-slate-600 dark:text-slate-300 uppercase">
                    <div className="w-3 h-3 bg-rose-500 rounded-sm"></div>{" "}
                    Anomalie Non-Détectée (Miss)
                  </div>
                </div>
              </div>

              {/* NOUVEAU: TOPOLOGIE DE RUPTURE & THEORIE DES CATASTROPHES */}
              <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl relative animate-slide-up">
                <div className="absolute top-4 right-4 text-[9px] font-mono opacity-25 text-slate-500">
                  MODÈLE: FRONCE DE RENE THOM (CUSP)
                </div>

                <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-6">
                  <Activity size={18} className="text-rose-500" /> La Topologie
                  de Rupture (Tensions Spatiales & Catastrophes)
                </h4>

                <p className="text-xs text-slate-500 dark:text-slate-400 mb-8 leading-relaxed">
                  Cette analyse modélise la distribution spatiale des tirages
                  sur la grille de 90 nombres sous l'angle de la{" "}
                  <strong>Théorie des Catastrophes de René Thom</strong>. Les
                  tensions géométriques et la dérive gravitationnelle
                  déterminent d'éventuels glissements de phase et instabilités
                  structurelles dans la stochastique du jeu.
                </p>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
                  {/* Gauge & Metrics Panel */}
                  <div className="lg:col-span-7 space-y-6">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {/* Circle Gauge for Topological Tension */}
                      <div className="p-5 bg-slate-50 dark:bg-black/20 rounded-2xl border border-slate-100 dark:border-white/5 flex items-center gap-4">
                        <div className="relative w-16 h-16 flex-shrink-0">
                          <svg
                            className="w-full h-full transform -rotate-90"
                            viewBox="0 0 36 36"
                          >
                            <path
                              className="text-slate-200 dark:text-slate-800"
                              strokeWidth="3.5"
                              stroke="currentColor"
                              fill="none"
                              d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                            <path
                              className={`transition-all duration-1000 ${
                                (report.topologicalTensionIndex ?? 25) > 55
                                  ? "text-rose-500"
                                  : (report.topologicalTensionIndex ?? 25) > 35
                                    ? "text-amber-500"
                                    : "text-indigo-500"
                              }`}
                              strokeDasharray={`${report.topologicalTensionIndex ?? 25}, 100`}
                              strokeWidth="3.5"
                              strokeLinecap="round"
                              stroke="currentColor"
                              fill="none"
                              d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                          </svg>
                          <div className="absolute inset-0 flex items-center justify-center text-xs font-black text-slate-800 dark:text-white">
                            {report.topologicalTensionIndex ?? 25}%
                          </div>
                        </div>
                        <div>
                          <span className="text-[10px] font-black uppercase text-slate-400 dark:text-slate-500 block">
                            Tension Topologique
                          </span>
                          <span className="text-xs font-bold text-slate-700 dark:text-slate-200">
                            {(report.topologicalTensionIndex ?? 25) > 55
                              ? "Haute Compression"
                              : (report.topologicalTensionIndex ?? 25) > 35
                                ? "Instabilité Modérée"
                                : "Équilibre Fluide"}
                          </span>
                        </div>
                      </div>

                      {/* René Thom Regime Status */}
                      <div className="p-5 bg-slate-50 dark:bg-black/20 rounded-2xl border border-slate-100 dark:border-white/5 flex flex-col justify-center">
                        <span className="text-[10px] font-black uppercase text-slate-400 dark:text-slate-500">
                          Régime Topologique
                        </span>
                        <div className="mt-1 flex items-center gap-2">
                          <span
                            className={`w-3 h-3 rounded-full animate-pulse ${
                              (report.catastropheControlParams?.regime ??
                                "STABLE_MONOSTABLE") === "BIFURCATION_ACTIVE"
                                ? "bg-rose-500"
                                : (report.catastropheControlParams?.regime ??
                                      "STABLE_MONOSTABLE") ===
                                    "CRITICAL_TENSION"
                                  ? "bg-amber-500"
                                  : "bg-emerald-500"
                            }`}
                          />
                          <span className="text-xs font-black uppercase tracking-wider text-slate-800 dark:text-white">
                            {(
                              report.catastropheControlParams?.regime ??
                              "STABLE_MONOSTABLE"
                            ).replace("_", " ")}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Table of René Thom System Parameters */}
                    <div className="rounded-2xl border border-slate-100 dark:border-white/5 overflow-hidden">
                      <table className="w-full text-left border-collapse text-xs">
                        <thead>
                          <tr className="bg-slate-50 dark:bg-black/30 text-[10px] font-black text-slate-400 dark:text-slate-500 tracking-wider uppercase">
                            <th className="p-3 pl-4">Variable du Système</th>
                            <th className="p-3">Symbole</th>
                            <th className="p-3 text-right pr-4">
                              Valeur Mesurée
                            </th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-white/5">
                          <tr>
                            <td className="p-3 pl-4 font-semibold text-slate-700 dark:text-slate-300">
                              Paramètre de Bifurcation (Compression)
                            </td>
                            <td className="p-3 font-mono text-indigo-500 font-bold">
                              a
                            </td>
                            <td className="p-3 font-mono text-right pr-4 text-slate-800 dark:text-slate-200">
                              {(
                                report.catastropheControlParams?.a ?? 1.2
                              ).toFixed(4)}
                            </td>
                          </tr>
                          <tr>
                            <td className="p-3 pl-4 font-semibold text-slate-700 dark:text-slate-300">
                              Asymétrie de Dérive Gravitationnelle
                            </td>
                            <td className="p-3 font-mono text-indigo-500 font-bold">
                              b
                            </td>
                            <td className="p-3 font-mono text-right pr-4 text-slate-800 dark:text-slate-200">
                              {(
                                report.catastropheControlParams?.b ?? 0.35
                              ).toFixed(4)}
                            </td>
                          </tr>
                          <tr className="bg-slate-50/50 dark:bg-black/10">
                            <td className="p-3 pl-4 font-bold text-slate-800 dark:text-white flex items-center gap-1.5">
                              Discriminant de la Fronce (Bistabilité)
                              {(report.catastropheControlParams?.discriminant ??
                                2.5) <= 0 && (
                                <AlertTriangle
                                  size={12}
                                  className="text-rose-500"
                                />
                              )}
                            </td>
                            <td className="p-3 font-mono text-rose-500 font-black">
                              Δ
                            </td>
                            <td className="p-3 font-mono font-black text-right pr-4 text-slate-800 dark:text-white">
                              {(
                                report.catastropheControlParams?.discriminant ??
                                2.5
                              ).toFixed(4)}
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>

                  {/* Cusp Plot visualization (Right coordinate space) */}
                  <div className="lg:col-span-5 flex flex-col items-center">
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 dark:text-slate-500 mb-3 block">
                      Espace des Phases de René Thom
                    </span>
                    <div className="relative w-full max-w-[240px] aspect-square bg-slate-50 dark:bg-black/30 border border-slate-100 dark:border-white/5 rounded-3xl p-4 flex items-center justify-center">
                      <svg
                        className="w-full h-full text-slate-400"
                        viewBox="0 0 200 200"
                      >
                        {/* Shaded Cusp Zone (Bistable bifurcated phase where 4a^3 + 27b^2 <= 0) */}
                        {(() => {
                          const pointsUpper: string[] = [];
                          const pointsLower: string[] = [];
                          // Note: Cusp region is only defined for a <= 0, so coordinate-wise x <= 100 on our 200px plot
                          for (let aVal = 0; aVal >= -5.0; aVal -= 0.25) {
                            const bVal = 0.3849 * Math.pow(-aVal, 1.5);
                            pointsUpper.push(
                              `${100 + aVal * 15},${100 - bVal * 15}`,
                            );
                            pointsLower.unshift(
                              `${100 + aVal * 15},${100 + bVal * 15}`,
                            );
                          }
                          const pathStr = `M 100,100 L ${pointsUpper.join(" L ")} L ${pointsLower.join(" L ")} Z`;
                          return (
                            <path
                              d={pathStr}
                              fill="url(#forensic-cusp-gradient)"
                              className="stroke-rose-500/30 stroke-2 opacity-80"
                            />
                          );
                        })()}

                        {/* Defining Gradients */}
                        <defs>
                          <radialGradient
                            id="forensic-cusp-gradient"
                            cx="30%"
                            cy="50%"
                            r="60%"
                          >
                            <stop
                              offset="0%"
                              stopColor="#f43f5e"
                              stopOpacity="0.25"
                            />
                            <stop
                              offset="100%"
                              stopColor="#f43f5e"
                              stopOpacity="0.03"
                            />
                          </radialGradient>
                        </defs>

                        {/* Coordinate axes */}
                        <line
                          x1="20"
                          y1="100"
                          x2="180"
                          y2="100"
                          className="stroke-slate-300 dark:stroke-slate-700 stroke-1"
                          strokeDasharray="3,3"
                        />
                        <line
                          x1="100"
                          y1="20"
                          x2="100"
                          y2="180"
                          className="stroke-slate-300 dark:stroke-slate-700 stroke-1"
                          strokeDasharray="3,3"
                        />

                        {/* Node trajectory boundaries */}
                        <text
                          x="170"
                          y="94"
                          className="text-[8px] font-mono fill-slate-400 font-bold"
                        >
                          a
                        </text>
                        <text
                          x="105"
                          y="27"
                          className="text-[8px] font-mono fill-slate-400 font-bold"
                        >
                          b
                        </text>

                        {/* Chart label pointers */}
                        <text
                          x="45"
                          y="115"
                          className="text-[6px] font-mono fill-rose-500/60 font-black tracking-tighter"
                        >
                          BISTABILITÉ (Δ ≤ 0)
                        </text>
                        <text
                          x="110"
                          y="170"
                          className="text-[6px] font-mono fill-indigo-500/60 font-black tracking-tighter"
                        >
                          ÉQUILIBRE (Δ &gt; 0)
                        </text>

                        {/* Pulsing Active State Coordinate Node */}
                        {(() => {
                          const aVal =
                            report.catastropheControlParams?.a ?? 1.2;
                          const bVal =
                            report.catastropheControlParams?.b ?? 0.35;
                          // Bound dot to graph ranges
                          const rawX = 100 + aVal * 15;
                          const rawY = 100 - bVal * 15;
                          const dotX = Math.min(185, Math.max(15, rawX));
                          const dotY = Math.min(185, Math.max(15, rawY));

                          const activeColor =
                            (report.catastropheControlParams?.regime ??
                              "STABLE_MONOSTABLE") === "BIFURCATION_ACTIVE"
                              ? "fill-rose-500"
                              : (report.catastropheControlParams?.regime ??
                                    "STABLE_MONOSTABLE") === "CRITICAL_TENSION"
                                ? "fill-amber-500"
                                : "fill-indigo-500";

                          return (
                            <g>
                              <circle
                                cx={dotX}
                                cy={dotY}
                                r="7"
                                className={`${activeColor} opacity-25 animate-ping`}
                              />
                              <circle
                                cx={dotX}
                                cy={dotY}
                                r="4"
                                className={activeColor}
                                stroke="#ffffff"
                                strokeWidth="1.5"
                              />
                            </g>
                          );
                        })()}
                      </svg>
                    </div>

                    <div className="flex gap-4 mt-4 justify-center">
                      <div className="flex items-center gap-1.5 text-[8px] font-bold text-slate-500 uppercase">
                        <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full" />{" "}
                        Monostable
                      </div>
                      <div className="flex items-center gap-1.5 text-[8px] font-bold text-slate-500 uppercase">
                        <span className="w-1.5 h-1.5 bg-rose-500 rounded-full" />{" "}
                        Rupture (Bifurcation)
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === "ballistic" && (
            <div className="animate-slide-up space-y-8">
              {/* Balistique */}
              <section className="bg-white dark:bg-slate-950/50 rounded-2xl p-8 border border-slate-200 dark:border-slate-800 shadow-sm relative overflow-hidden">
                <h4 className="font-black text-slate-400 dark:text-slate-500 mb-8 uppercase text-xs tracking-[0.3em] text-center flex items-center justify-center gap-2">
                  <ScanLine size={14} /> Trajectoire Vectorielle
                </h4>

                <div className="relative flex flex-col md:flex-row justify-between items-center gap-6 md:gap-20">
                  <div className="flex flex-col gap-4 items-center z-10 w-full md:w-auto">
                    <span className="text-xs font-black text-indigo-500 uppercase bg-indigo-50 dark:bg-indigo-900/20 px-3 py-1 rounded-full">
                      Prédiction IA
                    </span>
                    <div className="flex flex-wrap md:flex-col gap-3 justify-center">
                      {Array.isArray(report.matches) ? (
                        report.matches.map((m, i) => (
                          <div key={`pred-${i}`} className="relative group">
                            <NumberBall
                              number={m.predicted}
                              size="md"
                              glow={m.errorType === "Hit"}
                            />
                            {m.errorType !== "Hit" &&
                              m.errorType !== "None" && (
                                <div
                                  className={`absolute -bottom-6 left-1/2 -translate-x-1/2 text-[10px] font-bold whitespace-nowrap transition-opacity ${m.errorType === "Voisin" ? "opacity-100 text-blue-500" : "opacity-0 group-hover:opacity-100 text-slate-400"}`}
                                >
                                  {m.errorType} ({m.delta})
                                </div>
                              )}
                          </div>
                        ))
                      ) : (
                        <div className="text-center text-slate-400 text-xs font-bold">
                          {report.matches} Hits Exacts
                        </div>
                      )}

                      {/* LES MANQUEMENTS (Empty slots for prediction) */}
                      {report.missedOpportunities &&
                        report.missedOpportunities.length > 0 && (
                          <div className="mt-4 pt-4 border-t border-transparent flex flex-col gap-3 items-center">
                            <span className="text-[10px] font-black text-transparent uppercase">
                              Manquements
                            </span>
                            {report.missedOpportunities.map((_, i) => (
                              <div
                                key={`empty-pred-${i}`}
                                className="w-12 h-12 rounded-full border-2 border-dashed border-rose-200 dark:border-rose-900/30 flex items-center justify-center text-rose-300 dark:text-rose-800 font-bold"
                              >
                                X
                              </div>
                            ))}
                          </div>
                        )}
                    </div>
                  </div>

                  <div className="hidden md:flex flex-col items-center gap-2 opacity-30 flex-1">
                    <ArrowRight size={24} className="text-slate-400" />
                    <div className="h-px w-full bg-gradient-to-r from-transparent via-slate-400 to-transparent"></div>
                    <span className="text-xs font-mono text-slate-500">
                      MAPPING
                    </span>
                  </div>

                  <div className="flex flex-col gap-4 items-center z-10 w-full md:w-auto">
                    <span className="text-xs font-black text-emerald-500 uppercase bg-emerald-50 dark:bg-emerald-900/20 px-3 py-1 rounded-full">
                      Résultat Réel
                    </span>
                    <div className="flex flex-wrap md:flex-col gap-3 justify-center">
                      {Array.isArray(report.matches) ? (
                        report.matches.map((m, i) => (
                          <div key={`act-${i}`} className="relative">
                            {m.actual !== null ? (
                              <div className="relative">
                                <NumberBall number={m.actual} size="md" />
                                <div
                                  className={`absolute -top-2 -right-2 px-2 py-0.5 rounded-full text-[10px] font-black uppercase border ${getBadgeColor(m.errorType)}`}
                                >
                                  {m.errorType === "None"
                                    ? "Miss"
                                    : m.errorType}
                                </div>
                              </div>
                            ) : (
                              <div className="w-12 h-12 rounded-full border-2 border-dashed border-slate-300 flex items-center justify-center text-slate-300 font-bold">
                                ?
                              </div>
                            )}
                          </div>
                        ))
                      ) : (
                        <div className="text-center text-slate-400 text-xs font-bold">
                          {report.nearMisses?.length || 0} Proches
                        </div>
                      )}

                      {/* LES MANQUEMENTS */}
                      {report.missedOpportunities &&
                        report.missedOpportunities.length > 0 && (
                          <div className="mt-4 pt-4 border-t border-slate-200 dark:border-slate-700 flex flex-col gap-3 items-center">
                            <span className="text-[10px] font-black text-rose-500 uppercase">
                              Manquements
                            </span>
                            {report.missedOpportunities.map((miss, i) => (
                              <div key={`miss-${i}`} className="relative">
                                <NumberBall number={miss.number} size="md" />
                                <div className="absolute -top-2 -right-2 px-2 py-0.5 rounded-full text-[10px] font-black uppercase border bg-rose-100 text-rose-800 border-rose-300 dark:bg-rose-900/40 dark:text-rose-300 dark:border-rose-700">
                                  Oubli
                                </div>
                              </div>
                            ))}
                          </div>
                        )}
                    </div>
                  </div>
                </div>
              </section>

              <div className="grid md:grid-cols-2 gap-6">
                {/* Missed Opportunities (Manquements spectrauxe) */}
                {report.missedOpportunities &&
                  report.missedOpportunities.length > 0 && (
                    <section className="bg-slate-50 dark:bg-slate-950/45 border border-slate-200 dark:border-slate-800/80 p-6 rounded-[2rem] shadow-xl relative overflow-hidden group">
                      <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(245,158,11,0.03)_50%,transparent_75%,transparent_100%)] bg-[length:20px_20px] pointer-events-none"></div>
                      <h4 className="font-black text-slate-800 dark:text-slate-200 mb-5 uppercase text-[10px] tracking-[0.2em] flex items-center gap-2">
                        <AlertOctagon
                          size={14}
                          className="text-amber-500 animate-pulse"
                        />{" "}
                        Dissonance Spectrale (Signaux Manqués)
                      </h4>
                      <div className="space-y-4 relative z-10">
                        {report.missedOpportunities.map((miss, idx) => {
                          const isStrong = miss.reason.includes("z=");
                          return (
                            <div
                              key={idx}
                              className={`relative overflow-hidden p-4 rounded-2xl flex flex-col gap-3 transition-colors ${isStrong ? "bg-amber-500/10 border border-amber-500/20" : "bg-white/5 border border-slate-200 dark:border-white/5"}`}
                            >
                              {isStrong && (
                                <div className="absolute top-0 right-0 w-16 h-16 bg-amber-500/20 blur-2xl rounded-full mix-blend-screen pointer-events-none"></div>
                              )}
                              <div className="flex items-center gap-4">
                                <div className="shrink-0 bg-black/40 p-2 rounded-full border border-white/10 shadow-inner">
                                  <NumberBall number={miss.number} size="sm" />
                                </div>
                                <div className="flex-1">
                                  <div className="text-xs font-mono font-bold text-amber-500 dark:text-amber-400 mb-1">
                                    Numéro {miss.number}{" "}
                                    {isStrong && (
                                      <span className="ml-2 text-[9px] px-1.5 py-0.5 rounded bg-amber-500/20 text-amber-600 dark:text-amber-300 border border-amber-500/30 uppercase tracking-widest font-black">
                                        Anomalie Signal
                                      </span>
                                    )}
                                  </div>
                                  <div className="text-[10px] text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
                                    {miss.reason}
                                  </div>
                                </div>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </section>
                  )}

                {/* Algorithm Drift */}
                <section className="bg-slate-50 dark:bg-slate-950/45 border border-slate-200 dark:border-slate-800/80 p-6 rounded-[2rem] shadow-xl relative overflow-hidden">
                  <h4 className="font-black text-slate-800 dark:text-slate-200 mb-5 uppercase text-[10px] tracking-[0.2em] flex items-center gap-2">
                    <Activity size={14} className="text-indigo-500 dark:text-indigo-400" /> Flux de
                    Dérive Algorithmique
                  </h4>
                  <div className="space-y-5">
                    {Array.isArray(report.algorithmicDrift) &&
                    report.algorithmicDrift.length > 0 ? (
                      report.algorithmicDrift.map((drift, i) => {
                        const driftVal = Math.min(100, drift.driftScore);
                        return (
                          <div key={i} className="flex flex-col gap-2">
                            <div className="flex justify-between items-center">
                              <span className="text-[10px] uppercase tracking-widest font-bold text-slate-700 dark:text-slate-300">
                                {drift.algo.replace(/_/g, " ")}
                              </span>
                              <span
                                className={`text-[9px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full border ${
                                  drift.direction === "overestimating"
                                    ? "bg-rose-500/10 text-rose-500 dark:text-rose-400 border-rose-500/20"
                                    : "bg-emerald-500/10 text-emerald-500 dark:text-emerald-400 border-emerald-500/20"
                                }`}
                              >
                                {drift.direction === "overestimating"
                                  ? "Surestimation (Entropie)"
                                  : "Sous-estimation (Omission)"}
                              </span>
                            </div>
                            <div className="flex items-center gap-3">
                              <div className="flex-1 h-1 bg-slate-200 dark:bg-slate-850 rounded-full overflow-hidden flex relative">
                                {drift.direction === "overestimating" ? (
                                  <div
                                    className="absolute right-0 h-full bg-gradient-to-l from-rose-500 to-transparent"
                                    style={{ width: `${driftVal}%` }}
                                  />
                                ) : (
                                  <div
                                    className="absolute left-0 h-full bg-gradient-to-r from-emerald-500 to-transparent"
                                    style={{ width: `${driftVal}%` }}
                                  />
                                )}
                              </div>
                              <span
                                className={`font-mono text-xs font-black ${
                                  drift.direction === "overestimating"
                                    ? "text-rose-500 dark:text-rose-400"
                                    : "text-emerald-500 dark:text-emerald-400"
                                }`}
                              >
                                {Math.round(driftVal)}%
                              </span>
                            </div>
                          </div>
                        );
                      })
                    ) : Array.isArray(report.scoreDivergence) &&
                      report.scoreDivergence.length > 0 ? (
                      report.scoreDivergence.map((div, i) => (
                        <div
                          key={i}
                          className="flex justify-between items-center text-xs"
                        >
                          <span className="font-bold text-slate-600 dark:text-slate-400 capitalize">
                            {div.algo}
                          </span>
                          <div className="flex items-center gap-2">
                            <div className="w-24 h-1.5 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden">
                              <div
                                className="h-full bg-indigo-500"
                                style={{ width: `${div.impact}%` }}
                              ></div>
                            </div>
                            <span className="font-mono font-black text-indigo-500">
                              {Math.round(div.impact)}%
                            </span>
                          </div>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-400 italic">
                        Aucune divergence algorithmique détaillée.
                      </p>
                    )}
                  </div>
                </section>

                {/* Near Misses Corrections */}
                {Array.isArray(report.matches) &&
                  report.matches.filter((m) =>
                    ["Voisin", "Miroir", "Shadow"].includes(m.errorType),
                  ).length > 0 && (
                    <section className="bg-white dark:bg-slate-800 p-6 rounded-[2rem] shadow-sm border border-slate-100 dark:border-slate-700 md:col-span-2 mt-2">
                      <h4 className="font-black text-slate-700 dark:text-slate-300 mb-4 uppercase text-xs tracking-widest flex items-center gap-2">
                        <Microscope size={14} className="text-purple-500" />{" "}
                        Diagnostic des Proximités (Near Misses)
                      </h4>
                      <div className="grid md:grid-cols-2 gap-4">
                        {report.matches
                          .filter((m) =>
                            ["Voisin", "Miroir", "Shadow"].includes(
                              m.errorType,
                            ),
                          )
                          .map((m, idx) => (
                            <div
                              key={idx}
                              className="bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700 p-4 rounded-2xl flex items-start gap-4"
                            >
                              <div className="flex flex-col items-center gap-1">
                                <NumberBall number={m.predicted} size="sm" />
                                <span className="text-[10px] font-black uppercase text-slate-400">
                                  Prédit
                                </span>
                              </div>
                              <div className="flex flex-col items-center justify-center pt-2">
                                <ArrowRight
                                  size={14}
                                  className="text-slate-400"
                                />
                              </div>
                              <div className="flex flex-col items-center gap-1">
                                <NumberBall number={m.actual!} size="sm" />
                                <span
                                  className={`text-[10px] font-black uppercase ${m.errorType === "Voisin" ? "text-blue-500" : m.errorType === "Miroir" ? "text-purple-500" : "text-amber-500"}`}
                                >
                                  {m.errorType}
                                </span>
                              </div>
                              <div className="flex-1 mt-1 ml-2">
                                <p className="text-[10px] font-medium text-slate-600 dark:text-slate-400 leading-tight">
                                  {m.suggestedCorrection ||
                                    "Bruit mesuré. Aucune correction spécifique à isoler."}
                                </p>
                              </div>
                            </div>
                          ))}
                      </div>
                    </section>
                  )}
              </div>
            </div>
          )}

          {activeTab === "autopsy" && (
            <div className="animate-slide-up space-y-6">
              <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl relative">
                <div className="absolute top-4 right-4 flex items-center gap-2">
                  {report.modelUsed && (
                    <span className="text-[10px] font-mono font-bold bg-slate-100 dark:bg-slate-800 text-slate-500 px-2 py-0.5 rounded border border-slate-200 dark:border-slate-700">
                      MODÈLE: {report.modelUsed}
                    </span>
                  )}
                  {report.isBlackSwan && (
                    <span className="text-[10px] font-black uppercase tracking-wider bg-rose-500 text-white px-2.5 py-0.5 rounded-full animate-pulse shadow-md shadow-rose-500/20">
                      ⚠️ Cygne Noir Détecté
                    </span>
                  )}
                </div>

                <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-6">
                  <Sparkles size={18} className="text-purple-500" />
                  Rapport d'Autopsie IA (Narratif Post-Mortem)
                </h4>

                <div className="p-6 bg-slate-50 dark:bg-black/20 rounded-2xl border border-slate-100 dark:border-white/5 mb-6">
                  <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed font-medium whitespace-pre-line">
                    {report.aiAnalysis || "Aucune analyse narrative disponible pour ce tirage."}
                  </p>
                </div>

                {report.recommendations && report.recommendations.length > 0 && (
                  <div className="space-y-4">
                    <h5 className="text-xs font-black uppercase text-slate-400 tracking-widest flex items-center gap-2">
                      <Lightbulb size={14} className="text-amber-500" />
                      Recommandations Stratégiques de l'Oracle
                    </h5>
                    <div className="grid gap-3">
                      {report.recommendations.map((rec, i) => (
                        <div key={i} className="flex items-start gap-3 p-4 bg-emerald-500/5 border border-emerald-500/10 rounded-xl">
                          <CheckCircle2 size={16} className="text-emerald-500 shrink-0 mt-0.5" />
                          <p className="text-xs text-slate-700 dark:text-slate-300 font-medium leading-relaxed">
                            {rec}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Near misses & Missed signals sub-section */}
              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-white dark:bg-slate-900 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 shadow-sm">
                  <h4 className="font-black text-slate-800 dark:text-slate-200 mb-4 uppercase text-xs tracking-widest flex items-center gap-2">
                    <Activity size={14} className="text-indigo-500" /> Near Misses (+/- 1 & Miroirs)
                  </h4>
                  <div className="space-y-3">
                    {report.nearMisses && report.nearMisses.length > 0 ? (
                      report.nearMisses.map((nm, idx) => (
                        <div key={idx} className="flex items-center justify-between p-3 bg-slate-50 dark:bg-black/25 border border-slate-100 dark:border-slate-800 rounded-xl font-mono text-xs">
                          <span className="text-slate-500">Prédiction {nm.predicted}</span>
                          <ArrowRight size={12} className="text-slate-400" />
                          <span className="text-indigo-500 font-bold">Réel {nm.actual} (dist. {nm.distance})</span>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-400 italic">Aucun near miss de premier ordre détecté.</p>
                    )}
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-900 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 shadow-sm">
                  <h4 className="font-black text-slate-800 dark:text-slate-200 mb-4 uppercase text-xs tracking-widest flex items-center gap-2">
                    <AlertTriangle size={14} className="text-amber-500" /> Anomalies Globales Manquées
                  </h4>
                  <div className="space-y-3">
                    {report.missedSignals && report.missedSignals.length > 0 ? (
                      report.missedSignals.map((ms, idx) => (
                        <div key={idx} className="p-3 bg-slate-50 dark:bg-black/25 border border-slate-100 dark:border-slate-800 rounded-xl text-xs flex justify-between items-center">
                          <div>
                            <span className="font-bold text-slate-700 dark:text-slate-300 block">{ms.pattern}</span>
                            <span className="text-[10px] text-slate-400 uppercase tracking-wider">{ms.type}</span>
                          </div>
                          <span className="text-xs font-mono font-black text-amber-500 bg-amber-500/10 px-2 py-0.5 rounded border border-amber-500/20">
                            Importance: {(ms.significance * 100).toFixed(0)}%
                          </span>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-400 italic">Aucune anomalie structurelle majeure ignorée.</p>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === "metrics" && (
            <div className="animate-slide-up space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {/* 1. RMSE Card */}
                <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-black uppercase text-indigo-500 tracking-widest block mb-1">Précision Globale</span>
                    <h4 className="text-xl font-black text-slate-800 dark:text-white uppercase tracking-tight mb-2">RMSE du Modèle</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                      Root Mean Square Error. Calcule la distance quadratique moyenne entre les scores assignés et les sorties réelles.
                    </p>
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-slate-800 dark:text-white font-mono">
                      {report.rmse !== undefined ? report.rmse.toFixed(3) : "N/A"}
                    </span>
                    <span className="text-xs font-bold text-slate-400">/ 100</span>
                  </div>
                </div>

                {/* 2. Brier Score Card */}
                <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-black uppercase text-rose-500 tracking-widest block mb-1">Fiabilité Probabiliste</span>
                    <h4 className="text-xl font-black text-slate-800 dark:text-white uppercase tracking-tight mb-2">Brier Score</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                      Mesure de calibration de probabilité (0 = perfection absolue, 0.25 = tirage purement uniforme sans aucun signal).
                    </p>
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-slate-800 dark:text-white font-mono">
                      {report.brier_score !== undefined ? report.brier_score.toFixed(4) : "N/A"}
                    </span>
                    <span className="text-xs font-bold text-slate-400">
                      {report.brier_score !== undefined && report.brier_score < 0.2 ? "Excellent" : "Bruit Élevé"}
                    </span>
                  </div>
                </div>

                {/* 3. KL Divergence Card */}
                <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-black uppercase text-purple-500 tracking-widest block mb-1">Gain d'Information</span>
                    <h4 className="text-xl font-black text-slate-800 dark:text-white uppercase tracking-tight mb-2">Divergence KL</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                      Divergence de Kullback-Leibler. Quantité d'information stochastique perdue en approximant la distribution réelle.
                    </p>
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-slate-800 dark:text-white font-mono">
                      {report.kl_divergence !== undefined ? report.kl_divergence.toFixed(4) : "N/A"}
                    </span>
                    <span className="text-xs font-bold text-slate-400">nats</span>
                  </div>
                </div>

                {/* 4. Shannon Entropy */}
                <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-black uppercase text-amber-500 tracking-widest block mb-1">Incertitude du Système</span>
                    <h4 className="text-xl font-black text-slate-800 dark:text-white uppercase tracking-tight mb-2">Entropie de Shannon</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                      Incertitude intrinsèque du vecteur de prédiction avant le tirage. Une entropie basse indique des cibles fortes.
                    </p>
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-slate-800 dark:text-white font-mono">
                      {report.shannon_entropy !== undefined ? report.shannon_entropy.toFixed(2) : "N/A"}
                    </span>
                    <span className="text-xs font-bold text-slate-400">bits</span>
                  </div>
                </div>

                {/* 5. Benford Compliance */}
                <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-black uppercase text-emerald-500 tracking-widest block mb-1">Intégrité Logarithmique</span>
                    <h4 className="text-xl font-black text-slate-800 dark:text-white uppercase tracking-tight mb-2">Loi de Benford</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                      Degré de conformité de la distribution des premiers chiffres significatifs de l'historique par rapport à la loi logarithmique standard.
                    </p>
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-slate-800 dark:text-white font-mono">
                      {report.benfordCompliance !== undefined ? (report.benfordCompliance * 100).toFixed(1) : "N/A"}
                    </span>
                    <span className="text-xs font-bold text-slate-400">% conformité</span>
                  </div>
                </div>

                {/* 6. Continuous Topological Loss */}
                <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-black uppercase text-pink-500 tracking-widest block mb-1">Maniabilité de Grille</span>
                    <h4 className="text-xl font-black text-slate-800 dark:text-white uppercase tracking-tight mb-2">Perte Topologique</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                      Mesure continue de la dispersion géométrique sur l'attracteur spatial par rapport à la grille bidimensionnelle idéale.
                    </p>
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-slate-800 dark:text-white font-mono">
                      {report.continuousTopologicalLoss !== undefined ? report.continuousTopologicalLoss.toFixed(4) : "N/A"}
                    </span>
                    <span className="text-xs font-bold text-slate-400">T-loss</span>
                  </div>
                </div>
              </div>

              {/* Catastrophe / Thom Params */}
              {report.catastropheControlParams && (
                <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md">
                  <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-4">
                    <Cpu size={18} className="text-rose-500" />
                    Théorie des Catastrophes & Paramètres de Contrôle
                  </h4>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mb-6 leading-relaxed">
                    Sous le modèle topologique d'une fronce de René Thom, l'instabilité structurelle est mesurée par le discriminant bistable Δ. Si le discriminant passe sous 0, le système entre en état de bifurcation, générant des transitions d'écart brutales.
                  </p>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="p-4 bg-slate-50 dark:bg-black/25 rounded-xl border border-slate-100 dark:border-slate-800">
                      <span className="text-[10px] font-mono text-slate-400 block">PARAMÈTRE DE COMPRESSION (a)</span>
                      <span className="text-lg font-black text-indigo-500 font-mono">{report.catastropheControlParams.a.toFixed(5)}</span>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-black/25 rounded-xl border border-slate-100 dark:border-slate-800">
                      <span className="text-[10px] font-mono text-slate-400 block">ASYMÉTRIE DE DÉRIVE (b)</span>
                      <span className="text-lg font-black text-indigo-500 font-mono">{report.catastropheControlParams.b.toFixed(5)}</span>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-black/25 rounded-xl border border-slate-100 dark:border-slate-800">
                      <span className="text-[10px] font-mono text-slate-400 block">DISCRIMINANT (Δ = 4a³ + 27b²)</span>
                      <span className={`text-lg font-black font-mono ${report.catastropheControlParams.discriminant <= 0 ? "text-rose-500" : "text-emerald-500"}`}>
                        {report.catastropheControlParams.discriminant.toFixed(5)}
                      </span>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-black/25 rounded-xl border border-slate-100 dark:border-slate-800">
                      <span className="text-[10px] font-mono text-slate-400 block">RÉGIME ACTIF</span>
                      <span className="text-xs font-black uppercase text-slate-850 dark:text-slate-100 block mt-1 tracking-wider">
                        {report.catastropheControlParams.regime.replace(/_/g, " ")}
                      </span>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {activeTab === "counterfactuals" && (
            <div className="animate-slide-up space-y-6">
              <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl">
                <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-4">
                  <GitMerge size={18} className="text-emerald-500" />
                  Optimisation Contre-Factuelle (Correction Gradient)
                </h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 mb-8 leading-relaxed">
                  Cette analyse rétrospective simule quel aurait été l'impact si nous avions modifié dynamiquement l'importance (le poids ADN) de chaque algorithme juste avant le tirage. Les écarts mesurés par rapport à l'impact réel nous donnent le gradient exact de correction à appliquer.
                </p>

                {report.counterfactuals && report.counterfactuals.length > 0 ? (
                  <div className="space-y-6">
                    {report.counterfactuals.map((cf, idx) => {
                      const delta = cf.proposedWeightChange !== undefined ? cf.proposedWeightChange : (cf.optimalWeight - cf.originalWeight);
                      return (
                        <div key={idx} className="p-6 bg-slate-50 dark:bg-black/25 border border-slate-200 dark:border-slate-800 rounded-2xl flex flex-col md:flex-row md:items-center justify-between gap-6 transition-all hover:border-emerald-500/20">
                          <div className="flex-1 space-y-2">
                            <div className="flex items-center gap-3">
                              <span className="text-xs font-mono font-black text-emerald-500 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded-md uppercase">
                                {cf.action || (delta > 0 ? "BOOST" : "REDUCE")}
                              </span>
                              <h5 className="font-bold text-slate-800 dark:text-white capitalize">
                                {cf.algo.replace(/_/g, " ")}
                              </h5>
                            </div>
                            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium">
                              {cf.description || `Ajuster le poids global permettrait d'accroître l'alignement sur les tendances de ce tirage.`}
                            </p>
                            {cf.potentialNumbers && cf.potentialNumbers.length > 0 && (
                              <div className="flex items-center gap-2 mt-2 flex-wrap">
                                <span className="text-[10px] font-black uppercase text-slate-400">Numéros Ciblés :</span>
                                {cf.potentialNumbers.map((n) => (
                                  <span key={n} className="px-1.5 py-0.5 rounded bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-mono text-[10px] font-bold">
                                    {n}
                                  </span>
                                ))}
                              </div>
                            )}
                          </div>

                          <div className="flex md:flex-col items-end gap-4 justify-between shrink-0">
                            <div className="text-right">
                              <span className="text-[10px] font-black text-slate-400 uppercase block">Amélioration Potentielle</span>
                              <span className="text-xl font-black text-emerald-500 font-mono">+{cf.improvement.toFixed(1)}%</span>
                            </div>

                            <div className="flex items-center gap-4">
                              <div className="text-center">
                                <span className="text-[8px] font-black text-slate-400 uppercase block">Poids initial</span>
                                <span className="font-mono text-xs text-slate-600 dark:text-slate-400">{(cf.originalWeight * 100).toFixed(1)}%</span>
                              </div>
                              <ArrowRight size={12} className="text-slate-400" />
                              <div className="text-center">
                                <span className="text-[8px] font-black text-emerald-500 uppercase block">Poids Optima</span>
                                <span className="font-mono text-xs font-black text-emerald-500">{(cf.optimalWeight * 100).toFixed(1)}%</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                ) : (
                  <p className="text-xs text-slate-400 italic text-center py-6">Aucune contre-analyse d'ADN disponible pour ce tirage.</p>
                )}
              </div>
            </div>
          )}

          {activeTab === "spectral" && (
            <div className="animate-slide-up space-y-6">
              <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl">
                <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-4">
                  <Waves size={18} className="text-cyan-500" />
                  Divergence de Spectre d'Énergie Spectrale
                </h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 mb-8 leading-relaxed">
                  Chaque numéro vibre sur une fréquence d'apparition théorique modulée par transformée de Fourier discrète (DFT). Ce tableau quantifie le delta énergétique entre les probabilités attribuées par le spectre et le résultat concret du tirage réel (100 si sorti, 0 sinon).
                </p>

                {report.spectralDeviations && report.spectralDeviations.length > 0 ? (
                  <div className="grid gap-3 max-h-[500px] overflow-y-auto custom-scrollbar pr-2">
                    {report.spectralDeviations.map((spec, idx) => {
                      const absoluteDelta = Math.abs(spec.delta);
                      return (
                        <div key={idx} className="flex items-center justify-between p-4 bg-slate-50 dark:bg-black/25 border border-slate-200 dark:border-slate-800 rounded-xl transition-all hover:bg-slate-100/50 dark:hover:bg-slate-800/50">
                          <div className="flex items-center gap-4">
                            <NumberBall number={spec.number} size="sm" />
                            <div>
                              <span className="text-xs font-black text-slate-700 dark:text-slate-300">Numéro {spec.number}</span>
                              <span className="text-[10px] text-slate-400 block font-medium">Analyse d'énergie par déviation spectrale</span>
                            </div>
                          </div>

                          <div className="flex items-center gap-8 font-mono text-xs">
                            <div className="text-right">
                              <span className="text-[8px] font-black text-slate-400 uppercase block">Énergie Prédite</span>
                              <span className="text-slate-700 dark:text-slate-300">{spec.predictedEnergy.toFixed(2)}</span>
                            </div>

                            <div className="text-right">
                              <span className="text-[8px] font-black text-slate-400 uppercase block">Énergie Réelle</span>
                              <span className={`font-bold ${spec.actualEnergy > 0 ? "text-emerald-500" : "text-slate-400"}`}>{spec.actualEnergy.toFixed(0)}</span>
                            </div>

                            <div className="text-right w-16">
                              <span className="text-[8px] font-black text-slate-400 uppercase block">Δ Delta</span>
                              <span className={`font-black ${absoluteDelta > 40 ? "text-rose-500" : "text-indigo-500"}`}>
                                {spec.delta > 0 ? "+" : ""}{spec.delta.toFixed(1)}
                              </span>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                ) : (
                  <p className="text-xs text-slate-400 italic text-center py-6">Aucune déviation spectrale disponible pour ce tirage.</p>
                )}
              </div>
            </div>
          )}

          {activeTab === "xap" && (
            <div className="animate-slide-up space-y-6">
              <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl relative">
                <div className="absolute top-4 right-4 flex gap-2">
                  {report.consensusStrength !== undefined && (
                    <span className="text-[10px] font-mono font-bold bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-300 px-2 py-0.5 border border-indigo-100 dark:border-indigo-800 rounded">
                      Consensus : {report.consensusStrength.toFixed(0)}%
                    </span>
                  )}
                  {report.antiConsensusActive && (
                    <span className="text-[10px] font-black uppercase text-rose-500 bg-rose-500/10 border border-rose-500/20 px-2 py-0.5 rounded">
                      🛡️ ADVERSARIAL ACTIVE
                    </span>
                  )}
                </div>

                <h4 className="font-black text-slate-800 dark:text-white uppercase text-sm tracking-widest flex items-center gap-2 mb-4">
                  <Cpu size={18} className="text-blue-500" />
                  Génome Oraculaire & Explications de Décision XAP
                </h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 mb-8 leading-relaxed">
                  La méthode eXplainable AI (XAP) dissèque l'origine de l'énergie prédictive de chaque numéro gagnant au sein du réseau d'algorithmes combinés. Elle retrace quelle composante du code génétique a joué le rôle de catalyseur principal.
                </p>

                {report.winningXAP && report.winningXAP.length > 0 ? (
                  <div className="space-y-6">
                    {report.winningXAP.map((xap, idx) => (
                      <div key={idx} className="p-6 bg-slate-50 dark:bg-black/25 border border-slate-200 dark:border-slate-800 rounded-2xl space-y-4 animate-fade-in">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-4">
                            <NumberBall number={xap.number} size="sm" glow={true} />
                            <div>
                              <h5 className="font-black text-slate-800 dark:text-white text-sm">
                                Numéro {xap.number}
                              </h5>
                              <p className="text-xs text-slate-400 font-mono">
                                Algorithme Guide : <span className="font-bold text-indigo-500 capitalize">{xap.dominantAlgo.replace(/_/g, " ")}</span>
                              </p>
                            </div>
                          </div>

                          <div className="text-right">
                            <span className="text-[8px] font-black text-slate-400 uppercase block">Contribution Principale</span>
                            <span className="text-lg font-black text-indigo-500 font-mono">{(xap.contributionPercentage).toFixed(1)}%</span>
                          </div>
                        </div>

                        {/* Entropy and Gini */}
                        {(xap.compositionEntropy !== undefined || xap.compositionGini !== undefined) && (
                          <div className="grid grid-cols-2 gap-4 py-2 bg-slate-100/50 dark:bg-black/10 rounded-xl px-4 text-xs font-mono">
                            {xap.compositionEntropy !== undefined && (
                              <div className="flex justify-between items-center">
                                <span className="text-slate-400">Entropie de Composition :</span>
                                <span className="font-bold text-slate-700 dark:text-slate-300">{(xap.compositionEntropy).toFixed(3)}</span>
                              </div>
                            )}
                            {xap.compositionGini !== undefined && (
                              <div className="flex justify-between items-center">
                                <span className="text-slate-400">Index de Gini (Inégalité) :</span>
                                <span className="font-bold text-slate-700 dark:text-slate-300">{(xap.compositionGini).toFixed(3)}</span>
                              </div>
                            )}
                          </div>
                        )}

                        {/* DNA Vector display */}
                        {xap.dnaVector && (
                          <div className="space-y-2">
                            <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 block">Vecteur d'Affinité de l'ADN</span>
                            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                              {Object.entries(xap.dnaVector).map(([algo, val]) => {
                                const weightPercentage = Number(val) * 100;
                                return (
                                  <div key={algo} className="p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg text-[9px] font-mono">
                                    <div className="flex justify-between font-bold mb-1">
                                      <span className="text-slate-500 truncate capitalize" title={algo}>{algo.replace(/_/g, " ")}</span>
                                      <span className="text-indigo-500">{weightPercentage.toFixed(1)}%</span>
                                    </div>
                                    <div className="w-full h-1 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                                      <div className="h-full bg-indigo-500 rounded-full" style={{ width: `${Math.min(100, weightPercentage)}%` }} />
                                    </div>
                                  </div>
                                );
                              })}
                            </div>
                          </div>
                        )}

                        {/* Synergy Algos */}
                        {xap.synergyAlgos && xap.synergyAlgos.length > 0 && (
                          <div className="flex items-center gap-2 flex-wrap pt-2">
                            <span className="text-[10px] font-black uppercase text-slate-400">Co-contributeurs (Synergie) :</span>
                            {xap.synergyAlgos.map((algo) => (
                              <span key={algo} className="px-2 py-0.5 rounded bg-blue-500/10 border border-blue-500/20 text-blue-500 font-mono text-[9px] font-bold capitalize">
                                {algo.replace(/_/g, " ")}
                              </span>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-slate-400 italic text-center py-6">Aucune explication décisionnelle oraculaire (XAP) disponible.</p>
                )}
              </div>
            </div>
          )}

          {/* Feedback Form */}
          <div className="border-t border-slate-200 dark:border-slate-800 pt-8">
            <div className="flex items-center gap-3 mb-4">
              <MessageSquare size={18} className="text-slate-400" />
              <h4 className="font-black text-slate-600 dark:text-slate-300 uppercase text-xs tracking-widest">
                Feedback Opérateur (RLHF)
              </h4>
            </div>

            {feedbackSent ? (
              <div className="bg-emerald-50 dark:bg-emerald-900/20 p-4 rounded-2xl border border-emerald-200 dark:border-emerald-800 text-center animate-fade-in">
                <p className="text-emerald-700 dark:text-emerald-400 font-bold flex items-center justify-center gap-2">
                  <CheckCircle2 size={16} /> Signal RL transmis avec succès
                </p>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="flex gap-2 justify-center">
                  {[
                    {
                      id: "Visionnaire",
                      icon: <ThumbsUp size={16} />,
                      color: "bg-emerald-500",
                    },
                    {
                      id: "Standard",
                      icon: <Meh size={16} />,
                      color: "bg-amber-500",
                    },
                    {
                      id: "Incohérente",
                      icon: <ThumbsDown size={16} />,
                      color: "bg-rose-500",
                    },
                  ].map((rate) => (
                    <button
                      key={rate.id}
                      onClick={() => {
                        audioEngine.play("click");
                        setUserRating(
                          rate.id as PredictionFeedback["userRating"],
                        );
                      }}
                      className={`flex-1 py-3 rounded-xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all transform active:scale-95 ${userRating === rate.id ? `${rate.color} text-white shadow-lg scale-105` : "bg-slate-100 dark:bg-slate-800 text-slate-500 hover:bg-slate-200 dark:hover:bg-slate-700"}`}
                    >
                      {rate.icon} {rate.id}
                    </button>
                  ))}
                </div>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={userComment}
                    onChange={(e) => setUserComment(e.target.value)}
                    placeholder="Observation technique optionnelle..."
                    className="flex-1 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 text-xs outline-none focus:border-indigo-500 transition-colors"
                  />
                  <button
                    onClick={handleSubmitFeedback}
                    disabled={!userRating || submittingFeedback}
                    className="px-6 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-xl font-black text-[10px] uppercase tracking-widest disabled:opacity-50 hover:opacity-90 transition-opacity"
                  >
                    Envoyer
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
