import { useState, useCallback, useMemo, useRef, useEffect } from 'react';
import { useNexusStore } from '../store/useNexusStore';
import { generateMasterPrediction, getStrategyName, getAlgoWeights, normalizeWeights } from '../services/predictionEngine';
import { savePredictionToHistory } from '../services/predictionHistoryService';
import { calculateShannonEntropy, detectGameRegime } from '../services/mathService';
import { getLocalForensicReports } from '../services/postPredictionAnalysisService';
import { LearningService } from '../services/learningService';
import { DEFAULT_ALGO_WEIGHTS, AlgoKey } from '../shared/prediction.types';
import { DNAOptimizer } from '../services/training/DNAOptimizer';
import { useFeatureFlags } from '../services/prediction/featureFlags';
import { useToast } from '../components/ui/Toast';
import { audioEngine } from '../utils/audioEngine';
import type { AlgoWeights, Prediction } from '../types';

export const usePredictionGenerator = (drawName: string) => {
    const { showToast } = useToast();
    const history = useNexusStore(state => state.history);
    const temporalDepth = useNexusStore(state => state.temporalDepth);
    const setLastPrediction = useNexusStore(state => state.setLastPrediction);
    const globalWeights = useNexusStore(state => state.globalWeights);
    const updateGlobalWeights = useNexusStore(state => state.updateGlobalWeights);
    const spectral = useNexusStore(state => state.spectral);
    const correlationMatrix = useNexusStore(state => state.correlationMatrix);
    const regularity = useNexusStore(state => state.regularity);
    const volatility = useNexusStore(state => state.volatility);
    const symbioticContext = useNexusStore(state => state.symbioticContext);
    const fractal = useNexusStore(state => state.fractal);
    // @ts-ignore - auto generated by cleanup
    const isForensicOptimized = useNexusStore(state => state.isForensicOptimized);

    const [isComputing, setIsComputing] = useState(false);
    const [computingStep, setComputingStep] = useState<string>("");
    const [computingProgress, setComputingProgress] = useState<number>(0);
    const [activeDNA, setActiveDNA] = useState<string>("Standard");
    const [quantumMode, setQuantumMode] = useState(false);
    const { flags } = useFeatureFlags();
    const [isChaotic, setIsChaotic] = useState(false);
    const lastInferenceStateRef = useRef<string | null>(null);

    const [isOptimizing, setIsOptimizing] = useState(false);
    const [optimizedWeights, setOptimizedWeights] = useState<AlgoWeights | null>(null);
    const [previousWeights, setPreviousWeights] = useState<AlgoWeights | null>(null);

    const currentEntropy = useMemo(() => {
        if (history.length === 0) return 0;
        return calculateShannonEntropy(history.slice(0, 10)).normalized;
    }, [history]);

    const resolvedLearningRate = useMemo(() => {
        return Math.max(0.01, Math.min(0.2, 0.15 * (1.0 - currentEntropy) + 0.01));
    }, [currentEntropy]);

    const resolvedNoiseLevel = useMemo(() => {
        const volScore = volatility?.score || 50;
        return Math.max(0.1, Math.min(3.0, (volScore / 50.0) * (currentEntropy || 0.5) * 1.5 + 0.2));
    }, [currentEntropy, volatility]);

    const resolvedMcIterations = useMemo(() => {
        return Math.max(10, Math.min(100, Math.round(20 + 80 * (currentEntropy || 0.5))));
    }, [currentEntropy]);

    const gameRegimeInfo = useMemo(() => {
        if (!history || history.length < 5) return null;
        try {
            return detectGameRegime(history);
        } catch (e) {
            console.warn("[Oracle Base] Failed to detect game regime:", e);
            return null;
        }
    }, [history]);

    useEffect(() => {
        let active = true;
        const fetchReports = async () => {
            try {
                const rawReports = await getLocalForensicReports();
                if (!rawReports) return;
                const reports = rawReports.filter(r => r.drawName === drawName);
                if (reports.length > 0 && active) {
                    const windowSize = Math.min(10, reports.length);
                    const swans = reports.slice(0, windowSize).filter(r => r.isBlackSwan).length;
                    const chaoticRatio = swans / windowSize;
                    setIsChaotic(chaoticRatio >= 0.25 || (volatility?.score ?? 0) > 85);
                }
            } catch (err) {
                console.warn("[Oracle Base] Reports validation bypassed (local fallback mode active):", err);
            }
        };
        fetchReports();
        return () => { active = false; };
    }, [drawName, volatility]);

    useEffect(() => {
        setLastPrediction(null);
        lastInferenceStateRef.current = null;
    }, [drawName, setLastPrediction]);

    useEffect(() => {
        if (globalWeights) setActiveDNA(getStrategyName(globalWeights));
    }, [globalWeights]);

    const resolveWeights = async (forcedWeights?: AlgoWeights | null) => {
        let specificWeights = forcedWeights || (Object.keys(globalWeights || {}).length > 0 ? { ...globalWeights } as AlgoWeights : null);
        if (!specificWeights) {
            try {
                specificWeights = await getAlgoWeights(drawName);
            } catch (err) {
                console.warn("[Oracle Base] Using local weights library because server was unreachable:", err);
                specificWeights = DEFAULT_ALGO_WEIGHTS;
            }
        }
        return specificWeights;
    };

    const runInference = useCallback(async (forcedWeights?: AlgoWeights) => {
        if (history.length < 5) {
            audioEngine.play('error');
            showToast("Historique insuffisant pour l'Oracle Base.", "error");
            return;
        }
        audioEngine.play('loading');
        setIsComputing(true);
        setComputingStep("Convergence Vectorielle en cours...");

        let specificWeights = await resolveWeights(forcedWeights);

        if (quantumMode) {
            // Mode Quantique (Exploratoire) : au lieu de booster arbitrairement 4 algorithmes,
            // on augmente l'entropie globale de la distribution des poids (relaxation thermique).
            // Les poids se rapprochent de l'uniformité proportionnellement à la volatilité (resolvedNoiseLevel).
            const mixingFactor = Math.min(0.8, resolvedNoiseLevel * 0.15); 
            const numAlgos = Object.keys(specificWeights).length;
            const uniformWeight = 1.0 / (numAlgos || 1);
            
            const smoothedWeights = {} as AlgoWeights;
            Object.keys(specificWeights).forEach((k) => {
                const key = k as keyof AlgoWeights;
                const original = specificWeights![key] || 0;
                // Combinaison convexe entre le poids optimisé et le poids uniforme
                smoothedWeights[key] = original * (1 - mixingFactor) + uniformWeight * mixingFactor;
            });
            specificWeights = normalizeWeights(smoothedWeights);
        }

        if (!forcedWeights) {
            setPreviousWeights(null);
            setOptimizedWeights(null);
            setActiveDNA(quantumMode ? `Quantum ${getStrategyName(specificWeights!)}` : getStrategyName(globalWeights as AlgoWeights));
        }

        try {
            await new Promise(r => setTimeout(r, 150)); 
            const metrics = { spectral, correlationMatrix, regularity, volatility, fractal };
            const res = await generateMasterPrediction(
                drawName,
                history,
                temporalDepth,
                specificWeights!,
                metrics,
                symbioticContext || undefined,
                false,
                flags.adversarialMode,
                undefined,
                isForensicOptimized,
                (progress, step) => {
                    setComputingProgress(progress);
                    setComputingStep(step);
                }
            );
            
            setLastPrediction(res);
            
            try {
                await savePredictionToHistory(drawName, res, undefined, metrics);
            } catch (dbErr) {
                console.warn("[Oracle Base] Local execution success: Prediction not committed to distant repository (network isolated).", dbErr);
            }
            
            if (!forcedWeights) {
                audioEngine.play('success');
                showToast("Prédiction générée via l'ADN actif.", "success");
            }
        } catch (e: any) {
            console.error("[Oracle Base Inference Engine Error]:", e);
            audioEngine.play('error');
            showToast("Erreur d'inférence (Mode secouru actif).", "error");
        } finally {
            setIsComputing(false);
            setComputingStep("");
        }
    }, [drawName, history, spectral, correlationMatrix, regularity, volatility, fractal, symbioticContext, globalWeights, quantumMode, flags.adversarialMode, resolvedNoiseLevel, setLastPrediction, showToast]);



    const runMonteCarlo = useCallback(async () => {
        if (history.length < 10) {
            showToast("Historique insuffisant.", "error");
            return;
        }
        audioEngine.play('scan');
        setIsComputing(true);
        setComputingStep(`Monte-Carlo Déterministe (${resolvedMcIterations} runs)...`);

        try {
            let specificWeights = await resolveWeights();
            const metrics = { spectral, correlationMatrix, regularity, volatility, fractal };
            
            const histSum = history.slice(0, 10).reduce((acc, curr) => acc + curr.gagnants.reduce((a, b) => a + b, 0), 0);
            
            // Linear Congruential Generator (LCG) pour un tirage déterministe et statistiquement indépendant
            const LCG_M = 0x80000000;
            const LCG_A = 1103515245;
            const LCG_C = 12345;
            let lcgSeed = (histSum + history.length) % LCG_M;
            const nextRandom = () => {
                lcgSeed = (LCG_A * lcgSeed + LCG_C) % LCG_M;
                return lcgSeed / LCG_M;
            };
            
            let currentStateVector = new Float32Array(Object.keys(specificWeights).length);
            Object.keys(specificWeights).forEach((k, idx) => {
                currentStateVector[idx] = (specificWeights as any)[k] || 0;
            });
            let currentEnergy = -Infinity; // Sera initialisé à la première itération
            let currentPred: Prediction | null = null;
            
            const counts: Record<number, number> = {};
            const breakdownAcc: Record<number, Record<string, number>> = {};

            for (let i = 0; i < resolvedMcIterations; i++) {
                if (i % 5 === 0) setComputingStep(`MCMC Metropolis-Hastings (${i}/${resolvedMcIterations})...`);
                
                const proposedVector = new Float32Array(currentStateVector.length);
                let sumWeights = 0;
                Object.keys(specificWeights).forEach((_, idx) => {
                    // Bruit gaussien approché
                    const u1 = Math.max(Number.EPSILON, nextRandom());
                    const u2 = Math.max(Number.EPSILON, nextRandom());
                    const z0 = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2);
                    
                    const noise = z0 * 0.1 * resolvedNoiseLevel;
                    proposedVector[idx] = Math.max(0.01, currentStateVector[idx] * (1.0 + noise));
                    sumWeights += proposedVector[idx];
                });
                for(let j=0; j<proposedVector.length; j++) proposedVector[j] /= sumWeights;

                const perturbedWeights = {} as AlgoWeights;
                Object.keys(specificWeights).forEach((k, idx) => {
                    (perturbedWeights as any)[k] = proposedVector[idx];
                });

                // On génère la prédiction pour le vecteur proposé (ceci est la fonction d'évaluation la plus précise possible)
                const pred = await generateMasterPrediction(drawName, history, temporalDepth, perturbedWeights, metrics, symbioticContext || undefined, false, flags.adversarialMode, undefined, isForensicOptimized);
                
                // L'énergie est la "netteté" (sharpness) de la prédiction : écart entre le top 5 et le bruit de fond
                let topScores = [];
                for (let n = 1; n <= 90; n++) {
                    let s = 0;
                    if (pred.breakdown[n]) {
                       Object.values(pred.breakdown[n]).forEach(v => s += v);
                    }
                    topScores.push(s);
                }
                topScores.sort((a,b) => b - a);
                const top5Avg = topScores.slice(0, 5).reduce((a,b)=>a+b, 0) / 5;
                const next15Avg = topScores.slice(5, 20).reduce((a,b)=>a+b, 0) / 15;
                // Plus ce ratio est élevé, plus la prédiction est confiante/nette (moins d'entropie)
                const proposedEnergy = (top5Avg - next15Avg) / (top5Avg || 1);

                if (i === 0) {
                    currentStateVector = proposedVector;
                    currentEnergy = proposedEnergy;
                    currentPred = pred;
                } else {
                    const beta = 1.0 / (resolvedLearningRate + 0.01);
                    // Critère de Metropolis : on veut maximiser l'énergie (la netteté de la prédiction)
                    // clamp ratio à [0, 1]
                    const acceptanceRatio = Math.min(1.0, Math.exp(beta * (proposedEnergy - currentEnergy)));
                    const transitionProb = nextRandom();

                    if (transitionProb < acceptanceRatio) {
                        currentStateVector = proposedVector;
                        currentEnergy = proposedEnergy;
                        currentPred = pred;
                    }
                }

                // On agrège directement l'état courant (accepté ou précédent maintenu) pour éviter les fuites mémoire
                if (currentPred) {
                    currentPred.suggestedNumbers.forEach(n => {
                        counts[n] = (counts[n] || 0) + 1;
                        if (!breakdownAcc[n] && currentPred!.breakdown[n]) {
                            breakdownAcc[n] = { ...currentPred!.breakdown[n] };
                        }
                    });
                }
                
                // Yield thread
                if (i % 2 === 0) {
                    await new Promise(resolve => setTimeout(resolve, 0));
                }
            }

            setComputingStep("Convergence Globale...");

            const topCands = Object.entries(counts)
                .sort((a, b) => b[1] - a[1])
                .map(x => Number(x[0]));
                
            const top5 = topCands.slice(0, 5).sort((a,b) => a - b);
            const candidates = topCands.slice(5, 15);

            const activeWeights = globalWeights || DEFAULT_ALGO_WEIGHTS;
            const optimizer = new DNAOptimizer(Object.keys(activeWeights) as AlgoKey[]);
            const dnaMatrix = top5.map(num => {
                const bdown = breakdownAcc[num] || {};
                const vec = new Float32Array(optimizer['numAlgos']);
                optimizer['algoKeys'].forEach((k, idx) => { vec[idx] = bdown[k] || 0; });
                return vec;
            });

            const historicalVectors: Float32Array[] = [];
            const sampleDepth = Math.min(30, history.length);
            for (let i = 0; i < sampleDepth; i++) {
                const winners = history[i]?.gagnants || [];
                winners.forEach(w => {
                    const bdown = breakdownAcc[w] || {};
                    const vec = new Float32Array(optimizer['numAlgos']);
                    optimizer['algoKeys'].forEach((k, idx) => { vec[idx] = bdown[k] || 0; });
                    historicalVectors.push(vec);
                });
            }

            let calculatedAlignment: number | undefined; 
            if (historicalVectors.length > 0 && dnaMatrix.length > 0) {
                try {
                    const targetProfile = optimizer.extractTargetDNAProfile(historicalVectors, 30);
                    const evaluation = optimizer.evaluateCandidate(dnaMatrix, targetProfile, top5, history.map(h => h.gagnants || []));
                    // L'alignement est fonction exponentielle inverse de la distance euclidienne (plus rigoureux que 105 / (1+d))
                    calculatedAlignment = Math.round(100 * Math.exp(-evaluation.distance));
                } catch(e) {
                    console.warn("[MC] DNA Evaluation bypassed:", e);
                }
            }

            // Consensus MCMC : pourcentage moyen d'apparition des 5 meilleurs numéros au fil des itérations
            const top5Consensus = top5.reduce((sum, n) => sum + counts[n], 0) / (5 * resolvedMcIterations);
            const dynamicConfidence = Math.round(Math.min(99, Math.max(10, top5Consensus * 100)));

            const aggregatedPred: Prediction = {
                suggestedNumbers: top5,
                candidates: candidates,
                breakdown: breakdownAcc as any,
                confidence: dynamicConfidence,
                analysis: `Convergence MCMC Metropolis-Hastings avec alignement historique de ${calculatedAlignment !== undefined ? calculatedAlignment + '%' : 'Non calculable'}. Moteur cybernétique optimisé.`,
                timestamp: Date.now(),
                realityAlignment: calculatedAlignment,
                diversityMetrics: {
                    meanSimilarity: 0.1,
                    diversityScore: 0.9,
                    penalty: 0,
                    isMonoculture: false,
                    pairwiseSimilarities: [],
                    dominantAlgo: "MCMC"
                }
            };

            setLastPrediction(aggregatedPred);
            
            try {
                await savePredictionToHistory(drawName, aggregatedPred, undefined, metrics);
            } catch (dbErr) {
                console.warn("[Oracle MC] Local fallback success:", dbErr);
            }
            
            setActiveDNA("Monte-Carlo (MCMC)");
            audioEngine.play("success");
            showToast(`Convergence MC achevée avec succès.`, "success");

        } catch (e: any) {
            console.error("Monte Carlo Failed:", e);
            audioEngine.play("error");
            showToast("Echec du process stochastique MCMC.", "error");
        } finally {
            setIsComputing(false);
            setComputingStep("");
        }
    }, [history, drawName, resolvedMcIterations, resolvedNoiseLevel, resolvedLearningRate, flags.adversarialMode, spectral, correlationMatrix, regularity, volatility, fractal, symbioticContext, globalWeights, currentEntropy, setLastPrediction, showToast]);

    const handleOptimizeWeights = async () => {
        if (!navigator.onLine) {
            showToast("Mode hors-ligne : Apprentissage suspendu.", "error");
            return;
        }
        audioEngine.play("scan");
        setIsOptimizing(true);
        setComputingStep("Extraction du Signal Forensic...");
        try {
            const currentW = globalWeights || DEFAULT_ALGO_WEIGHTS;
            setPreviousWeights({ ...currentW } as AlgoWeights);

            const result = await LearningService.triggerAutoLearning(drawName);
            
            if (result && result.weights) {
                setOptimizedWeights(result.weights);
                await updateGlobalWeights(result.weights, drawName);
                
                audioEngine.play("success");
                showToast(`ADN Optimisé : + ${result.delta || "0.00"}% performance.`, "success");
                
                await runInference(result.weights);
            } else {
                audioEngine.play("click");
                showToast("Les matrices actuelles sont déjà optimales pour la structure stochastique en cours.", "info");
            }

        } catch (error) {
            console.error("Failed to optimize weights:", error);
            audioEngine.play("error");
            showToast("Erreur lors de l'apprentissage des poids.", "error");
        } finally {
            setIsOptimizing(false);
            setComputingStep("");
        }
    };

    return {
        isComputing,
        computingStep,
        computingProgress,
        activeDNA,
        quantumMode,
        setQuantumMode,
        isChaotic,
        isOptimizing,
        optimizedWeights,
        previousWeights,
        currentEntropy,
        resolvedLearningRate,
        resolvedNoiseLevel,
        resolvedMcIterations,
        gameRegimeInfo,
        runInference,
        runMonteCarlo,
        handleOptimizeWeights
    };
};
